### ISSUE TITLE
Read interleaved paired-end file

### ISSUE THREAD

**Issue by pschwien** [marcelm/cutadapt#113]
Hi,
it would be great if cutadapt could read a single paired end file in interleaved format in addition to having the paired reads in separate files. This may sound unimportant since it is easy enough to generate two input files but in large pipelines that use the interleaved format it can take quite some time and space to split them and later re-combine.

Best regards,
Patrick

**Comment by marcelm** [comment]
Sounds like a good suggestion. I guess some kind of `--interleaved` switch that enables both interleaved input and output would be sufficient, right? I’m not sure when I have time to implement this (it’s not hard, but testing always takes a bit of time).

**Comment by pschwien** [comment]
Hi Marcel,
I would be happy to assist in testing this new functionality.

Best,
Patrick

**Comment by marcelm** [comment]
I’ve just committed support for reading/writing of interleaved FASTQ files. As mentioned above, use the `--interleaved` switch to enable this.

My assessment of “it’s not too hard” was a bit optimistic as adding this functionality turned out to require some larger refactoring. With the integrated changes, however, it should become much easier to support other file formats if necessary (BAM, for example).

Check out the most recent version from Git or wait until cutadapt 1.9 is released to get the new functionality.
