### ISSUE TITLE
Error in setup.py syntax

### ISSUE THREAD

**Issue by thetrio84** [marcelm/cutadapt#125]
When installing using "python setup.py install --user" I get the error message:

 File "setup.py", line 33
    csource = path + ('.cpp' if extension.language == 'c++' else '.c')
                                           ^
SyntaxError: invalid syntax

I figure this is a mistake in the setup.py file. I am installing this remotely on a computer running Linux. Any idea what I can do to remedy this situation?

Thanks.

**Comment by marcelm** [comment]
I think this is due to a too old Python version. At least Python 2.6 is required. But I guess you have already noticed that since you closed the issue ...

I’ve changed the setup script such that it prints out a more comprehensible error message instead. Thanks for reporting.

**Comment by thetrio84** [comment]
You're right. In fact, since I was running it on a cluster, I had to load the python module before trying the install. Thanks for your help.

As a follow up installation question,  I was wondering if I had installed the program correctly. The cutadapt-1.8.1 folder is in my $PATH directory, but I still can't call the "cutadapt" function without having "python" before it. (I.e. when I'm in the cutadapt directory, I cannot use "cutadapt -a", I must use "python cutadapt -a ...". When I'm out of the $PATH directory, even "python cutadapt -a ..." doesn't work.) This causes a pipeline using cutadapt to fail. Is there an executable file that I can put in my $PATH directory to make "cutadapt" work from any directory?

Thanks again for your prompt response.

**Comment by marcelm** [comment]
The cutadapt binary is in the `bin` subdirectory of the cutadapt-1.8.1 folder, so if you want to run it, use `bin/cutadapt`. You cannot take that executable and put it somewhere else since the Python modules need to be installed as well.

However, the recommended way to install cutadapt is to use `pip install --user cutadapt` (this also downloads the tarball for you). If you don’t have pip, then you can run `python setup.py install --user` from within the unpacked tarball. The result is the same in both cases: The binary plus the required Python modules are installed under `$HOME/.local/`. You then need to add `$HOME/.local/bin` to your PATH.

Currently, it also works to just add the `cutadapt-1.8.1/bin` directory to your PATH instead of a proper installation.

**Comment by thetrio84** [comment]
Thank you! That has resolved my issue! Much appreciated.
