### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by kyleabeauchamp** [marcelm/cutadapt#131]
I found some test failures on my OSX / Anaconda install of the latest github version.  Most of the tests are similar to the first one (`_align`).

```
nosetests 
EEE....EEE.......F........EE
[...]
src/software/cutadapt/cutadapt/align.py", line 9, in <module>
    from cutadapt._align import Aligner, compare_prefixes, locate
ImportError: No module named _align

src/software/cutadapt/cutadapt/modifiers.py", line 110, in __call__
    start, stop = quality_trim_index(read.qualities, self.cutoff_front, self.cutoff_back, self.base)
TypeError: quality_trim_index() takes at most 3 arguments (4 given)
[...]
    raise AssertionError(message)
AssertionError: test_fastq_incomplete() did not raise FormatError
```

**Comment by marcelm** [comment]
Since I’m developing on Linux only, I’m happy to hear that some of the tests pass on OS X ...! More seriously, though, the problem is the ImportError which shows that an extension module was not compiled. Do you only have problems with the tests or does the program itself also not run? If it’s only the tests, then I’m inclined to ignore this since I’m not working with OS X and I can therefore not debug it. Otherwise, did you run `python setup.py install`? This will compile and install the modules. You can also compile the modules only (without installing them) with `python setup.py build_ext -i`.

**Comment by marcelm** [comment]
I got a colleague to test the installation on OS X. It worked for him using these commands:
```
sudo easy_install pip
pip install --user --upgrade cutadapt
```
The script was put into `/Users/username/Library/Python/2.7/bin/cutadapt` and worked fine.
