### ISSUE TITLE
Reads cleaved differently when using wildcard N instead of G at the end of adapter sequence

### ISSUE THREAD

**Issue by komalsrathi** [marcelm/cutadapt#141]
Hi Marcel,

I am very confused by my results. I will try to explain whats going on and can you suggest a solution?

I have two adapters that I am trying to cleave. I ran my dataset using two different commands & getting very different results:

```
# command 1
cutadapt --untrimmed-output=sample_untrimmed.fa -a short_adpt=GTTTTAGAGCTAG -g long_adpt=GTGGAAAGGACGAAACACCG --times=2 --error-rate=0.1 --output={name}_trimmed.fa --info-file=sample_info.txt sample.reads.fa

# using this command I get 8 reads mapped to a certain ID
# this is the info file for those 8 reads showing how they were cleaved
# info file
HWI-D00712:1134:C6NMYANXX:5:1114:15798:2655 1:N:0:GTGGCC	1	5	25	ATCTC	GTGGAAAGGACGAAACACAG	ACAGTGATTGTGGACATGCGGTTTA	long_adpt
HWI-D00712:1134:C6NMYANXX:5:1207:19711:40183 1:N:0:GTGGCC	1	5	25	ATCTC	GTGGAAAGGACGAAACACAG	ACAGTGATTGTGGACATGCGGTTTA	long_adpt
HWI-D00712:1134:C6NMYANXX:5:1213:18632:18006 1:N:0:GTGGCC	1	6	26	GATCTT	GTGGAAAGGACGAAACACAG	ACAGTGATTGTGGACATGCGGTTT	long_adpt
HWI-D00712:1134:C6NMYANXX:5:1213:18632:18006 1:N:0:GTGGCC	0	20	24	ACAGTGATTGTGGACATGCG	GTTT		short_adpt
HWI-D00712:1134:C6NMYANXX:5:2116:6547:23967 1:N:0:GTGGCC	2	6	25	GATCTC	GTGGAAGGACGAAACACAG	ACAGTGATTGTGGACATGCGGTTTA	long_adpt
HWI-D00712:1134:C6NMYANXX:5:2209:15361:46886 1:N:0:TTGGCC	1	8	28	TCGAACTC	GTGGAAAGGACGAAACACAG	ACAGTGATTGTGGACATGCGGT	long_adpt
HWI-D00712:1134:C6NMYANXX:5:2209:5029:90727 1:N:0:GTGGCC	1	8	28	TCGAACTC	GTGGAAAGGACGAAACACAG	ACAGTGATTGTGGACATGCGGT	long_adpt
HWI-D00712:1134:C6NMYANXX:5:2301:11648:18509 1:N:0:GTGGCC	1	3	23	CGA	GTGGAAAGGACGAAACACAG	ACAGTGATTGTGGACATGCGGTTTAGA	long_adpt
HWI-D00712:1134:C6NMYANXX:5:2302:9600:26028 1:N:0:GTGGCC	1	1	21	C	GTGGAAAGGACGAAACACAG	ACAGTGATTGTGGACATGCGGTTTAGAGC	long_adpt
HWI-D00712:1134:C6NMYANXX:5:2302:9600:26028 1:N:0:GTGGCC	1	19	29	ACAGTGATTGTGGACATGC	GGTTTAGAGC		short_adpt

# First sequence represents the actual adapter (long_adpt) that was used in commandline
# subsequent sequences are the ones that were identified as "long-adapter" and cleaved from the sequence
GTGGAAAGGACGAAACACCG
GTGGAAAGGACGAAACACAG
GTGGAAAGGACGAAACACAG
GTGGAAAGGACGAAACACAG
GTGGAAGGACGAAACACAG
GTGGAAAGGACGAAACACAG
GTGGAAAGGACGAAACACAG
GTGGAAAGGACGAAACACAG
GTGGAAAGGACGAAACACAG

# command 2
# the only change is that the last bp of long_adpt is converted from G -> N
cutadapt --untrimmed-output=sample_untrimmed.fa -a short_adpt=GTTTTAGAGCTAG -g long_adpt=GTGGAAAGGACGAAACACCN --times=2 --error-rate=0.1 --output={name}_trimmed.fa --info-file=sample_info.txt sample.reads.fa

# using this command I get 0 reads mapped to a certain ID
# this is the info file for those 8 reads that previously mapped to this ID but now they do not  map
# info file to show how they were cleaved this time 
HWI-D00712:1134:C6NMYANXX:5:1114:15798:2655 1:N:0:GTGGCC	1	5	24	ATCTC	GTGGAAAGGACGAAACACA	GACAGTGATTGTGGACATGCGGTTTA	long_adpt
HWI-D00712:1134:C6NMYANXX:5:1207:19711:40183 1:N:0:GTGGCC	1	5	24	ATCTC	GTGGAAAGGACGAAACACA	GACAGTGATTGTGGACATGCGGTTTA	long_adpt
HWI-D00712:1134:C6NMYANXX:5:1213:18632:18006 1:N:0:GTGGCC	1	6	25	GATCTT	GTGGAAAGGACGAAACACA	GACAGTGATTGTGGACATGCGGTTT	long_adpt
HWI-D00712:1134:C6NMYANXX:5:1213:18632:18006 1:N:0:GTGGCC	0	21	25	GACAGTGATTGTGGACATGCG	GTTT		short_adpt
HWI-D00712:1134:C6NMYANXX:5:2116:6547:23967 1:N:0:GTGGCC	2	6	24	GATCTC	GTGGAAGGACGAAACACA	GACAGTGATTGTGGACATGCGGTTTA	long_adpt
HWI-D00712:1134:C6NMYANXX:5:2209:15361:46886 1:N:0:TTGGCC	1	8	27	TCGAACTC	GTGGAAAGGACGAAACACA	GACAGTGATTGTGGACATGCGGT	long_adpt
HWI-D00712:1134:C6NMYANXX:5:2209:5029:90727 1:N:0:GTGGCC	1	8	27	TCGAACTC	GTGGAAAGGACGAAACACA	GACAGTGATTGTGGACATGCGGT	long_adpt
HWI-D00712:1134:C6NMYANXX:5:2301:11648:18509 1:N:0:GTGGCC	1	3	22	CGA	GTGGAAAGGACGAAACACA	GACAGTGATTGTGGACATGCGGTTTAGA	long_adpt
HWI-D00712:1134:C6NMYANXX:5:2302:9600:26028 1:N:0:GTGGCC	1	1	20	C	GTGGAAAGGACGAAACACA	GACAGTGATTGTGGACATGCGGTTTAGAGC	long_adpt
HWI-D00712:1134:C6NMYANXX:5:2302:9600:26028 1:N:0:GTGGCC	1	20	30	GACAGTGATTGTGGACATGC	GGTTTAGAGC		short_adpt

# First sequence represents the actual adapter (long_adpt) that was used in commandline
# subsequent sequences are the ones that were identified as "long-adapter" and cleaved from the sequence
GTGGAAAGGACGAAACACCG
GTGGAAAGGACGAAACACA
GTGGAAAGGACGAAACACA
GTGGAAAGGACGAAACACA
GTGGAAGGACGAAACACA
GTGGAAAGGACGAAACACA
GTGGAAAGGACGAAACACA
GTGGAAAGGACGAAACACA
GTGGAAAGGACGAAACACA
```

Can you please tell me why the 8 reads are cleaved so differently from the last time when I have the same parameters and just substituted the last bp to N.

Thanks!

**Comment by marcelm** [comment]
Hi, I admit this is a bit unexpected, but it is probably due to cutadapt allowing indels in the alignment. I have used the first read and the long adapter only and shortened both a bit to see more easily what is going on. In the first case, with a `G` in the end, this is the resulting alignment (read on top, adapter on bottom):
```
A CGAAACACAG ACAGTGATTGT
  CGAAACACCG
```
In the second case, the alignment is this one:
```
A CGAAACAC-A GACAGTGATTGT
  CGAAACACCN
```
That is, there is a gap in it. The version without a gap is considered to be equivalent since the number of matches is identical in both cases, so cutadapt goes with the first one it finds.

The solution is to either disallow indels or to penalize them more heavily than mismatches, but that needs to be implemented. Cutadapt has a `--no-indels` parameter, but it only works for specific adapter types and not in this case. I’ll see whether I can make `--no-indels` work here as well.

**Comment by komalsrathi** [comment]
I don't understand though. How is using GTGGAAAGGACGAAACACCG alone so different than using GTGGAAAGGACGAAACACCN? Shouldn't it work in the same way but instead of just identifying GTGGAAAGGACGAAACACCG alone, it should identify anything that is GTGGAAAGGACGAAACACCT, GTGGAAAGGACGAAACACCA, GTGGAAAGGACGAAACACCC, GTGGAAAGGACGAAACACCG (with an error rate of .1)?
Alternatively, can I use 4 different adapters? Instead of using N, I will just replace the last character with G, A, C and T and use --times=5 (because I have a short adapter as well, so total 5 adapters)?

**Comment by komalsrathi** [comment]
I just repeated analysis with GTGGAAAGGACGAAACACCT and GTGGAAAGGACGAAACACCG as two separate adapters and gave --times=3 (2 long and one short adapter). But again, some reads are getting lost. Here is the comparison table of mapped read count of when I used the original adapter (```-g long_adpt=GTGGAAAGGACGAAACACCG & --times=2```), using N as the last nucleotide (```-g long_adpt=GTGGAAAGGACGAAACACCN & --times=2```), using two adapters i.e using G & T as last nucleotide (```-g long_adpt=GTGGAAAGGACGAAACACCG -g alt_adpt=GTGGAAAGGACGAAACACCG & --times=3```)

```
ID	Gene	G	N	G.T
MGLibB_01016	2810474O19Rik	20	0	20
MGLibB_04466	Aoc3	15	0	16
MGLibB_06641	Bcas2	2	0	0
MGLibB_06771	Bdkrb2	2	0	2
MGLibB_07744	Cadm2	2	0	0
MGLibB_10816	Clip4	1	0	1
MGLibB_11445	Copa	1	0	1
MGLibB_12609	Cxxc5	1	0	0
MGLibB_12820	Cyp2d11	1	0	0
MGLibB_13637	Ddx47	1	0	1
MGLibB_14248	Dlg1	17	0	0
MGLibB_16067	Eme1	1	0	1
MGLibB_16085	Emilin3	1	0	1
MGLibB_16113	Emr1	3	0	3
MGLibB_16163	Enkd1	1	0	0
MGLibB_18601	Fmnl2	2	0	0
MGLibB_18866	Fpgs	4	0	0
MGLibB_20220	Gm10024	4	0	3
MGLibB_20502	Gm12887	1	0	0
MGLibB_22777	Gpr85	1	0	1
MGLibB_26515	Itgb5	9	0	0
MGLibB_27304	Khnyn	1	0	0
MGLibB_30654	Mcm5	4	0	0
MGLibB_30882	Mef2a	2	0	0
MGLibB_32398	Mtbp	4	0	4
MGLibB_35406	Ogfod2	5	0	5
MGLibB_35506	Olfr1019	1	0	1
MGLibB_35872	Olfr1173	1	0	0
MGLibB_37859	Olfr611	10	0	10
MGLibB_39129	Otx1	5	0	5
MGLibB_40339	Pecam1	1	0	0
MGLibB_41982	Pop1	1	0	1
MGLibB_42099	Ppara	1	0	1
MGLibB_43898	Pvrl2	3	0	3
MGLibB_44955	Rcsd1	1	0	1
MGLibB_44958	Rcvrn	11	0	11
MGLibB_45108	Rer1	1	0	0
MGLibB_46335	Rps11	5	0	5
MGLibB_47170	Scel	2	0	0
MGLibB_47867	Serpinb2	4	0	4
MGLibB_51973	Styx	3	0	3
MGLibB_52130	Surf4	3	0	0
MGLibB_52762	Tas2r121	1	0	1
MGLibB_53354	Telo2	6	0	6
MGLibB_54072	Tm4sf4	11	0	11
MGLibB_55519	Traf2	3	0	3
MGLibB_55896	Trio	8	0	8
MGLibB_56038	Trpc4	1	0	0
MGLibB_57027	Ubqln2	14	0	15
MGLibB_58077	Vmn1r171	1	0	1
MGLibB_58259	Vmn1r228	6	0	6
MGLibB_58479	Vmn1r79	3	0	3
MGLibB_59618	Wrnip1	8	0	6
MGLibB_59783	Xpr1	1	0	0
MGLibB_61862	NonTargetingControlGuideForMouse_0058	1	0	0
MGLibB_62491	NonTargetingControlGuideForMouse_0687	1	0	1
MGLibB_62633	NonTargetingControlGuideForMouse_0829	2	0	2
```

**Comment by marcelm** [comment]
> I don't understand though. How is using GTGGAAAGGACGAAACACCG alone so different than using GTGGAAAGGACGAAACACCN?

I understand your confusion and will try to explain in more detail. Conceptually, the algorithm tries out all possible alignments between the adapter and the read and picks the best one. It is defined to be the one that has the most matching characters in the region where the two sequences overlap. In my small examples above, the adapter has a length of 10 bases and in both cases, 9 bases match.

What happens now is that in the case of the adapter ending with N, the algorithm first tries out the alignment that you see above (with the gap). It tries the other one (without gap) later and since that one is equally good, it will stick to the one it found first and report that. That does not happen when the adapter ends with a G: The algorithm looks at the alignment version that has a gap in it, but it is not as good as the one without a gap, because it has only 8 matches:
```
A CGAAACAC-A GACAGTGATTGT
  CGAAACACCG
```

> and use --times=5

Do *not* use `--times=5`. The number that you give to that option should be the number of adapters that you expect *in each read*. If you have two adapters per read, use `--times=2`. You can still use as many `-a` or `-g` options as you want, cutadapt will try out all of them and remove the one that matches best.

> But again, some reads are getting lost.

Yes, because you will again get alignments with gaps/indels in them. As I said, the solution to this is to have an option to disable indels.

I am also surprised that your downstream analysis is so sensitive to single bases being lost, perhaps you can change that instead.

**Comment by komalsrathi** [comment]
Thank you! Does it look at the order of the adapters in the command line?

**Comment by marcelm** [comment]
The order is not quite as given on the command line (it's more like: first all -a adapters in the order given, then all -g adapters in the order given). I'm not quite sure at the moment, but the behavior if there are equally good adapters is that the first one is used.

**Comment by komalsrathi** [comment]
I am just an informatics person helping someone with pre-processing of the data, not involved with the downstream analysis. I think you are right when you say that the downstream analysis needs to be less sensitive. While I do want to achieve the best possible pipeline, they will have to have accept some level of error as this is true for all high throughput techniques. Thank you for your help!

**Comment by marcelm** [comment]
Hi, I’ve just committed a change that enables the `--no-indels` option for all adapter types. With that, the results should be as you expect them.
To get the new behavior, either get the most recent version from Git or wait until 1.9 is released.
