### ISSUE TITLE
cutadapt error "AssertionError"

### ISSUE THREAD

**Issue by tekkytekky** [marcelm/cutadapt#142]
I use cutadapt in shared server. 
But the version in the server is 1.7.1 ,not lastest (1.8.3).
So I tried to install the lastest version

- - - - - - - - - - - 
pip install cutadapt --upgrade --user
- - - - - - - - - - - 

After this commad execution, I receive the version information following.
- - - - - - - - - - -
$ ~/.local/bin/cutadapt --version
1.8.3
- - - - - - - - - - - 

However, I got an error following when I excute cutadapt for real.

- - - - - - - - - - - 
~/.local/bin/cutadapt -e 1 -g GTTCTTGACCCCC --minimum-length 20 --discard -o out_1.fastq -p out_2.fastq in_1.fastq in_2
This is cutadapt 1.8.3 with Python 2.7.2
Command line parameters: -e 1 -g GTTCTTGACCCCC --minimum-length 20 --discard -o out_1.fastq -p out_2.fastq in_1.fastq in_2
Trimming 1 adapter with at most 100.0% errors in paired-end legacy mode ...
Traceback (most recent call last):
  File "~/.local/bin/cutadapt", line 10, in <module>
    cutadapt.main()
  File "~/.local/lib/python2.7/site-packages/cutadapt/scripts/cutadapt.py", line 823, in main
    stats = process_paired_reads(reader, modifiers, modifiers2, writers)
  File "~/.local/lib/python2.7/site-packages/cutadapt/scripts/cutadapt.py", line 274, in process_paired_reads
    read1 = modifier(read1)
  File "~/.local/lib/python2.7/site-packages/cutadapt/scripts/cutadapt.py", line 197, in __call__
    assert match.length - match.errors > 0
AssertionError
- - - - - - - - - - - - - 

I would like you to tell me the solution...
Thank you for your help.

**Comment by marcelm** [comment]
Hi, and sorry for the late reply, I was not in the office for a while. The problem is probably the `-e 1` option you are using: The value must be an *error rate*. If you want to allow 10% errors, use `-e 0.1`, for example, or `-e 0.05` for 5% errors. Using `-e 1` actually means that 100% errors are allowed and this leads to a crash in some part of the program.

It seems that you want to allow one error in the adapter matches. In order to do that, just omit the `-e 1` option and cutadapt will use the default value of 10%. With your adapter having a length of 13 bases, this results in 1.3 errors being allowed, which is rounded down to 1 and therefore exactly what you want.

**Comment by marcelm** [comment]
This has been fixed: Setting the allowed error rate to 100% via `-e 1` may not make much sense, but at least cutadapt will not crash anymore.
