### ISSUE TITLE
cutadapt 

### ISSUE THREAD

**Issue by fl86** [marcelm/cutadapt#158]
When using cutadapt to trim my data I also select on minimum length. However I noticed that although this length selection is executed in the first file, it does not seem to be applied in the second file. The latter still contains reads with length inferior to 50. Yet from what I gathered this option ought to work on paired-end data or did I misunderstood?

This is my code
cutadapt -q 20 -m 50 -o ML_59R1.fastq -p ML_59R2.fastq 59_R1.fastq 59_R2.fastq 

Am I doing something wrong?

**Comment by marcelm** [comment]
In older versions of cutadapt, the filtering options such as `-m` would only work on the first read. This is not the case anymore and they do work for both reads, but for backwards compatibility, cutadapt switches to a 'legacy' mode when it looks as if you were trying to use the program in the old way. Any of the uppercase adapter-specifying options (`-A`/`-B`/`-G` and also `-U) enable the new behavior. Since you haven’t specified any of those options, you get the old behavior. The workaround is to specify a dummy adapter such as `-A XXX` (the `X` does not match anything so no adapters will be removed). Hope that helps!
