### ISSUE TITLE
Documentation on using as a python module

### ISSUE THREAD

**Issue by astewart-twist** [marcelm/cutadapt#161]
Awesome tool!   Would be interested in seeing whether its simple enough to use as a module inside a python script rather than as a command line tool.  Thoughts?

**Comment by marcelm** [comment]
I’ve been working a bit on making this possible, but there’s not much documentation, yet. Could you briefly describe your use case?

**Comment by astewart-twist** [comment]
Sure.  Mostly just iterating through fastq files and trimming out adaptors.  Right now Im just calling cutadapt as a script via subprocess, which is fine, but ideally I would just import the module and makes calls to whatever the entrypoint functions are.  I can figure it out myself by going through the code, but was just wondering if you or anyone has been already doing this and had good examples / documentation.

**Comment by marcelm** [comment]
Someone pasted some code [in issue 148](https://github.com/marcelm/cutadapt/issues/148#issuecomment-163305916), maybe that’s a starting point. The tests may also be helpful. Note I’m not (yet) making any guarantees regarding the stability of the Python API.

**Comment by astewart-twist** [comment]
Ah!  Very useful examples.  Thanks for sharing.

**Comment by marcelm** [comment]
Hi, this issue about using Cutadapt as an API from Python scripts is still open and as I’m cleaning up the issue list, I’ve decided to close it now. Perhaps this isn’t relevant to you anymore, but let me explain, also for others.

I still think it would be a great to be able to do `import cutadapt` and run a totally custom pipeline, and I have over the last years taken this into account when I refactored the code. However, making a stable API available, at least for Cutadapt itself, will take too much effort. Given the time available to me for working on the program, it is just unrealistic that this is going to happen.

Cutadapt already has a very stable API &mdash; the command-line interface, so even though spawning a `subprocess` isn’t as nice, it works just fine. Also, keeping the command-line stable requires quite a few compromises, and I don’t want to have to think about another layer of constraints when refactoring and adding new features.

That said, I *have* moved some parts of Cutadapt into libraries since this issue was opened, in particular [xopen](https://pypi.org/project/xopen/) and recently [dnaio](https://pypi.org/project/dnaio/). So for some parts of Cutadapt, the stable Python-level API does exist.
