### ISSUE TITLE
Remove the fixed number of bases after the adapter trimming

### ISSUE THREAD

**Issue by shengqh** [marcelm/cutadapt#172]
Currently we are using NEXTflex kit in our sequencing project. The NEXTflex kit will add 4 random bases between actual read and the adapters. Ideally, we need to remove the 3' adapter first, followed by removing additional 4 bases from both sides of the read and finally keep the reads longer than 20 bases. Currently, cutadapt will remove the 4 bases from both sides followed by removing the adapter which is opposite to our requirement. Is it possible to add a flag to indicate the order of those two tasks? Thanks a lot.

**Comment by marcelm** [comment]
You have two options to do what you want, even without any special options. First, you can run cutadapt a second time: Remove the adapter in the first round, then remove the four bases from each read in the second round. If you have single-end reads, you can even pipe the output of the first into the second, somewhat like this:
```
cutadapt -a ADAPTER input.fastq | cutadapt -u 4 -u -4 - > output.fastq
```
The second option uses the trick of adding four `N` bases to the beginning of the adapter:
```
cutadapt -u 4 -a NNNNADAPTER -o output.fastq input.fastq
```
Do you think this works for you? I’d like to avoid adding further options to cutadapt since there are already so many.

**Comment by marcelm** [comment]
No reply, closing.

**Comment by y9c** [comment]
Hi @marcelm, 

I use the first solution to cut bases after adapter trimming, but this will generate two report (log) for cutadapt. I would like to know is it possible to adjust the priority of each trimming step? 
For example. I think it is more reasonable to run quality trimming (`-q`), after adapter trimming (`-a`).

Thanks!

**Comment by marcelm** [comment]
At the moment, it is not possible to change the order in which these steps are done, but it sounds like a reasonable feature request. Can you please open a new issue? (Since this one is closed.)
