### ISSUE TITLE
Error when length of quality sequence and length of read do not match

### ISSUE THREAD

**Issue by jose-raul-barreras** [marcelm/cutadapt#178]
Hi!
When you have some file with different length of quality sequence and length of read, cutadapt fails.
I attach the error log. I tested with last version and I got the same results.

```
Traceback (most recent call last):
  File "/util/opt/anaconda/2.2/envs/cutadapt-1.4.2/bin/cutadapt", line 10, in <module>
    cutadapt.main()
  File "/util/opt/anaconda/2.2.0/envs/cutadapt-1.4.2/lib/python2.7/site-packages/cutadapt/scripts/cutadapt.py", line 806, in main
    (n, total_bp) = process_reads(reader, pe_reader, adapter_matcher, quality_trimmer, modifiers, readfilter, trimmed_outfile, untrimmed_outfile, pe_outfile, rest_writer)
  File "/util/opt/anaconda/2.2.0/envs/cutadapt-1.4.2/lib/python2.7/site-packages/cutadapt/scripts/cutadapt.py", line 485, in process_reads
    for read in reader:
  File "_seqio.pyx", line 146, in __iter__ (cutadapt/_seqio.c:3520)
  File "_seqio.pyx", line 54, in cutadapt._seqio.Sequence.__init__ (cutadapt/_seqio.c:1679)
ValueError: In read named 'SOME_NAME': length of quality sequence and length of read do not match (52!=150)


Cutadapt terminated with exit signal: '256'.
Terminating Trim Galore run, please check error message(s) to get an idea what went wrong...
```

Best regards!

**Comment by marcelm** [comment]
Your FASTQ file is invalid, so exiting with an error message is the only viable option for cutadapt. Or did I misunderstand?

**Comment by jose-raul-barreras** [comment]
Yes. The file is invalid, but I think could be better skip the read with the problem, report it as a warning and continue.

**Comment by marcelm** [comment]
Possibly, but such a message will easily get lost and then people would continue with broken files without knowing it.

I think it’s much better to fail early and loudly if there is anything wrong with input data because it often points to some other underlying problem. The message above, for example, occurs often when the FASTQ file is incomplete (full disk etc.). Re-running the program that generated/copied the FASTQ file would be the correct thing to do. And if you know what you are doing, you can manually fix the broken record in the file to get rid of the error.
