### ISSUE TITLE
cutadapt 1.9.1 error

### ISSUE THREAD

**Issue by Vishweshwaran** [marcelm/cutadapt#179]
Hi,
   When i try to use cutadapt without installation I get the following error.

[USER@user cutadapt-1.9.1]$ python2.6 ./bin/cutadapt --help

ERROR: A required extension module could not be imported because it is
incompatible with your system. A quick fix is to recompile the extension
modules with the following command:

    /usr/bin/python2.6 setup.py build_ext -i

See the documentation for alternative ways of installing the program.

The original error message follows.

Traceback (most recent call last):
  File "./bin/cutadapt", line 9, in <module>
    from cutadapt.scripts import cutadapt
  File "/user/cutadapt-1.9.1/cutadapt/scripts/cutadapt.py", line 62, in <module>
    check_importability()
  File "/user/cutadapt-1.9.1/cutadapt/__init__.py", line 9, in check_importability
    import cutadapt._align
ImportError: /user/cutadapt-1.9.1/cutadapt/_align.so: undefined symbol: PyFPE_jbuf

I get the same error even after running

[user@user cutadapt-1.9.1]$ python setup.py build_ext -i

After running the above command as mentioned in the manual I get

[user@user cutadapt-1.9.1]$ python setup.py build_ext -i
running build_ext

The python version is 2.6...

Can some one tell me whats going wrong..

Thanks..

Regards
Vishwesh

**Comment by marcelm** [comment]
Try to use the `pip install` method that is [described in the documentation](http://cutadapt.readthedocs.org/en/stable/installation.html). You do not need admin rights for that. Let me know if that works!

**Comment by Vishweshwaran** [comment]
I am not a sudo user or root user...

I tried running
 pip install cutadapt
But I get the following error.
-bash: pip: command not found

Regards
Vishwesh

**Comment by marcelm** [comment]
Sorry for the delay in replying. Do you have *only* Python 2.6? If you have 2.7, then you should use that. Unpack the .tar.gz file again (to make sure the directory is clean) and run the command from your first message, but using 2.7: `python2.7 ./bin/cutadapt --help`.

Also, make sure that you use the same `python` command consistently. If you use `python2.6` to run cutadapt, then you should also use `python2.6` when running the `setup.py` script, as in `python2.6 setup.py build_ext -i`.

Instead of pip, you could try `easy_install`:
```
easy_install --user cutadapt
```
Then run cutadapt with the command `~/.local/bin/cutadapt`.

I’m happy to help further, just tell me what you tried.
