### ISSUE TITLE
Problem with parsing command line arguments on Windows

### ISSUE THREAD

**Issue by emmaggie** [marcelm/cutadapt#193]
OS: Windows 7, Windows Server 2012 R2. Version cutadapt 1.9.1 (1.8.3 works perfectly). When called with command line arguments (e.g -a ADAPTERSEQUENCE) throws an error:     
`Traceback (most recent call last):      
  File "cutadapt.py", line 855, in <module>     
    main()     
  File "cutadapt.py", line 615, in main     
    too_short_outfile, paired=='both')     
TypeError: __init__() takes exactly 2 arguments (4 given)`          
It is not a general problem with command line argument parsing (sys.argv[1:] gives expected list of arguments). It's something downstream. Ideas?

**Comment by marcelm** [comment]
Hi, are you sure you are using version 1.9.1? The error message says that there’s a problem in line 855, but the file has only 700 lines in that version. Can you make sure with `cutadapt --version`? If you still get 1.9.1, then it is a problem with your installation because then I would assume that it is a mixture of an old and a new version.

**Comment by emmaggie** [comment]
You are right. One of the scripts (cutadapt.py) was from 1.8.3 and the rest was from 1.9.1. Please close the issue. Thank you for a quick response!

**Comment by marcelm** [comment]
I’m glad it was that easy!
