### ISSUE TITLE
Cutadapt incorrectly recognizes reads as improperly paired

### ISSUE THREAD

**Issue by snaqvi1990** [marcelm/cutadapt#197]
Hi, I am trying to run cutadapt in paired end mode to trim Illumina adapters. This is my command:
cutadapt -a AGATCGGAAGAGC -A AGATCGGAAGAGC -o s_1_1_sequence.trimmed.txt.gz -p s_1_2_sequence.trimmed.txt.gz  s_1_1_sequence.txt.gz s_1_2_sequence.txt.gz

The first header of s_1_1_sequence.txt.gz is:
@WIGTC-HISEQ2:1:1212:4718:2051#CGATGT/1;1

and for s_1_2_sequence.txt.gz:
@WIGTC-HISEQ2:1:1212:4718:2051#CGATGT/2;1

However cutadapt gives the following error:
Error: Reads are improperly paired. Read name 'WIGTC-HISEQ2:1:1212:4718:2051#CGATGT/1;1' in file 1 not equal to 'WIGTC-HISEQ2:1:1212:4718:2051#CGATGT/2;1' in file 2.

As far as I can tell, the read headers are in fact properly paired, and end with /1 and /2 as indicated in the docs. So I don't know why cutadapt thinks that the paired read names don't match up; perhaps it is because of the semicolon?

Thanks,
Sahin Naqvi

**Comment by marcelm** [comment]
Hi, thanks for trying cutadapt. The semicolons are a part of the problem, yes. The two characters `;1` are part of the read name, so your read names actually do not end with `/1` or `/2`. Cutadapt ignores the `/1` and `/2` only if it finds them at the very end of the read name. It seems to me that some other software has modified the read names since the standard names produced by the Illumina pipeline (it seems to be an older version from a few years back) do not include the `;1`. I think the best option would be to remove the `;1` from the read names. You can also replace the semicolon with a space since cutadapt also ignores everything starting from the first whitespace character.

I can also show you how to remove the check for properly paired reads from the source code, but it may very well be that then the next tool that you use after trimming adapters complains about improper read names.

**Comment by phancanhtrinh** [comment]
I am running cutadapt and I have a similar problem. Please give me some suggestion; thank you very much!

cutadapt --interleaved -q 20 -a AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT -A GATCGGAAGAGCACACGTCTGAACTCCAGTCACGGATGACTATCTCGTATGCCGTCTTCTGCTTG -o trimmed.1.fastq S4_48_1_R1.fq.gz

--> error:

This is cutadapt 2.8 with Python 3.8.10
Command line parameters: --interleaved -q 20 -a AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT -A GATCGGAAGAGCACACGTCTGAACTCCAGTCACGGATGACTATCTCGTATGCCGTCTTCTGCTTG -o trimmed.1.fastq S4_48_1_R1.fq.gz
Processing reads on 1 core in paired-end mode ...
cutadapt: error: Error in sequence file at unknown line: Reads are improperly paired. Name 'A00709:496:HCGV2DSX5:3:1101:5104:1063 1:N:0:ATAGCTGG+GCTGATAG' (first) does not match 'A00709:496:HCGV2DSX5:3:1101:6352:1063 1:N:0:ATAGCTGG+GCTGATAG' (second).

**Comment by marcelm** [comment]
Hi, are you sure you want the `--interleaved` option? In your case, I would guess that the input is not actually interleaved. Since your file name is `S4_48_1_R1.fq.gz`, I would assume that there is also a second file named `S4_48_1_R2.fq.gz`. If that is so, you need to provide that as second input file and you probably also want non-interleaved output, which means you need to provide a second output file name, like so:
```
cutadapt -q 20 \
-a AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT \
-A GATCGGAAGAGCACACGTCTGAACTCCAGTCACGGATGACTATCTCGTATGCCGTCTTCTGCTTG \
-o trimmed.1.fastq .gz \
-p trimmed.2.fastq.gz \
S4_48_1_R1.fq.gz \
S4_48_1_R2.fq.gz
```

**Comment by phancanhtrinh** [comment]
Thank you very much, Marcel; I got your idea. It works now.

**Comment by marcelm** [comment]
Great, thanks for letting me know.

**Comment by marcelm** [comment]
Hi, it is very likely that the error message is correct and that there’s an issue in the input files.

Note that Cutadapt doesn’t care about the names of the input files, so no renaming is necessary. Also, proper pairing is not about the primers, but is more about the file format.

Typically, paired-end reads are provided in two files, the R1 and the R2 files, and the expectation is that the *n*th read in the R1 file has the *n*th read in the R2 file as its partner. By convention, the two reads in a pair have identical identifiers. So paired-end reads are only considered to be properly paired when the read IDs of the two reads in each pair match. In your case, a read pair was encountered where R1 has ID 'M04398:31:000000000-KTKCM:1:1101:16827:17490', whereas R2 has ID 'M04398:31:000000000-KTKCM:1:1101:16992:26157', which are not the same. (The `1:N:0:TAGGCATG+TATCCTCT` part (after the space character) is considered to be a comment and is ignored when doing the comparison.) See also https://cutadapt.readthedocs.io/en/stable/reference.html#properly-paired-reads.

I would guess that your reads are out of sync, that is, the *n*th read in the R1 file no longer corresponds to the *n*th read in the R2 file. This can happen, for example, when you process your original data with a tool that does some filtering (that is, it removes reads) and when you use that tool separately on file R1 and R2. During this filtering, some reads got removed from the R1 file and some from the R2 file so that the correspondence between them is lost.

**Comment by PGR23** [comment]
Thank you for your detailed quick reply. I had to demultiplex myself, so that is probably where the uneven filtering occurred. I'll edit my code accordingly and hopefully things will run smoothly. Thank You!

**Comment by eysung** [comment]
Hi, I'm having a similar problem. 
I know the files match, and I've verified that the correct primers are found in forward and reverse, respectively. This wasn't the case when I ran it on other data before, but only on this data and a few others do I get the same error message. Any suggestions on how to resolve this would be appreciated!

**Version:** cutadapt 2.8
**command:** cutadapt -g GTGYCAGCMGCCGCGGTAA -G GGACTACNVGGGTWTCTAAT -o s_Human_Gut_PRJNA747117/1_primer_remove/dna/Amplicon/E/22Hdna_fw.fastq.gz -p s_Human_Gut_PRJNA747117/1_primer_remove/dna/Amplicon/E/22Hdna_rv. fastq.gz s_Human_Gut_PRJNA747117/data/dna/Amplicon/E/22Hdna_S22_L022_R1_001.fastq.gz s_Human_Gut_PRJNA747117/data/dna/Amplicon/E/21Hdna_S21_L021_R2_001.fastq.gz
**Error:** cutadapt: error: Error in sequence file at unknown line: Reads are improperly paired. Read name 'SRR17380173.1 1 length=301' in file 1 does not match 'SRR17380172.1 1 length=301' in file 2.

Thanks for your help. EY

Translated with DeepL.com (free version)

**Comment by marcelm** [comment]
Hi, there is a problem with the input FASTQ files. Where do these files come from? Judging from the read names, they have been downloaded from SRA. Possibly `fastq-dump` with the `--split-files` option was used. Here is an excerpt from `fastq-dump --help`:
```
     --split-files                 Write reads into separate files. Read
                                     number will be suffixed to the file
                                     name. NOTE! The `--split-3` option is
                                     recommended. In cases where not all
                                     spots have the same number of reads,
                                     this option will produce files that WILL
                                     CAUSE ERRORS in most programs which
                                     process split pair fastq files.
```
Note the last sentence. I recommend to re-download the files but use the `--split-3` option instead.

**Comment by akabetso** [comment]
thank you @marcelm your solution was what i needed!
