### ISSUE TITLE
Illumina TruSeq Adapter Prefix BLASTs to human genome

### ISSUE THREAD

**Issue by JeremyBAdams** [marcelm/cutadapt#201]
The common prefix you list for the Illumina TruSeq Adapter (AGATCGGAAGAGC) has BLASTN hits when searched against the human genome. Can you comment on if there will be sequence loss at these genomic positions when the adapter prefix is run through CutAdapt? Does it make sense to use the full TruSeq Adapter sequence in certain instances?

I retrieved the Illumina TruSeq Adapter common prefix sequence from the following link (http://cutadapt.readthedocs.io/en/stable/guide.html#illumina-truseq).

Thank you

**Comment by marcelm** [comment]
Yes, there would be false positive adapter matches within reads that cover these loci, and these reads will be trimmed although they shouldn’t. Just use the full adapter sequences - the only downside is that your command-line is a bit longer and that it is slightly slower.

Note that there are only 4**13=67 million different 13-character strings. Since the human genome contains 6 billion (counting forward and reverse) overlapping 13-character strings, you would expect to see around 90 occurrences of *any* 13-character string just by chance (assuming a very simple model).

What type of data do you have? If it is from whole-genome sequencing and you use BWA-MEM, I’d not trim adapters anyway since insert size should be large enough so one would see adapters only rarely and then BWA-MEM’s soft-clipping of ends that do not match takes care of the remaining few adapter occurrences. If it’s something else, then I would probably not worry about the sequence loss since most of the BLASTN matches you found would not be on genes anyway.

In case I could help you, please don’t close the issue, yet. I’d like to keep it open until I have time to add a sentence about this to the documentation.
