### ISSUE TITLE
If cutadapt find two matches of an adapter with same quality, which one should it choose?

### ISSUE THREAD

**Issue by bli25ucb** [marcelm/cutadapt#205]
Hi @marcelm , if cutadapt find two matches of an adapter with same quality, one in the middle, and another close to the 3' end, which one will cutadapt choose? Suppose we use '-a' option. 

Thanks!
Bo

**Comment by marcelm** [comment]
Cutadapt does not use the quality, but of course your question is still valid. The answel is that, if there are two matches that are both within the allowed error rate, it chooses the "leftmost" one (the one that is closest to the 5' end).

Note that this applies even if the two matches have different numbers of errors. If the leftmost match has more errors than one further right, the leftmost one is still the one that is chosen as long as the number of errors is within the bounds given by the maximum error rate (given with the `-e` option, by default 10%). 

My opinion is that this behavior is the one that makes sense since there can be adapter dimers and one typically wants to remove both adapters, so the leftmost one should be chosen. And if there is a sequencing error in the leftmost adapter occurrence, it should still be chosen, even if there is no sequencing error in the other occurrence.

**Comment by bli25ucb** [comment]
@marcelm, thanks a lot for your quick reply! Yeah, for quality, I actually mean number of mismatches.

**Comment by bli25ucb** [comment]
Hi @marcelm, so what if we have multiple adapters, which one does cutadapt choose? I have noticed when I have both 5' adapters (-g) and 3' adapters (-a), it is the 3' adapter trimmed.

**Comment by marcelm** [comment]
This is covered [in the section about removing multiple adapters](http://cutadapt.readthedocs.io/en/stable/guide.html#multiple-adapters) in the documentation. The [subsection about trimming more than one adapter](http://cutadapt.readthedocs.io/en/stable/guide.html#trimming-more-than-one-adapter-from-each-read) may also be relevant to you. I have updated it a bit just now to include a description of so-called "linked adapters", which could be useful in your case.

**Comment by bli25ucb** [comment]
@marcelm Thanks a lot. I should read your documentation more carefully
