### ISSUE TITLE
paired end mode is not cutting read 2

### ISSUE THREAD

**Issue by RCWilliams** [marcelm/cutadapt#206]
I'm running cut adapt on paired end reads, but I cannot get -u to apply to read 2. I've played around with the placement of the commands in relation to the adapters, but I can't figure it out. Can anybody offer any help?
I've included all possible adapter sequences because I don't know which are actually present, might this be causing a problem?
Thank you in advance for any help and apologies if it's obvious!

cutadapt -u 5 -q 20,20 -y 'found {name}' --minimum-length 50 --pair-filter=both \
--too-short-output {path to file} \
--too-short-paired-output {path to file} \
-a adapter1=GATCGGAAGAGCACACGTCTGAACTCCAGTCAC -A adapter1b=GATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT \
-a adapter2=AGATCGGAAGAGCACACGTCTGAACTCCAGTCACACAGTGATCTCGTATG -a adapter3=GATCGGAAGAGCACACGTCTGAACTCCAGTCACACAGTGATCTCGTATGC \
-A adapter7=AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCC -A adapter8=GATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCG \
-b adapter4=CTGTCTCTTATACACATCT -b adapter5=AGATGTGTATAAGAGACAG -b adapter6=CTGTCTCTTATACACATCTAGATGTGTATAAGAGACAG \
-o {R1_trimmed} -p {R2_trimmed} {R1} {R2}

**Comment by marcelm** [comment]
Thanks for the example. You just need to provide `-U 5` in addition to `-u 5` in order to also trim the second read. The lowercase trimming options `-a`/`-b`/`-u` etc. apply only to the first read. The uppercase options `-A`,`-B`,`-U` etc. apply to the second read. (The only exception is `-q`, which applies to both reads.)

The order of the options does not matter at all. The only parameters that need to be in the correct order are the two input read files (`{R1}` and `{R2}` in your example).

Including too many adapter sequences is also not a problem, but you should consider [following these instructions in  the documentation](http://cutadapt.readthedocs.io/en/stable/guide.html#illumina-truseq) because it appears you are trimming Illumina adapters and what is shown there is often correct. If it doesn’t work, you can still try  the above, but note that the adapter1 you are given is actually one base too short in the 5' end. Yes, Illumina says they are using that sequence, but there is a step in which an extra nucleotide gets ligated between the DNA fragment and the adapter.

**Comment by RCWilliams** [comment]
Thank you so much for such a fast and helpful reply, I really appreciate it! it worked!
Thank you also for the advice on the Illumina adapters, I’ll play around with this.

**Comment by marcelm** [comment]
You are welcome! Closing the issue then. Feel free to re-open if you have further questions or problems.

**Comment by rspreafico-vir** [comment]
Related to this thread, there is one point not clear to me from the documentation. If one wants only to quality- (but not adapter-) trim using `-q` on both reads of PE sequencing, would that work? On the one hand, I understand that `-q` works on both reads. On the other hand, I understand that not specifying any adapter for read 2 with the capital-letter flags activates legacy mode, which spares read 2. This latter is actually what I am seeing, with read 1 getting quality trimmed but read 2 that doesn't. So how to force cutadapt to quality trim both reads even when adapters are not trimmed? Apologies in advance if I missed this point from the documentation.

**Comment by marcelm** [comment]
You can disable legacy mode by adding `--pair-filter=any` to your command line. Legacy mode exists for compatibility with older Cutadapt versions, but this option exists only in newer Cutadapt versions, so if you use it, legacy mode is not necessary and will be disabled. This is actually true for many other options: Using any of `-A`, `-G`, `-B`, `-U`, `--length` and some others disables legacy mode. Previously, I recommended to provide a dummy R2 adapter, as in `-A XXX`, but then this slows down processing a bit and you get the extra statistics for it.

Having said that, I will add that the next release of Cutadapt will no longer have the legacy mode because it leads to suprising behaviour, as your question shows.

**Comment by rspreafico-vir** [comment]
Thanks for the quick response!
