### ISSUE TITLE
triming poly A for paired-end sequencing data

### ISSUE THREAD

**Issue by lhcumt** [marcelm/cutadapt#207]
Thanks for provide such a good tools for processing sequencing data.

I have a question about trimming poly A for paired-end sequencing data.
I found the instruction, in the user guide, for doing this:
cutadapt -a ADAPTER_FWD -A ADAPTER_REV -o out.1.fastq -p out.2.fastq reads.1.fastq reads.2.fastq

For positive strands reads, ploy A and downstream BP should be trimmed, while for negative strands reads, ploy T and upstream BP should be trimmed, right?

So for trimming poly A for paired-end sequencing data, which one out of following 4 should I use:
cutadapt -a "A{100}" -A "T{100}" -o out.1.fastq -p out.2.fastq reads.1.fastq reads.2.fastq
cutadapt -a "A{100}" -G "T{100}" -o out.1.fastq -p out.2.fastq reads.1.fastq reads.2.fastq

Thank you very much and look forward your reply

**Comment by marcelm** [comment]
Hi, I have to admit I’m not sure about the answer because I don’t have that much experience with RNAseq.

I think there are two cases.

Case 1:
```
R1--------->

----------AAAAAAAAAA
----------TTTTTTTTTT

        <---------R2
```
Here, the following needs to be taken care of:

- Read 1 runs into the poly-A tail
- Read 2 starts within a poly-T head

The cutadapt options for this would be  (`-a A{100}` and `-G T{100}`).

Then the second case is the reverse complement of the first:
```
R2--------->

----------AAAAAAAAAA
----------TTTTTTTTTT

        <---------R1
```
This could happen here:
- Read 2 runs into the poly-A tail
- Read 1 starts within a poly-T head

The cutadapt options for this would be  (`-A A{100}` and `-g T{100}`).

And if my thinking is correct, then this could work:
```
cutadapt -a "A{100}" -A "A{100}" -g "T{100}" -G "T{100}" -o ... -p ... ... ...
```
You should definitely double-check this!

**Comment by mebbert** [comment]
@marcelm, not sure if I should create a separate issue for this, but it would be great to add a feature to remove polyA and polyT tails at the same time it's removing adapters. Some sort of flag `--remove-polya`. That way we could avoid running cutadapt twice! Or maybe there is currently a way?

Really appreciate your help!

**Comment by marcelm** [comment]
Could you provide some test data? A few reads that show the possible configurations are fine, or perhaps an SRA accession with the correct adapter sequence?

**Comment by marcelm** [comment]
@mebbert You should be able to use `-n 2` and just provide both the poly-A/T tails and the adapter sequences. This will remove up to two adapter sequences from each read.

**Comment by marcelm** [comment]
Please re-open to discuss this more.
