### ISSUE TITLE
Multiple adaptor

### ISSUE THREAD

**Issue by ptranvan** [marcelm/cutadapt#212]
Hi,

In case where my adapter is found at a multiple location:

`XXADAPTXXADAPTMYSEQ`

Is it possible to trim everything so at the end I got `MYSEQ` ? (without running twice cutadapt)

**Comment by marcelm** [comment]
Hi, you edited your question. I guess you found out that [you probably need to use a non-anchored 5' adapter with the `-g` option](http://cutadapt.readthedocs.io/en/stable/guide.html#five-prime-adapters).

How many bases are there between the two adapters? If it is a fixed number of bases, then you can just use `-g adaptNNadapt` (the `N` are IUPAC wildcard characters that match any base).

If the distance is variable, then it would be nice to have an option telling cutadapt that it should pick the rightmost match of the adapters. By default, it picks the leftmost one. That option currently does not exist, however, so here is a workaround: Instead of running cutadapt twice, give it the option `-n 2` (short for `--times=2`), which instructs cutadapt to attempt to remove an adapter from each twice. In your example, it would remove the leftmost one first and then in the second round the rightmost one.

**Comment by ptranvan** [comment]
Thanks for your help.
