### ISSUE TITLE
how to automate trimming paired-end reads

### ISSUE THREAD

**Issue by m-ocejo** [marcelm/cutadapt#217]
Hi!
First of all, thank you very much for such a useful tool!!
My coding skill is very low and I was wondering if there is anyway to automate multiple samples (80 paired-end reads in my case) in the "Trimming paired-end reads" step. 

Best!

**Comment by marcelm** [comment]
Hi, great to hear you are satisfied with the tool. The question of how to automate cutadapt for many samples is one that you should probably ask your local Unix command-line expert. It’s easiest to solve these things while sitting down with someone.

Here is one very short example in order to get you started. I assume you have your paired-end reads in a directory named `untrimmed/`, and that the two files for a single sample are named something like `Sample1_R1_001.fastq.gz`, `Sample1_R2_001.fastq.gz` etc. Create a directory `trimmed` and then you could trim all the files like this:
```
# iterate over all the Read 1 files
for r1 in untrimmed/*_R1_*.fastq.gz; do
    # replace _R1_ in the file name with _R2_
    r2=${r1/_R1_/_R2_}
    out1=trimmed/$(basename ${r1})
    out2=trimmed/${out1/_R1_/_R2_}
    cutadapt -a ... -A ... -o ${out1} -p ${out2} ${r1} ${r2}
done
```
Of course you’ll have to adjust this to suit your needs (and I haven’t even tested it), but it shows some basic principles that you can use, in particular of how to iterate over the files and how to get the name for read 2 when you have the name for read 1.

**Comment by m-ocejo** [comment]
OK! I´ll try to adjust it to my data.
Many thanks for your time giving the example!
