### ISSUE TITLE
Bug in length filtering - cutadapt removes longer reads than required

### ISSUE THREAD

**Issue by neuhofmo** [marcelm/cutadapt#227]
Hi,
I use cutadapt for quite a while and I love it - but this is the first time I encounter something that seems like a bug (possibly a serious one):

For some reason cutadapt removed most of my reads for being too short. I used the `-m 13` flag, for paired-end reads 150bp long, and many of them were removed for being too short, regardless of the read length. 
I used --too-short-output and --too-short-paired-output, and apparently some of the reads written to these output files were longer than 13bp. The average (unique) read length written to these files was actually 65bp, which is well over 13bp!

Might there be some other reasons for discarding the reads except for length? If so, they are not reported in the log so I don't know why my reads were discarded (perhaps quality?).

Attached is the first lines of the log file:
[cutadapt_log_for_bug_report.txt](https://github.com/marcelm/cutadapt/files/731906/cutadapt_log_for_bug_report.txt)

Thanks a lot,
Moran

**Comment by marcelm** [comment]
Hi and thanks for the report. I hope that this is not a bug. It is normal that you see reads that are longer than the threshold among the discarded reads. The reason is that cutadapt checks the length of both members of the pair: Even if only of them is too short, the entire pair is considered to be too short.

That is, if you have a read pair that has lengths 50 bp and 10 bp after trimming, it would be discarded when you use `-m 13`, and therefore you’d see that pair in the `--too-short-...` output.

I hope this is the case in your data. You could test it on the read pairs that were output by the `--too-short-..` options by checking the length of both forward and reverse read at the same time: It should always be the case that at least one of them is shorter than 13 bp.

Note that you can actually change this behavior with the `--pair-filter` option. The default is `--pair-filter=any` with the behavior I just described. If you change it to `--pair-filter=both`, then both reads would have to be shorter than the given minimum length in order for the pair to be considered to be too short.

> Might there be some other reasons for discarding the reads except for length?

Only the options that are listed under the "Filtering of processed reads:" heading in the `--help` output ever discard reads. From what I can see in your command-line, you only use the `-m` option, so no other filtering is going on.

This may of course not help you with your actual problem that most of your reads end up being too short ... If you still think you have found a bug, it would be best if you could select a single read pair that shows the problem and send it to me or attach it to the bug report.

**Comment by marcelm** [comment]
I assume this is resolved. Please re-open if not.
