### ISSUE TITLE
Does cutadapt remove reverse complements?

### ISSUE THREAD

**Issue by sagnikbanerjee15** [marcelm/cutadapt#228]
Hello,

I have used cutadapt to remove adapters. My library has sequences from both strands. Is the reverse complement of the adapter also removed? It is a single stranded library.

Thank you

**Comment by marcelm** [comment]
No, cutadapt searches and removes only the sequence as you provide it. The reverse-complement is not searched. This is because usually the two adapters used on both sides can be different from each other. If the adapters are the same ones in your case, you will need to reverse-complement the sequence yourself and provide it to cutadapt with a second `-a` option. Cutadapt will then remove the best-matching adapter from each read.

**Comment by sagnikbanerjee15** [comment]
All right Thank you very much

**Comment by marcelm** [comment]
You’re welcome.
