### ISSUE TITLE
Read shorted than adapter sequence

### ISSUE THREAD

**Issue by sagnikbanerjee15** [marcelm/cutadapt#230]
Hello,

I am using cutadapt to trim off 2 different adapters one in the 5' position and the other in the 3' position. How will cutadapt react when the read itself is a small portion of the adapter. For example, if the 5' adapter sequence is ABCDEFGHIJ and the read is ABCD. 

Thank you

**Comment by marcelm** [comment]
Hi and thanks for using cutadapt. I had to test this myself, but it turns out that cutadapt does not recognize an adapter in this case. You don’t say whether you are using a regular or an anchored 5' adapter (with a `^` in the beginning). For a regular (non-anchored) 5' adapter, bases in the beginning may be missing, but not at the end. Similarly, anchored 5' adapters are only recognized if they appear in full - also here, no bases at the end may be missing.

Changing this behavior is simple, but I am not sure yet whether I want to do it: Results may change for some people, which is something that I usually try to avoid.

If you are using anchored 5' adapters and you have access to your cutadapt installation, you could make this change yourself in the file `adapters.py`. Change this line (close to the top of the file):
```
PREFIX = align.STOP_WITHIN_SEQ2
```
to this:
```
PREFIX = align.STOP_WITHIN_SEQ1 | align.STOP_WITHIN_SEQ2
```
I can also describe the change necessary if you use a regular 5' adapter.

Why exactly is the read so short? Is it so short only after the 3' adapter has been removed?

**Comment by sagnikbanerjee15** [comment]
Thank you for the explanation. Actually I am attempting to perform de novo assembling with reads. Prior to sequencing each of the reads have a 5' and a 3' vector sequence attached (this is needed as a part of the experiment). The library is unstranded which means the reverse strand has the reverse complements of the vector sequences. After that the reads are randomly sheared and sequenced. Hence for each initial mRNA seq, there will be two reads which will have the 5' and the 3' vector.
 
Each of the vector sequences are about 120 bases long and the reads are about 150. So it is possible that the shearing was done in a way that vector was sheared in two parts and I have to remove both before I assemble. 

Thank you

**Comment by marcelm** [comment]
Hi, sorry for not getting back for so long; I wasn’t at work for a few weeks. With your explanation, it now makes sense that you get these kinds of artifacts.

I would probably be fine with changing the behavior for anchored 5' adapters (and anchored 3' adapters), but the impact for regular 5' adapters seems to be too large. Assume `ADAPTER` is the adapter, then in order to allow the truncated read with sequence `ADAPT` to match as a regular 5' adapter, I would need to change the parameters such that also reads like `SEQUENCEADAP` would match. Even if this probably makes sense to do, I’m worried about breaking backwards compatibility.

Let me know if you are still interested in a solution or whether you have found a workaround in the meantime.

**Comment by sagnikbanerjee15** [comment]
Thank you marcelm, I have found a workaround. Thanks

**Comment by marcelm** [comment]
Forgotten to close this.
