### ISSUE TITLE
GC bias adjustment for expected counts

### ISSUE THREAD

**Issue by hartemink** [marcelm/cutadapt#236]
when computing "expected" statistics, GC content of 50% is currently assumed.  cutadapt could add a parameter that allows a simple modification to this assumption which is problematic for organisms like yeast (GC content closer to 40%) and extremophile bacteria and archaea (GC content can be as high as 70%).  cutadapt could allow the user to specify (say) "--gc 40", and with that information, expected statistics could be computed accordingly (although they would now have to depend on the specific sequences of nucleotides in the adapters themselves).

**Comment by marcelm** [comment]
Thanks for the suggestion! I’ve now had some time to implement this. You can specify a GC content of 40% of your input reads with `--gc-content=40` (you can leave out the `=` sign and abbreviate options, so `--gc 40` would also work). Since this seems to be a feature that not many people need, this option is currently not listed when you type in `cutadapt --help` because the help is already quite long. This can be changed later.

Note that the percentage that you give is actually interpreted as the GC content of the *reads*. Since Illumina has GC bias, this may be different from the actual GC content of the genome.

Let me know whether it works for you.

**Comment by hartemink** [comment]
excellent!  thanks -- can't wait to give it a try...

peace,
alex


==

NOTE: i am using a queueing service for inbound email that delivers to my inbox only at specified times.  currently, email arrives at 6am and 4pm each day, plus at 11am on weekdays.  if you need a more timely response about something, please text or call instead.
