### ISSUE TITLE
Trimming both ends of paired-end reads

### ISSUE THREAD

**Issue by MartonSzoboszlay** [marcelm/cutadapt#237]
Hello,

thanks for developing cutadapt! It's a really useful tool. However, I've got a little lost in the user guide, would be grateful if you could point me in the right direction. Here is what I'd like to do:
I have paired-end amplicon reads of a locus that has considerable size heterogeneity. The sequencing went through the primers, so I need to trim them off, but due to the size heterogeneity some reads are long enough to reach into the primer + adapter at the opposite end but some are not. I'd like to trim off the forward primer from the beginning of the forward reads while discarding reads that did not contain the primer. Additionally, I'd like to trim off the complement of the reverse primer (and anything that follows it) from the end of the forward reads. This time, however, I do not want to discard the reads that did not contain the complement of the reverse primer. Similarly, I'd like to trim off the reverse primer from the beginning of the reverse reads and discard reads that did not contain the primer, and then trim off the the complement of the forward primer from the end of the reverse reads (not discarding reads that did not have it). Finally, if a forward read is discarded, I'd like to have its reverse read pair removed too and vice versa.
Is there a way to set up cutadapt to do this with one command?
Thanks!

Márton

**Comment by marcelm** [comment]
Thanks for very clearly describing what you want :-). This is one of the use cases I had in mind when adding "linked adapters". See also the docs although they describe only the use case of trimming reads that are not paired-end.

You need to use two linked adapters (one for read 1, one for read 2) and the `--discard-untrimmed` option:

    cutadapt -a FWDPRIMER...RCREVPRIMER -A REVPRIMER...RCFWDPRIMER --discard-untrimmed -o out.1.fastq.gz -p out.2.fastq.gz in.1.fastq.gz in.2.fastq.gz

FWDPRIMER is the forward primer, RCREVPRIMER is the reverse complement of the reverse primer, and similar for the other two.

In the linked adapters, the first one (the one before the `...`) is by default a 5' anchored adapter. It must occur, otherwise the other adapter is not even looked for and the read is considered to be "untrimmed". The second one (after the `...`) is a regular 3' adapter, which is optional. This is relevant with `--discard-untrimmed`: As long as the 5' adapter appears, the read is considered to be "trimmed" and is kept, just as you need it.

The same applies for the the linked adapter for read 2, for which you just use uppercase `-A` instead.

The only thing that remains is your last requirement: You want the entire pair to be discarded if one of the reads in the pair is considered to be "untrimmed". And this is actually the default behavior with `--discard-untrimmed` (and also the other filter options): If *any* of the two reads is considered to be untrimmed, the full pair is considered to be that as well, and therefore discarded. (See also the `--pair-filter` option, which one could use to change this.)

Please do not close the issue even if I could help. I would like to put this into the documentation later when I have time.

**Comment by MartonSzoboszlay** [comment]
This is awesome. Thanks for the detailed explanation!

**Comment by MartonSzoboszlay** [comment]
Hello,

I followed the template command, but noticed that 1 or 2 bases were trimmed off from the 3' end of the reads. Based on the user guide, I thought that by default, a minimum of 3 bases have to match the adapter sequence for trimming to occur. I tried including --overlap 3 in the command but it didn't change the outcome. Here is part of the report:

Overview of removed sequences at 3' end
length  count   expect  max.err error counts
0       10338   158815.0        0       7843 2483 12
1       101     39703.8 0       58 32 11
2       258     9925.9  0       143 75 40
3       230     2481.5  0       116 65 49
4       944     620.4   0       535 265 144
5       250     155.1   0       118 80 52
6       95      38.8    0       49 24 22

Frankly, this seems to contradict the "How to read the report" section of the user guide. How can there be error counts for length 0? How can 1 base trimmed off with 2 errors? According to this report, this happened with 11 reads. I'm afraid I'm misinterpreting this table. Could you explain how to read it correctly?
Best,

Márton

**Comment by marcelm** [comment]
I received another bug report by e-mail today also mentioning the 0 lengths in the report. This must be a bug and I will look into it. Tthe overlap thing may or may not be related.

**Comment by MartonSzoboszlay** [comment]
I've just noticed that if I add up all the count values in the above table I get the number that the report shows at the beginning as the total number of 3' trimmed reads. If I understand the table right, the first line, length 0, should mean no trimming, thus should not be counted.

**Comment by marcelm** [comment]
Ok, this is helpful! I think this points me to the right place in the code. I hope it’s not so urgent. Not sure I’ll have time over Easter.

**Comment by MartonSzoboszlay** [comment]
Do you think the trimming is done correctly and the bug only messes up the report, or is it possible that the 3' trimming is not correct (e.g. trimming off 1-2 bases for no reason)? If it's only the report, then I can continue working with my trimmed reads...

**Comment by douglasgscofield** [comment]
I submitted the other bug report via email.  In our tests, the trimming is done correctly at both ends, it is only the report that is in error.

**Comment by marcelm** [comment]
Oh no, I just found a [`TODO Statistics`](https://github.com/marcelm/cutadapt/blob/6b2366d526f33b386be3ce06f023f116ee0d66ea/cutadapt/adapters.py#L652) in the code, I guess I missed this before making the release ...

Yes, it should only be the statistics that are off. I’m quite sure that trimming itself works fine. But in case you actually see this in the reads, please let me know. (Best to open a new issue.)

Sorry about this. The reason this was not caught is that cutadapt still does not have automated testing for the statistics. It’s a relic from how the code is structured that makes this a bit difficult. One of the changes that I made in the last version was to actually make it easier to test the statistics - but unfortunately, it introduced the bug we are seeing here at the same time.

**Comment by marcelm** [comment]
I believe to have fixed the statistics problem.

I will also push a change in a minute that adds a new section to the documentation containing a slightly expanded version of my previous answer to @MartonSzoboszlay.

**Comment by marcelm** [comment]
The commit with the statistics problem fix is a57a09fda38e3.
The section in the docs is at https://cutadapt.readthedocs.io/en/latest/recipes.html#trimming-amplicon-primers-from-both-ends-of-paired-end-reads

**Comment by tolot27** [comment]
What about partially or completely overlapping paired reads? IMHO, the primer sequences should be trimmed from both sides of both reads. Hence, the linked adapters should be provided with parameters `-g` and `-G` as well. Am I correct?

I tried it with `-b/-B` as well but without success. Then I felt back to the non-linked version (without the `...`) for both `-a/-A` and `-g/-G` with success.

**Comment by marcelm** [comment]
Linked adapters should work in the same way I described in the comments above no matter whether the reads overlap or not. Don’t use `-b` - it’s almost never the right option to use (I even wonder whether I should remove it in the future). I cannot say why using linked adapters did not work for you. Feel free to  open a separate issue for this. Describe clearly what your data looks like and what you want the output to be.
