### ISSUE TITLE
Anchored 5' Adapters Error

### ISSUE THREAD

**Issue by adityabandla** [marcelm/cutadapt#238]
Hi,

I am trying to remove my primer sequences from both my reads, from the 5' end. I used to do this using the anchored option in v1.11

However, when I try to do the exact same thing using v1.13, it throws an error saying both reads cannot be anchored

My reads are paired-end Illumina ones

Best,
Adi

**Comment by marcelm** [comment]
You can please show the command-line that you are using?

**Comment by adityabandla** [comment]
Hi Marcel

The following is the code that I used 

cutadapt -g ^AAACTYAAAKGAATTGACGG -G ^ACGGGCGGTGTGTRC$ -m 100 --error-rate 0.1 --no-indels --times 1 --overlap 3

**Comment by marcelm** [comment]
The error message that you get is `Cannot anchor both ends at the same`. This occurs because you used both `^` and `$` on the second adapter sequence. So you are asking to anchor the adapter to the beginning of the sequence, but also to the end, which does not make that much sense, so it is forbidden.

The above did not work with cutadapt 1.11 either, but you would not get an error message. Cutadapt 1.13 checks the adapter sequences that you give more thoroughly.

I think what would happen in 1.11 is that cutadapt would look for the adapter sequence `ACGGGCGGTGTGTRC$`, so the `$` would actually be interpreted not as a marker for anchoring, but as a literal character to search for. Since this would not match in any of your reads, this would be counted as an error every time.

I have updated the error message to make it clearer. It now prints:
```
cutadapt: error: Trying to use both "^" and "$" in adapter specification '^ACGGGCGGTGTGTRC$'
```

**Comment by adityabandla** [comment]
Hi Marcel

My bad! I just figured this out and was typing it out, when I got your reply notification :)

Thanks for the clear explanation for not seeing this error in v1.11

Cheers,
Aditya

**Comment by marcelm** [comment]
Great you figured it out yourself - it’s still a good thing you reported it since the error message was not clear enough.
