### ISSUE TITLE
'5 primer not trimmed properly when 3' primer is provided as additional input

### ISSUE THREAD

**Issue by omeras** [marcelm/cutadapt#245]
Hey,
I'm trying to trim PCR amplicons. the read structure is as follows:
variable region (~6 bp) - F primer (17 bp, denoted FP) - area of interest (20 bp) - fixed region and R primer (90 bp, denoted RP).

when I use -a FP...RP I get ~200 trimmed reads.
-g FP -a RP yields ~1000 reads with trimmed FP.
-g FP results 66K reads trimmed.
anchoring RP does not solve the issue, as well as removing the first 5 bases (-u 5).

Do you have any idea why does it happen? Is there a risk in running cutadapt twice, once with -g FP an then -a RP?

Thanks,
Omer

**Comment by marcelm** [comment]
I think I can explain why you get those results:
> when I use -a FP...RP I get ~200 trimmed reads.

When you specify a linked adapter as `-a FP...RP`, the 5' part (FP) is automatically anchored. Since you have a variable region preceding FP, the primer is not found.

> -g FP -a RP yields ~1000 reads with trimmed FP.
> -g FP results 66K reads trimmed.

You did not say it, but I assume that you also get 66K reads with trimmed RP. Cutadapt by default assumes that each read contains only one adapter. If you give multiple adapters, it removes only the best-matching one from each read. The best-matching one is the one with the highest number of matches and because your RP is so long, that one is typically chosen.

You can run cutadapt twice, that is not a problem, but you can also use a non-anchored linked adapter instead. This was [introduced in the most recent cutadapt version 1.13](http://cutadapt.readthedocs.io/en/stable/changes.html#v1-13-2017-03-16). Just write `-g FP...RP` (note the `-g` instead of `-a`).

If for some reason you don’t have access to that version, you could also use `-g FP -a RP` as before, but add the option `-n 2`, which tells cutadapt that it should trim up to two adapters per read.

**Comment by omeras** [comment]
The -g option works great. Thanks!

**Comment by marcelm** [comment]
Sure! Closing this issue then. Feel free to re-open or file a new one if you have other questions.
