### ISSUE TITLE
Trimming paired end sample did not remove all adapters

### ISSUE THREAD

**Issue by siheming** [marcelm/cutadapt#253]
I am using cutadapt to remove adapters from paired end data from the SRA archive. Read1= SRR_NUMBER_1.fastq, Read2= SRR_NUMBER_2.fastq
The files contain a 3' adapter: "CTGTCTCTTATACACATCT" and a 5' adapter: "AGATGTGTATAAGAGACAG"
The options i am using to cut the adapters are:
`cutadapt -a "CTGTCTCTTATACACATCT" -g "AGATGTGTATAAGAGACAG" -A "CTGTCTCTTATACACATCT" -G "AGATGTGTATAAGAGACAG" -O 8 -o ${pathToResults}/${Read1} -p ${pathToResults}/${Read2} ${pathToSequences}/${Read1} ${pathToSequences}/${Read2}`

when i check for my adapters before trimming i can find a lot of them:
`-bash-4.1$ grep "CTGTCTCTTATACACATCT" fastq_all/SRR2973272_1.fastq | wc -l`
`331126`
`-bash-4.1$ grep "CTGTCTCTTATACACATCT" fastq_all/SRR2973272_2.fastq | wc -l`
`324764`
`-bash-4.1$ grep "AGATGTGTATAAGAGACAG" fastq_all/SRR2973272_1.fastq | wc -l`
`1192`
`-bash-4.1$ grep "AGATGTGTATAAGAGACAG" fastq_all/SRR2973272_2.fastq | wc -l`
`1027`

After the script run successfully most of the adapters are removed but some remain:
`-bash-4.1$ grep "CTGTCTCTTATACACATCT" fastq_trimmed_cutadapt/SRR2973272_1.fastq | wc -l`
`0`
`-bash-4.1$ grep "CTGTCTCTTATACACATCT" fastq_trimmed_cutadapt/SRR2973272_2.fastq | wc -l`
`0`
`-bash-4.1$ grep "AGATGTGTATAAGAGACAG" fastq_trimmed_cutadapt/SRR2973272_1.fastq | wc -l`
`21`
`-bash-4.1$ grep "AGATGTGTATAAGAGACAG" fastq_trimmed_cutadapt/SRR2973272_2.fastq | wc -l`
`19`

Is there anything I oversaw and why such a small amount of adapters does not get removed?

**Comment by marcelm** [comment]
This happens when you search for 5’ adapters (with `-g`/`-G`) and reads have multiple occurrences of the adapter sequence.

Currently, cutadapt’s search algorithm always finds the *leftmost* occurrence of an adapter. For 3' adapters, this makes sense, as the part to the right of the adapter is removed, which means that all further occurrences of the adapter sequence are removed as well.

For 5' adapters, however, finding the leftmost occurrence and removing everything to the left means that any additional occurrences remain in the read.

It possibly makes sense to change this behavior, but since that would be a (minor) backwards incompatible change (perhaps someone relies on the current behavior), I need to think about this a bit.

For now, you can add the option `-n 2` in order to make cutadapt search for adapters twice per read (this will be somewhat slower). This should take care of the remaining adapters - unless there are reads with three adapters or more in a row.

**Comment by siheming** [comment]
Thanks a lot for the reply. When I come back to run my script I will see how the `-n 2` option will change the output of my files.

**Comment by siheming** [comment]
It seems like the `-n 2` option takes care of the remaining adapters. So thanks for the help!
But I would still say that the behavior for 5' adapters is a litte unintuitive.

**Comment by marcelm** [comment]
Great this solved it. I have opened issue #254 so I don’t forget this problem.

**Comment by marcelm** [comment]
Finding rightmost 5' adapters is now possible, see #254.
