### ISSUE TITLE
too-short-read option parsing all reads to untrimmed

### ISSUE THREAD

**Issue by gcorre** [marcelm/cutadapt#257]
Dear all,
I'm processing paired-end reads to remove adaptor in R1 and filtering short reads.
When using only -m, the legacy mode works well but when adding the --too-short options to parse short reads in separate output files, the legacy mode is no longer active and all the reads (containing the adaptor or not) go to the untrimmed output file but are actually trimmed.

Command line:
> cutadapt -O 23 -e 0.1-m 35 --pair-filter=any
 --too-short-output R1_short.fastq 
--too-short-paired-output R2_short.fastq 
--no-indels 
-g GTCTGTTGTGTGACTCTGGTAAC 
--untrimmed-paired-output R2_noLTR.fastq 
--untrimmed-output R1_noLTR.fastq 
-o R1_LTR.fastq 
-p R2_LTR.fastq 
pair1.fastq 
pair2.fastq
 
log file with -m only : 

> Trimming 1 adapter with at most 10.0% errors in paired-end legacy mode ...

log file with --too-short options:
> Trimming 1 adapter with at most 10.0% errors in paired-end mode ...

Is there an option I missed or is there a parsing error when using those options?
cutadapt 1.14 with Python 3.5.2/debian
Best,

**Comment by marcelm** [comment]
You have two filtering criteria: Requiring a minimum length and checking whether a read is trimmed or not. I think the problem is that you want `--pair-filter=any` for one of them and `--pair-filter=both` for the other. So a bit more detailed, given the options above, cutadapt does the following when it has processed a read pair to decide where to write it:

1. It checks whether *any* (since `--pair-filter=any`) of the two reads in the pair are too short. If so, it writes the pair to `R1_short.fastq` and `R2_short.fastq`. Since R2 will never be too short, the requirement that *any* read is too short essentially checks only R1 - so this works as desired I assume.
2. It checks whether *any* of the two reads in the pair are untrimmed. If so, it writes the pair to `R1_noLTR.fastq` and `R2_noLTR.fastq`. Here is the problem: Since you do not modify R2, it will always be untrimmed and no pair will ever be considered "untrimmed". Using `--pair-filter=both` would work here.

It is currently not possible to have different pair-filter settings for the different filters, so my suggestion for now is to process your data in two steps, that is, running cutadapt twice: First, trim the reads and use the `--untrimmed-output` options. Then filter by length. The disadvantage (if it is one) is that the order by which the criteria are applied is swapped (too short first then untrimmed vs untrimmed then too short).

I wonder whether it makes sense to add a `--pair-filter=first` option, which would be a way to re-enable "legacy mode".

**Comment by gcorre** [comment]
Thanks a lot for the comment,
Indeed I want to trim the R1 reads for an adaptor (-g option) and output R1/R2 pairs in-sync in separate files if R1 contains the adaptor or not.
 R2 is not modified but the pairs must be discarded if any of R1/R2 is too short before or after trimming R1.

I tried with `--pair-filter=both` and it works but pairs with trimmed R1 reads that are too short are not discarded if R2 is longer than the threshold. A two steps approach is a solution but increases to computing time. 
Indeed `--pair-filter` option should take into account the number of adaptor provided as option `both ` will fail if only one adaptor is indicated in the command line. Maybe setting two independent filtering options, one for the trimming (any or both reads trimmed according to the number of adaptors provided) and one for the min/max size, quality and #Ns with `any|both` option.

best

**Comment by marcelm** [comment]
Yes, it probably makes sense to take into account that only an R1 adapter is provided and to adjust behavior accordingly. However, I’m a bit reluctant to introduce behavior changes, so I’ll have to think about this. Please leave the issue open for now.

**Comment by marcelm** [comment]
This is finally fixed in the development version. Here is what I added to the changelog:

> When only R1 or only R2 adapters are given, the `--pair-filter` setting is now forced to `both` for the `--discard-untrimmed` (and `--untrimmed-(paired-)output`) filters.
>
> Otherwise, with the default ``--pair-filter=any``, all pairs would be considered untrimmed because one of the reads in the pair is always untrimmed.

Additionally, I have just removed "legacy mode", but I have also added the `--pair-filter=first` option I mentioned above.
