### ISSUE TITLE
Failure in saving too-short reads to file

### ISSUE THREAD

**Issue by roberthaney** [marcelm/cutadapt#258]
I am running 1.9, with 300bp PE data and the following command:

cutadapt -q 20 -m 30 -o 46CdarMaj_R1_trimmed.fq -p 46CdarMaj_R2_trimmed.fq --too-short-output 46CdarMaj_trimmed_too-short.fq 46CdarMaj_S1_L001_R1_001.fastq 46CdarMaj_S1_L001_R2_001.fastq 

The run fails with the following error:
Traceback (most recent call last):
  File "/share/pkg/cutadapt/1.9/bin/cutadapt", line 10, in <module>
    cutadapt.main()
  File "/share/pkg/cutadapt/1.9/lib/python2.7/site-packages/cutadapt/scripts/cutadapt.py", line 856, in main
    stats = process_paired_reads(reader, modifiers, modifiers2, filters)
  File "/share/pkg/cutadapt/1.9/lib/python2.7/site-packages/cutadapt/scripts/cutadapt.py", line 287, in process_paire
d_reads
    if filter(read1, read2):
  File "/share/pkg/cutadapt/1.9/lib/python2.7/site-packages/cutadapt/filters.py", line 95, in __call__
    self.writer.write(read1, read2)
TypeError: write() takes exactly 2 arguments (3 given)

Thanks for your assistance!

Rob Haney

**Comment by marcelm** [comment]
Hi, you’re using quite an old cutadapt version. If you can, I suggest you update to a more recent one.

The current cutadapt 1.14 gives this error message with the command you gave above:
```
cutadapt: error: When using --too-short-output with paired-end reads, you also need to use --too-short-paired-output
```

**Comment by roberthaney** [comment]
Thanks!  Just to make sure I understand, R1 reads that have a mate that is below the length threshold, but are not below the length threshold themselves, go into the file specified with --too-short-output and R2 that have a mate that is below the length threshold, but are not below the length threshold themselves, go into the file specified by --too-short-paired-output?

**Comment by marcelm** [comment]
Yes, but I would put it differently:

* Paired-end reads are never split. If R1 is written to the `--too-short-output` file, then R2 is always also written to the `--too-short-paired-output` file and vice versa. (This holds also `-o`/`-p`, `--untrimmed-output`/`--untrimmed-paired-output` etc.)
* If R1 *or* R2 (or both) are too short, the filter is considered to apply and the read pair is written to the `--too-short-output`/`--too-short-paired-output` files.
* Option `--pair-filter` can be used to change this behavior. `--pair-filter=any` is the default and the behavior just described. With `--pair-filter=both`, you require that *both* R1 and R2 are too short to be written to the `--too-short-output`/`--too-short-paired-output` files.

**Comment by roberthaney** [comment]
Ah, OK. I am actually looking to emulate the behavior of trimgalore, where if one read of a pair is too short, but the other is not, you discard the too short read, but write the mate that is long enough to an unpaired file as it still may be useful. In these output files from the cutadapt --too-short-output and --too-short-paired-output options, then, there may be reads below the length cutoff or even zero length? I may want to post hoc purge these reads (particularly zero length) after the run then, or is there an option that would mimic trimgalore with which I could rerun? I don't see it in the docs, but maybe I am just missing it?

**Comment by marcelm** [comment]
Sorry for the delay, I’m traveling.

When trimming adapters, the assumption is that the non-trimmed parts of the 5' and 3' reads are actually the same piece of DNA and should therefore be reverse complements of each other (and have the same length). So if an adapter was not found in one read, it’s assumed that it exists in the other as well but that it was just not found.

So cutadapt doesn’t have an option for that. For quality trimming, it would make some sense, but at the moment, you’ll have to postprocess the individual output files.

> In these output files from the cutadapt --too-short-output and --too-short-paired-output options, then, there may be reads below the length cutoff or even zero length?

Since these are the too-short output files, yes. If quality trimming leads to reads with zero length, they will also be in there. Did you mean to ask whether there may be reads that are above the length cutoff? Yes, but for those the mate is too short.

**Comment by marcelm** [comment]
Just reading through this old issue again: I think it is easy enough to achieve the 'rescuing' described here by running Cutadapt separately on the two files created by `--too-short-output` and `--too-short-paired-output`. So for now, I will not add this as a separate feature.

The files specified with `--too-short-(paired-)output` contain the read pairs for which one of the reads is too short. The other may still be long enough to be usable. So here is what I would suggest:

```
cutadapt -m 30 -q 20 -o out.1.fastq.gz -p out.2.fastq.gz --too-short-output=tooshort.1.fastq.gz --too-short-paired-output=tooshort.2.fastq.gz in.1.fastq.gz in.2.fastq.gz
cutadapt -m 30 -o rescued.a.fastq.gz tooshort.1.fastq.gz
cutadapt -m 30 -o rescued.b.fastq.gz tooshort.2.fastq.gz
```
Note that I don’t use 1 and 2 in the names of the two rescued output files because I want to make it very clear that these files are no longer synchronized.

Closing this now, but feel free to object.
