### ISSUE TITLE
question regarding --mask-adapter. also for low quality bases?

### ISSUE THREAD

**Issue by rfolkert** [marcelm/cutadapt#262]
Dear cutadapt team,
I have a question regarding the masking of low quality bases. 
I want to use cutadapt to turn low quality bases at the 5' end into Ns using -q20,0 and --mask-adapter, When I run cutadapt it tells me a number of bases (8.7%) are trimmed (and I assume here turned into Ns), but I don't see any 'per base N content' when I check the quality using fastQC.
Now, this makes me wonder. Does the --mask-adapter also turn low-quality bases into N? Or only adapters?
Best,
Remco

**Comment by marcelm** [comment]
No, the `--mask-adapter` option will only work for “real” adapters, not for quality trimming. Here is a short program to do what you want (only single-end reads):
https://gist.github.com/marcelm/ab659840e0e83ef1fc131d64f507f947
Click on the "Raw" button, save as `qualmask.py`, then follow the instructions in the file itself. If you get error messages, try using the command `python` instead of `python3`. You need to have cutadapt installed. I’m not sure I want this functionality in cutadapt itself - it would be yet another command-line option, of which there already are so many.

**Comment by rfolkert** [comment]
Hi Marcel, thank you for your quick response. 
I will use your work around thanks for offering that!
