### ISSUE TITLE
Anchored adapters with prefix insertions only

### ISSUE THREAD

**Issue by a1an77** [marcelm/cutadapt#272]
I am using cutadapt to filter pool files into single samples, hence I want to use the barcode as the sequence to trim. The problem is that I have many reads with an insertion at the beginning, before the barcode (some do not have it and possible some have 2). I would like to keep the detection as strict as possible (i.e. no errors allowed) but still be able to detect the target within the first few bases of the read. Would this be possible? Maybe a tolerance parameter to be used with anchored adapters?

Allowing errors to catch the insertion is not a desired option since it might lead to wrong sorting of sequences in case the barcode is too close to another one (within the allowed error)

Currently I am using no anchored adapters but that might well lead to detections within the sequence, which is also an error

The desired behaviour is basically, given tolerance of 2 bases, to allow detection of
    
    BADAPTER
    BBADAPTER

but not of 

    BBBADAPTER
    ADABTER

**Comment by marcelm** [comment]
It’s a bit of an obscure feature, but you can do this already now by specifying the adapter as `-g XNNADAPTER` (literal `X` and `N` characters) and choosing an `--overlap` that is equal to the length of the adapter (or less if you wanted to allow partial matches).

The `X` in the beginning forces the match to be close to the 5' end because an `X` always results in a mismatch. There is [a related section in the documentation](https://cutadapt.readthedocs.io/en/stable/recipes.html#avoid-internal-adapter-matches). The `N` bases are wildcards that match any nucleotide without counting as mismatches.

[I intend to document this better](https://github.com/marcelm/cutadapt/issues/232).

**Comment by a1an77** [comment]
Seems to work indeed. I guess it might give problems if there are too many Ns tough, such as more than the --overlap, then it will always find partial matches. But for a few bases it is indeed a good solution, thanks!

**Comment by marcelm** [comment]
Hm, I’m not sure I see how there could be a partial match even with lots of Ns. When the maximum error rate is set to zero, then it should always work.

**Comment by a1an77** [comment]
Since a partial match is allowed only at the beginning of the sequence for 5' adapters it will always include the real adapter and not the Ns, right? Then there should be no problem even raiding the number of Ns.

**Comment by marcelm** [comment]
Yes! 5' adapters are not allowed to 'shift out of the read' at the 3' end.
