### ISSUE TITLE
Run time not reduce in parallel

### ISSUE THREAD

**Issue by haiwufan** [marcelm/cutadapt#279]
Hi Developer,
I install cutadapt v1.15, and trim my sample raw fastq data. I compare normal model and parallel model, but found that running time has not been reduced.
Could help me check what wrong when I run cutadapt?
Thanks!

Result as follows:

Sample | Reads | Bases | Q30% | Q20% | GC% | Ave_len | Cutadapt | Cutadapt parallel ( -j 10)
N0212F | 68451922 | 10267788300 | 92.5802 | 94.995 | 49.6991 | 150 | 25min | 29min
N0212M | 62379484 | 9356922600 | 91.8549 | 94.4256 | 50.642 | 150 | 24min | 26min
N0212P | 68362902 | 10254435300 | 92.0666 | 94.5964 | 50.639 | 150 | 25min | 29min

**Comment by haiwufan** [comment]
Run command as:
cutadapt -a AGATCGGAAGAGC -A AGATCGGAAGAGC -e 0.1 -O 1 -m 36 --max-n 5 -q 30,30 -j 10 -o trim.R1.fastq.gz -p trim.R2.fastq.gz R1.fastq R2.fastq

**Comment by haiwufan** [comment]
Hi marcelm
Here is my log file and cpuinfo.
[cpuinfo.log](https://github.com/marcelm/cutadapt/files/1581325/cpuinfo.log)
[trim.log](https://github.com/marcelm/cutadapt/files/1581326/trim.log)

**Comment by marcelm** [comment]
Thanks, this is interesting.

You did not say whether other people were using the machine at the same time, but even if there are, it should have been faster.

My only idea: Are you running this as a batch job? Did you request enough CPU resources? When I run a job on our cluster, the system prevents me from using more CPU resources than I requested. So even though a cluster node has 16 cores, I only get the resources equivalen to one core if I do not request multiple cores. Even when I run 10 threads, each of them would get only 10% of that one core so that it evens out in the end.

It’s holiday time over here, so I’ll be slow to reply until the end of the year.

**Comment by marcelm** [comment]
One idea from issue #288: Do you have `pigz` available? Cutadapt uses this for parallel output compression if it is installed, otherwise normal single-threaded `gzip`. Possibly this is the bottleneck.

Closing for now. Feel free to re-open if problem persists.
