### ISSUE TITLE
pkg_resources.DistributionNotFound: cutadapt==1.15

### ISSUE THREAD

**Issue by bfristensky** [marcelm/cutadapt#286]
It appears that cutadapt needs to have PYTHONPATH set in order to find some components, at least when cutadapt is installed in a user directory, rather than systemwide. 

It should be noted that cutadapt was installed within a $HOME directory using:
`pip install --install-option="--prefix=$BIRCH/python"`

(The ability to install programs when you don't have root priviliges is often very important!)

On both Red Hat 6.9 and Ubuntu 16.04.3, I need to run cutadapt using the following wrapper:
```
#!/bin/bash
# The lib64 path is needed to find cutadapt, and the
# lib path is needed for cutadapt to find xopen. 
PYTHONPATH="$BIRCH/python/lib64/python2.7/site-packages:$BIRCH/python/lib/python2.7/site-packages"
export PYTHONPATH
$BIRCH/python/bin/cutadapt $*
```
If I omit the PYTHONPATH, I get the following output:
```
Traceback (most recent call last):
  File "/home/psgendb/BIRCHDEV/python/bin/cutadapt", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/pkg_resources.py", line 3007, in <module>
    working_set.require(__requires__)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/pkg_resources.py", line 728, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cutadapt==1.15
```
The installation instructions should make not of this, and it might not hurt to include a wrapper such as that shown above for non-standard installations.

**Comment by marcelm** [comment]
You did not say what is in your `$BIRCH/python/` directory. I assume it is a self-compiled Python installation.

My guess for where the problem is is that you are using a system version of pip (that is, one that lives in `/usr/bin/`), while you should be using a pip from within your custom Python. With that, you wouldn’t need the `--install-option` parameter.

If I’m correct, then the first line in `$BIRCH/python/bin/cutadapt` will be `#!/opt/rh/python27/root/bin/python` or something like this. Change this to `#!/home/psgendb/BIRCHDEV/python/bin/python` and you should not need the wrapper.

A better way to fix this more long-term is to 1) install pip within the self-compiled Python and 2) use that pip to install cutadapt, this time without `--install-option`.

There should never be a need to set PYTHONPATH, even in a wrapper. It will appear to work at first, but mess things up in subtle ways.

> (The ability to install programs when you don't have root priviliges is often very important!)

Yes, of course, which is why 4 out of the 5 installation methods described on <https://cutadapt.readthedocs.io/en/stable/installation.html> do not require root permissions!
