### ISSUE TITLE
Cannot install with miniconda

### ISSUE THREAD

**Issue by SaiPrabhas** [marcelm/cutadapt#287]
Hello I tried to use pip and also miniconda to install cutadapt, but neither of them worked for me. pip install gives me a syntax error and miniconda method says it cannot find the files. I am attaching the screenshot of the error message. Please help me with this issue. Thank you.
![capture](https://user-images.githubusercontent.com/28931820/35343518-7a9ad10c-00f0-11e8-93a2-64fc577a5f36.JPG)

**Comment by marcelm** [comment]
Sorry, but since I don’t run Windows, I cannot help a lot with running cutadapt on it.

Bioconda only [supports Linux and macOS](https://bioconda.github.io/#using-bioconda), so that explains that error message.

This means you will need to go the `pip install` way. According to what another user reported in issue #263, it works when you first install the *Microsoft Visual C++ Compiler for Python 2.7* (see that issue for a link).

**Comment by SaiPrabhas** [comment]
I have the visual C++ compiler installed . The error looks like this.

![cutadapt](https://user-images.githubusercontent.com/28931820/35345087-5135a0a4-00f4-11e8-9cd0-a64068188ed7.JPG)

So I don't think that it might be a dependency issue.

**Comment by marcelm** [comment]
You need to run `pip install` directly from the command-line prompt, not from within python.

**Comment by SaiPrabhas** [comment]
Python scripts were not added in my PATH which is why I could not pip install the package. The package is successfully installed now. I have another question how can I add cutadapt to my PATH? I tried pip show cutadapt command and added that location to my PATH but I still get the following error.

![cutadapt-path](https://user-images.githubusercontent.com/28931820/35347229-173f6f46-00fa-11e8-8abd-c35e9bc3fc8e.JPG)

**Comment by marcelm** [comment]
I don’t know where the binary is installed to, sorry, you will need to search for it. If you cannot find it, you can try to run cutadapt with `python -m cutadapt`.

**Comment by marcelm** [comment]
I hope you solved it, closing for now.
