### ISSUE TITLE
Q: Adapter- and Fixed Trimming in one step

### ISSUE THREAD

**Issue by sklages** [marcelm/cutadapt#289]
Is it possible to first trim off potential adaptors and **after that** to trim off a fixed number of bases from the reads no matter if adaptor has been found in one single cutadapt call?

I am aware that there is `--cut / -U`, but this is applied before adaptor trimming.
Currently I am running cutadapt twice for that ..

**Comment by marcelm** [comment]
The order cannot be changed at the moment. (Suggestions on how to make this possible in a backwards-compatible way are welcome)

In case you don’t know, you can pipe the output of one cutadapt into the second one, like this:
```
cutadapt -a ACGTACGT input.fastq.gz | cutadapt -u 7 -o output.fastq.gz -
```
Note the missing output file on the first invocation and the use of `-` as input on the second invocation. Since both processes run in parallel, it should actually not be too much slower. See also http://cutadapt.readthedocs.io/en/stable/recipes.html#piping-paired-end-data for piping paired-end data this way.

**Comment by sklages** [comment]
Piping perfect! 
I completely missed this recipe. Thanks.

**Comment by marcelm** [comment]
Great, glad I could help!
