### ISSUE TITLE
Extract Adapter sequence

### ISSUE THREAD

**Issue by ghoshal** [marcelm/cutadapt#294]
Hi,

I am using cutadapt to remove a combination of adapters that has multiple Ns. I want to extract the matched adapter sequences and write them to a file. I used the --wildcard-file option but it returned a blank file. I also tried using --info-file and that did not return the matched sequences. Please let me know what I am doing wrong?

cutadapt -f fastq -B NNATCNNGATSSAAANNGGTNNAACNN --mask-adapter --no-indels -O 14 --discard-untrimmed --pair-filter both --info-file E03_5_matches -o E03-5_trimmed_R1.fastq -p E03-5_trimmed_R2.fastq E03-5_S12_L005_R1_001.fastq E03-5_S12_L005_R2_001.fastq > E03-5_info.txt

Thanks,

Bibaswan

**Comment by ghoshal** [comment]
Hi,

I actually found out the exact issue. All my adapters are in Read2 file and the info file is just writing the read one sequences. Is there a way to write the read 2 info file?

Thanks,

Bibaswan

**Comment by marcelm** [comment]
Hi and sorry for the late reply. Regarding whether you can get the info file for read 2: This isn’t implemented, but you can “cheat” and swap read 1 and read 2 when you run cutadapt. So swap the input files, swap the output files and also use `-b` instead of `-B`. I’ll be happy to help more when I have more time.

**Comment by marcelm** [comment]
Does it work when you leave off the `--mask-adapter` option? (If you solved your problem or if it is no longer relevant, feel free to close the issue.)
