### ISSUE TITLE
Trim only adapter but retain 3end extra

### ISSUE THREAD

**Issue by kevin199011** [marcelm/cutadapt#300]
Hi, is it possible to trim adapter sequence only but retain other bases? For example:
SEQUENCEADAPTERSEQEUNCE
when trimming adapter, it can retain both ends (SEQUENCESEQUENCE)? Thank you!

Kevin

**Comment by marcelm** [comment]
This is not directly possible at the moment. You could use the `--info-file` option (see documentation) and then post-process the created info file in order to get the output you need.

Another option would be to run cutadapt twice: Once with `-a ADAPTER` and once with `-g ADAPTER`, and then you get one set of files with the sequence preceding the adapter sequence and another with the sequences coming after the adapter sequence. You would not have both ends in the same record, though.
