### ISSUE TITLE
length of trimming bigger than adapter length

### ISSUE THREAD

**Issue by guillaume-rs** [marcelm/cutadapt#301]
Hi Marcel,

I'm using Cutadapt 1.16 with Python 3.6.5.
And here is my command line :
/usr/local/bin/cutadapt -j 14 -a file:./adapters.fa -A file:./adapters.fa -o ./adapters_trimming/trimmed_fastqR1.fastq -p ./trimmed_fastqR2.fastq ./fastq/A_R1_001.fastq ./fastq/A_R2_001.fastq

It is not really an issue, but I'm not really sure to understand the output of cutadapt.

Sorry for this naive question, but looking at the log of a run, it seems that cutadapt is trimming reads for a length longer than the length of the adapters given in input.
For example I use adapters of 35 bp and reads of 151 bp, and I see that some reads are totally trimmed : 

Overview of removed sequences
length	count	expect	max.err	error counts
...
151	44070	0.0	3	10 1870 37751 4439

As I've seen in the documentation, this behaviour should be normal, but I don't really get what is happening and why a read is trimmed for a length bigger than the size of the adapters.

Thank you in advance for your help,

Guillaume

**Comment by marcelm** [comment]
Yes, this is normal. Cutadapt removes the adapter sequence and anything that follows it, at least for the adapters you specify with `-a`).

This is the only thing that makes sense as only the part before the adapter is what you are interested in. Any sequence that follows after the adapter sequence is just a technical artifact. For example, even if the the DNA molecule in the sequencer would end right after the adapter, the sequencer would still continue to read random nucleotides until the read length is reached. There may also be an indexing barcode (used for multiplexing) after the adapter sequence.

You get empty (completely trimmed) reads when the read starts with an adapter sequence. This is a so-called “adapter dimer”. Library preparation usually adds a 5' and 3' adapter to each DNA fragment you want to sequence (you get DNA fragments that look like 5'ADAPTER-SEQUENCE-3'ADAPTER), but in this case it so happened that the 5' adapter was attached directly to the 3' adapter with no sequence in between. You then get 5'ADAPTER-3'ADAPTER. Since sequencing starts after the 5' adapter, you see a read that starts with the 3' adapter.

**Comment by GuillaumeRS** [comment]
Ok i see much clearer now. 
I didn't know that the sequencer would continue to read random nucleotides until the read length is reached. That explains why I have reads beginning with an adapter but still 151 bp long.
Thank you very much for your thorough explanation!
