### ISSUE TITLE
Allowing a range of base repeats using regex

### ISSUE THREAD

**Issue by MRMacArthur** [marcelm/cutadapt#304]
I am running cutadapt 1.14 on Python 2.7.12. The tool is maintained on a Linux. 

I would like to allow for a range of 2-4 nucleotides when searching for my adapters, the following is my command line input:
cutadapt -g 'CACCG...GT{2,4}AGAGC' --match-read-wildcards -o A_T.fastq A.fastq

I get this error:
cutadapt: error: invalid literal for int() with base 10: '2,4'

Defining a single numeric repeat (ex. {4} ) works fine, but is the regex range parameter supported in this or the newer version of cutadapt.

**Comment by marcelm** [comment]
This appears to be the first issue you opened in a public GitHub repo, so one suggestion for the future: If you ask a question and get an answer which obviously someone took the time to write, then it would be considered good form to show some appreciation. Just closing the issue is efficient, but somewhat snub. A “thanks” goes a long way towards keeping an Open Source developer motivated! This applies even if the answer isn’t what you wished for.

**Comment by MRMacArthur** [comment]
Oops sorry about that, no disrespect intended, didn't know the conventions.
I greatly appreciate the quick response and the fantastic tool!

All best,
M

**Comment by marcelm** [comment]
Sure, I didn’t assume bad intentions! Thanks for responding.
