### ISSUE TITLE
cutadapt does not see python 3 on Ubuntu 

### ISSUE THREAD

**Issue by fjvorhoelter** [marcelm/cutadapt#307]
I use cutadapt 1.16 with Python 2.7.12 on an Ubuntu machine. There is also Python 3.5.2 installed on the system.  However, when I try to use multiple CPU cores, I receive an error message:

> user@machine:~/scripts$ python3 -V
> Python 3.5.2
> user@machine:~/scripts$ cutadapt -j 4 test.R1.fastq.gz 
> ERROR: Running in parallel is not supported on Python 2

I installed cutadapt via pip: sudo pip install cutadapt.
The OS version is Ubuntu 16.04.4 LTS.
How can I let cutadapt make use of Python 3?

**Comment by marcelm** [comment]
The command you gave installs cutadapt under Python 2. You should remove the current installation with `sudo pip uninstall cutadapt` and then try `sudo pip3 install cutadapt` instead (note `pip3` instead of just `pip`).

I should mention that while `sudo pip` works, it is generally [not recommended as it poses security risks](https://stackoverflow.com/questions/21055859/). See also the [installation instructions](https://cutadapt.readthedocs.io/en/stable/installation.html) for other ways to install cutadapt.
