### ISSUE TITLE
unsynchronized demultiplex paired-end reads

### ISSUE THREAD

**Issue by liaoyunshi** [marcelm/cutadapt#308]
Dear Marcel,

Thanks for reading my issue.

Recently, I used pip to install cutadapt 1.6 with python 3.6. And I used cutadapt to demultiplex my paired-end data which contain inline barcode index at the 5' end. The whole barcode = **5'- [INDEX-seq][COMMON-ADAPTER] -3'**

So I used the following command:
**cutadapt -g file:barcode.fasta -G COMMON-ADAPTER -o trimmed-{name}.1.fastq -p trimmed-{name}.2.fastq input.1.fastq input.2.fastq**

The input read 1 and read 2 have the same number of reads.

According to the manual, `The paired-end data would be demultiplexed based on the first read. And if adapters to be found in the second read are given, they are detected and removed as normal, but these matches do not influence where the read pair is written. This is to ensure that read 1 and read 2 are always synchronized.`

So theoretically, for each demultiplexed paired-end dataset, the number of first read should equal to that of the second read. However, I did find the difference between the numbers of first and second reads, which indicated unsynchronization of demultiplexed read 1 and read 2.

Thus, I wonder if I do anything wrong leads to such unsynchronization, or could you please give me some suggestion about synchronizing the demultiplexed read 1 and read 2 again.

Thanks for your help.

**Comment by marcelm** [comment]
Hi, thanks for reporting. I need a little more information before I can help (or possibly fix a bug). Did you use any other options beside the ones you mentioned above? In which of your output files did you find this desynchronization (in all, or just in some)? How did you measure it? Did cutadapt finish successfully?

**Comment by marcelm** [comment]
I am very sorry for the late reply.

1. Yes, demultiplexing works in the same way as regular adapter trimming, except that after processing each read, the program looks at which adapter it has actually removed from it and writes the trimmed read to the appropriate output file.
2. Partial adapter matches are only allowed at the end of a read. The minimum overlap length applies only in those cases. Adapters within reads must occur in full. Since the adapter occurrence in your example `aaaGGTGCTGATATTttt` is missing the last characters (`GCT`), it will not be found. Note that some types of truncated/partial occurrences may still be found because the algorithm is error-tolerant.
3. As is probably clear now from what I wrote in the previous item, the leftmost occurrence won’t be found at all, so the trimmed read should be `ggg`.

**Comment by marcelm** [comment]
I hope I was able to answer your questions. Closing this issue now, but feel free to comment if you want to discuss more.
