### ISSUE TITLE
Demultiplexing Issue w/QIIME 2 Wrapper

### ISSUE THREAD

**Issue by dwh2102** [marcelm/cutadapt#309]
Hello,

I am using Cutadapt 1.16 with QIIME 2 version 2018.4.

I am demultiplexing a data set with 6 different amplicons barcoded from 47 different templates. I am using the barcode and primer sequence together as the barcode for demultiplexing which works well except that the first sample analyzed--and I've re-ordered them and it's always whichever one is listed first in the metadata file--winds up with a huge number of reads, way more than expected. All the extraneous ones seem be reads with 3 bases removed. Any help would be greatly appreciated. 

Thanks!

(qiime2-2018.4) qiime2@qiime2core2018-4:~$ qiime cutadapt demux-single --i-seqs multiplexed-seqs.qza --m-barcodes-file metadata2.tsv --m-barcodes-column BarcodeSequence --p-error-rate 0 --o-per-sample-sequences demultiplexed-seqs.qza --o-untrimmed-sequences untrimmed.qza --verbose
Running external command line application. This may print messages to stdout and/or stderr.
The command being run is below. This command cannot be manually re-run as it will depend on temporary files that no longer exist.

Command: cutadapt --front file:/tmp/tmpt85v7l8r --error-rate 0.0 -o /tmp/q2-CasavaOneEightSingleLanePerSampleDirFmt-i_po3nqz/{name}.1.fastq.gz --untrimmed-output /tmp/q2-MultiplexedSingleEndBarcodeInSequenceDirFmt-5qgb1s72/forward.fastq.gz /tmp/qiime2-archive-ip70iw2x/72148ae6-d0f2-49f0-81ec-4fa1bd2eee5e/data/forward.fastq.gz

This is cutadapt 1.16 with Python 3.5.5
Command line parameters: --front file:/tmp/tmpt85v7l8r --error-rate 0.0 -o /tmp/q2-CasavaOneEightSingleLanePerSampleDirFmt-i_po3nqz/{name}.1.fastq.gz --untrimmed-output /tmp/q2-MultiplexedSingleEndBarcodeInSequenceDirFmt-5qgb1s72/forward.fastq.gz /tmp/qiime2-archive-ip70iw2x/72148ae6-d0f2-49f0-81ec-4fa1bd2eee5e/data/forward.fastq.gz
Running on 1 core
Trimming 47 adapters with at most 0.0% errors in single-end mode ...
Finished in 786.25 s (283 us/read; 0.21 M reads/minute).

=== Summary ===

Total reads processed:               2,778,271
Reads with adapters:                   236,990 (8.5%)
Reads written (passing filters):     2,778,271 (100.0%)

Total basepairs processed:   581,744,202 bp
Total written (filtered):    578,255,648 bp (99.4%)

=== Adapter ATCC ===

Sequence: CTAAGGTAACGATGGCGGACGGGTGAGTAA; Type: regular 5'; Length: 30; Trimmed: 136588 times.

No. of allowed errors:
0-30 bp: 0

Overview of removed sequences
length	count	expect	max.err	error counts
3	135131	43410.5	0	135131
4	133	10852.6	0	133
5	4	2713.2	0	4
16	4	0.0	0	4
17	13	0.0	0	13
18	9	0.0	0	9
19	2	0.0	0	2
28	1	0.0	0	1
29	1	0.0	0	1
30	1289	0.0	0	1289
31	1	0.0	0	1

=== Adapter 14 ===

Sequence: AAGAGGATTCGATGGCGGACGGGTGAGTAA; Type: regular 5'; Length: 30; Trimmed: 3719 times.

No. of allowed errors:
0-30 bp: 0

Overview of removed sequences
length	count	expect	max.err	error counts
29	26	0.0	0	26
30	3685	0.0	0	3685
31	7	0.0	0	7
48	1	0.0	0	1

=== Adapter 18 ===

Sequence: TACCAAGATCGATGGCGGACGGGTGAGTAA; Type: regular 5'; Length: 30; Trimmed: 1539 times.

No. of allowed errors:
0-30 bp: 0

Overview of removed sequences
length	count	expect	max.err	error counts
26	1	0.0	0	1
28	1	0.0	0	1
29	4	0.0	0	4
30	1530	0.0	0	1530
31	3	0.0	0	3

=== Adapter 21 ===

Sequence: CAGAAGGAACGATGGCGGACGGGTGAGTAA; Type: regular 5'; Length: 30; Trimmed: 1437 times.

No. of allowed errors:
0-30 bp: 0

Overview of removed sequences
length	count	expect	max.err	error counts
29	7	0.0	0	7
30	1429	0.0	0	1429
31	1	0.0	0	1

**Comment by marcelm** [comment]
What you are seeing is due to partial adapter matches.

If you look at the statistics for the first adapter, you see that almost all of the matches are just 3 bases long:
```
Overview of removed sequences
length count expect max.err error counts
3 135131 43410.5 0 135131
```
The full-length matches are a bit further down in the same table:
```
30 1289 0.0 0 1289
```
(1289 times, a sequence of length 30 was trimmed, so this is a full-length match.)

QIIME uses the “regular 5' adapter” type. These adapters are required to occur at the start of a read, but partial matches are also allowed, as you can [read in the documentation](https://cutadapt.readthedocs.io/en/stable/guide.html#five-prime-adapters).

What happens here is that many reads do not contain exact, full-length adapter matches. However, if a read happens to start with `TAA`, Cutadapt will find a partial match to the first adapter because that one ends in `TAA`. Actually, it appears that *all* your adapter sequences end in `TAA`, so why does it assign all these reads that happen to start with `TAA` to the *first* adapter only? The answer is that Cutadapt checks each adapter in turn and unless there’s a better match later, it keeps the first match that it finds.

If you were using stand-alone Cutadapt, I would recommend that you do not use the regular 5' adapter type, but anchored 5' adapters. For that, you need to prefix each of the 47 sequences with a `^` character. Alternatively, you could increase the minimum overlap parameter.

I don’t know about the internals of the QIIME 2 wrapper, so I cannot say whether you can set that on the `qiime2` command-line.

Perhaps this is worth reporting to the authors of the QIIME 2 Cutadapt wrapper?

**Comment by dwh2102** [comment]
That makes perfect sense. So the problem stems from me using a combined barcode and sequence to sort since there are multiple amplicons with the same primer. 

I will try what you suggested. I crossposted on the QIIME 2 forum so they are aware. 

Thanks so much for your quick response.

**Comment by marcelm** [comment]
Great. Do you think this issue can be closed?

**Comment by dwh2102** [comment]
Sure thing. Thanks again.
