### ISSUE TITLE
Problem removing multiple adapters and adapter contamination

### ISSUE THREAD

**Issue by elxerone** [marcelm/cutadapt#323]
Hello,

Thanks for the fantastic program and very clear manual! I’ve been working years without any problems, however, I have a new primer set and now I am a bit confused how to proceed (cutadapt 1.16 with Python 2.7.14.)

I have paired-end amplicon reads (Illumina MiSeq) sequenced with 300bp product, so basically the product is sequenced from both ends. I need to remove both the forward primer and reverse complement from the reads. Trimming seems to work fine, however, I noticed that I have also forward primer in the middle of some forward reads which I should trim off as well. Can you help me how to do that? I tried this: 

cutadapt -a FORWARDR1...RCREVERSER2 -A FORWARDR2...RCREVERSER1 -m 1 -e 0.2 -O 15 -o TEST_R1.fastq -p TEST_R1.fastq TEST_R1.fastq TEST_R2.fastq > TEST_trim.log

but I have no idea how to force it to remove both primers in the beginning of the read as well as the primer contamination in the middle, could you help me?

Many, many thanks in advance!
Eeva

**Comment by elxerone** [comment]
Just to let you know that I found a solution to discard the contaminants.
I ran:
cutadapt -g ADAPTER -m 250 -e 0.2 -O 15 --discard-trimmed --pair-filter=any -o TEST_R1.fastq -p TEST_R1.fastq TEST_R1.fastq TEST_R2.fastq > TEST_trim.log

Couldn't figure out if it would have been possible to do everything at once but at least the result is right.
/Eeva

**Comment by marcelm** [comment]
Hi, great you figured it out yourself. I think the two-step solution you used is a good one. Possibly you could have used the [option for linked adapters without anchoring](https://cutadapt.readthedocs.io/en/stable/guide.html#linked-nonanchored) (that is, use `-g` instead of `-a`), but if you want some reads to be trimmed only and some to be discarded, then you do need two steps at the moment.
