### ISSUE TITLE
One of the reported length values is much larger than the length of the primer

### ISSUE THREAD

**Issue by tarunaaggarwal** [marcelm/cutadapt#331]
Hi @marcelm - I'm trying to remove primers from some files and the program is working fine for the most part. I just noticed something weird in the reports that are generated by Cutadapt. Below are my questions and info you asked for.

- Cutadapt and Python version: `This is cutadapt 1.17 with Python 3.6.6`
- How you installed the tool (conda or pip, for example): `conda`
- Which command-line parameters you used: 
```
	cutadapt \
	-G R22=GCCTGCTGCCTTCCTTGGA \
	-g G18S4=GCTTGTCTCAAAGATTAAGCC \
	-o B4N01MUC007.L001.R1.002.cutadapt.fastq \
	-p B4N01MUC007.L001.R2.002.cutadapt.fastq \
	--discard-untrimmed \
	B4N01MUC007.L001.R1.002.fastq.gz B4N01MUC007.L001.R2.002.fastq.gz \
	-O 10 \
	-e 0.1 \
	-m 1
```

- An example input read (or read pair): Files are [here](https://www.dropbox.com/sh/5o1j4yixfg01nnj/AACM8WxjiQsdpo2ZhW-_Z4pAa?dl=0)
- The output that cutadapt produces:
```
This is cutadapt 1.17 with Python 3.6.6
Command line parameters: -G R22=GCCTGCTGCCTTCCTTGGA -g G18S4=GCTTGTCTCAAAGATTAAGCC -o /bigdata/biklab/shared/ellen-pape/GSR/data-clea
n/cutadapt-results/trimmed/B4N01MUC007.16.L001.R1.001.cutadapt.fastq -p /bigdata/biklab/shared/ellen-pape/GSR/data-clean/cutadapt-res
ults/trimmed/B4N01MUC007.16.L001.R2.001.cutadapt.fastq --discard-untrimmed /bigdata/biklab/shared/ellen-pape/GSR/data-raw/18S_both_ru
ns/B4N01MUC007.16.L001.R1.001.fastq.gz /bigdata/biklab/shared/ellen-pape/GSR/data-raw/18S_both_runs/B4N01MUC007.16.L001.R2.001.fastq.
gz -O 10 -e 0.1 -m 1
Running on 1 core
Trimming 2 adapters with at most 10.0% errors in paired-end mode ...
Finished in 6.78 s (81 us/read; 0.74 M reads/minute).

=== Summary ===

Total read pairs processed:             83,528
  Read 1 with adapter:                  83,259 (99.7%)
  Read 2 with adapter:                  80,882 (96.8%)
Pairs that were too short:                   0 (0.0%)
Pairs written (passing filters):        80,646 (96.5%)

Total basepairs processed:    50,283,856 bp
  Read 1:    25,141,928 bp
  Read 2:    25,141,928 bp
Total written (filtered):     45,330,519 bp (90.1%)
  Read 1:    22,585,643 bp
  Read 2:    22,744,876 bp

=== First read: Adapter G18S4 ===

Sequence: GCTTGTCTCAAAGATTAAGCC; Type: regular 5'; Length: 21; Trimmed: 83259 times.

No. of allowed errors:
0-9 bp: 0; 10-19 bp: 1; 20-21 bp: 2

Overview of removed sequences
length	count	expect	max.err	error counts
11	1	0.0	1	1
12	1	0.0	1	1
13	2	0.0	1	2
14	4	0.0	1	2 2
15	1	0.0	1	0 1
16	2	0.0	1	2
17	14	0.0	1	12 2
18	36	0.0	1	23 12 1
19	409	0.0	1	41 76 292
20	3907	0.0	2	446 3271 190
21	78827	0.0	2	76513 2238 76
22	52	0.0	2	5 39 8
23	1	0.0	2	0 0 1
24	1	0.0	2	1
75	1	0.0	2	1

=== Second read: Adapter R22 ===

Sequence: GCCTGCTGCCTTCCTTGGA; Type: regular 5'; Length: 19; Trimmed: 80882 times.

No. of allowed errors:
0-9 bp: 0; 10-19 bp: 1

Overview of removed sequences
length	count	expect	max.err	error counts
10	1	0.1	1	1
11	2	0.0	1	1 1
12	14	0.0	1	14
13	4	0.0	1	2 2
14	8	0.0	1	1 7
15	22	0.0	1	15 7
16	29	0.0	1	7 22
17	40	0.0	1	20 20
18	2346	0.0	1	296 2050
19	78336	0.0	1	74594 3742
20	80	0.0	1	13 67

```
Note the 75 bp len for the first read, please. How is Cutadapt finding a primer seq of 75 bp long with the above parameters? I'd think the length would be 22 bp at most. Am I wrong? Might you please clarify? Thank you!

Taruna

**Comment by marcelm** [comment]
Hi Taruna, thanks for using Cutadapt. The answer is that the "length" column refers to the length of the sequence that was removed from the read – not to the length of the match. If Cutadapt finds a 5' adapter, it always removes the match and also all preceding bases if there are any. So in your case, the adapter was found somewhere in the middle of the read and the adapter itself and the 54 bases preceding it were removed. There is a sentence about this [in the documentation](https://cutadapt.readthedocs.io/en/stable/guide.html#how-to-read-the-report), but perhaps it’s a bit hidden.

The regular 5' adapter type you are using allows these types of ”internal matches”. If you don’t want that, you could use a [non-internal 5' adapter](https://cutadapt.readthedocs.io/en/stable/guide.html#non-internal). That adapter type was added very recently in Cutadapt 1.17. But I guess it does not matter much in your case since there is just one internal occurrence anyway.

**Comment by tarunaaggarwal** [comment]
Hi @marcelm - thank you for clarifying! Oh, the documentation isn't hidden. It's my fault. I didn't RTfM :-)
