### ISSUE TITLE
Trimming specific number of bases from both paired end reads

### ISSUE THREAD

**Issue by eoziolor** [marcelm/cutadapt#337]
- Cutadapt 1.18 and Python version 2.7
- How you installed the tool: conda
- Which command-line parameters you used: 
cutadapt -j 8 --interleaved -a CTGTCTCTTATA -A CTGTCTCTTATA --cut=10 -q 30 --trim-n --minimum-length 36 -

I am using the above command on an interleaved file trying to cut the first 10 bases from both reads. Unfortunately, I think cutadapt is only cutting the reads from the forward read (as suggested by the --help). Is there any way to trim this for both sets of reads in an interleaved or paired end input?

Thank you!

-Elias

**Comment by marcelm** [comment]
Yes, there is: Use the `-U` option, which works the same as `--cut`, but applies to the reverse read instead of the forward read. It makes more sense if you know that `--cut` is the same as `-u`, and then the same symmetry applies as with `-a`/`-A`. That is, the lowercase option (`-u`) applies to the forward read, the uppercase one (`-U`) to the reverse read.

By the way, are you sure Cutadapt is actually running under Python 2.7? The `-j` option for running on multiple cores is only supported on Python 3.

**Comment by eoziolor** [comment]
Yea sorry the -j was a leftover from when I ran it with my cluster's module, but that's cutadapt 1.15, so I switched to  a bioconda environment which was a 2.7.15 and the -j didn't work anymore.

Thanks so much for the help! Is the -U option in the readthedocs documentation somewhere? I looked for a while and couldn't find the answer there.

**Comment by marcelm** [comment]
It’s definitely in the `--help` output under the “Paired-end options” heading. There is also a sentence [in the docs](https://cutadapt.readthedocs.io/en/stable/guide.html#trimming-paired-end-reads):

> There is also option -U, which you can use to remove a fixed number of bases from the second read in a pair.

But I agree, the fact that you looked for it and did not find it means that the docs need to be improved.

**Comment by eoziolor** [comment]
Holy crap, I'm sorry I bothered you there. Yea I did look for a while, but I missed it regardless. I really appreciate the quick help!

**Comment by marcelm** [comment]
I’ve rewritten the docs slightly. There is now a table that lists the R1 options and their R2 counterparts. See https://cutadapt.readthedocs.io/en/latest/guide.html#trimming-paired-end-reads .
