### ISSUE TITLE
Cutadapt Parallel running

### ISSUE THREAD

**Issue by AlexFryd** [marcelm/cutadapt#338]
Hello everyone,
First thing to mention I am a rookie when it comes to Linux, Python etc. :)

I installed cutadapt (version 1.18) from the Anaconda cloud:
"conda install -c bioconda cutadapt "

I am also using python version 3.6,

I am using a command to do some single-end trimming of some undesired sequences. That is what I am using: 

`for i in $(ls myfile*.gz) ; do /pathway/to/cutadapt -b "A{25}" -b "A{50}" -q 5 -m 20 -j 10 -o cutadapt_$i $i ; done`
 Problem is that I get this error: **Running in parallel is not supported on Python 2**

I find this strange as I am running everything in python 3.6 environment. If I take out `-j 10` option, the code works, running in a single core.

Has anyone ever encountered such an issue?

Any feedback would be more than welcome!!!

Thank you in advance!

Alex

**Comment by marcelm** [comment]
Hi, there are a couple of things to try.

* When you install a tool with Conda, it will set up your environment in such a way (to be precise: the `$PATH` environment variable) that you only need to write the name of the program to run it. Do not use `/path/to/cutadapt`, but write `cutadapt` only. That way, you can be sure that you actually use the cutadapt version that was installed with Conda.

* Please run `conda list cutadapt` to see what it says in the 'Build' column. It should say `py36_0`. If it says `py27_0`, you have the Python 2 version of Cutadapt.

I suggest the following.
1. [Setup bioconda in the official way](http://bioconda.github.io/#set-up-channels). (Just copy and paste the three commands.) If you follow the instructions, you do not need to add the `-c bioconda` in the future.
2. Delete your current Cutadapt installation (with `conda remove cutadapt`)
3. Create a new so-called Conda environment with the following command:
```
conda create -n cutadapt cutadapt python=3
```
The first `cutadapt` (after the `-n`) is the name of the new environment. This is a name that you choose, it does not have to be `cutadapt`. The last two arguments `cutadapt` and `python=3` are package names. The `python=3` will force a Python version of 3.

Now, whenever you want to use Cutadapt, you need to *activate* the environment that you just created with `source activate cutadapt`.

Environments take a couple of minutes to learn, but I highly recommend using them because whenever something appears to get messed up, you can just create a new environment and install everything freshly in there. (And delete the old environment with `conda env remove -n envname`).

The next Cutadapt release doesn’t support Python 2.7 anymore, so this issue will not come up again.

**Comment by AlexFryd** [comment]
Hello  Marcelm,

Thanks a lot for your help! Indeed it now worked absolutely fine. So I will working this way from now on!

Thanks again!

Alex

**Comment by marcelm** [comment]
Great :-)
