### ISSUE TITLE
Error: too many parameters

### ISSUE THREAD

**Issue by masumistadler** [marcelm/cutadapt#342]
Hello,

I'm running into an error when trying to cut my primers from paired-end reads (V4 region 16S rRNA) sequenced with Illumina MiSeq. I'm using:

- Cutadapt (Vers. 1.18) and Python (Vers. 2.7.15rc1) / Python3 (Vers. 3.6.6) on a Ubuntu 18.04.01 LTS
- Installed via `sudo pip install cutadapt` and upgraded with `sudo pip install --upgrade cutadapt`

I'm executing the following command:

`-g GTGCCAGCMGCCGCGGTAA -a ATTAGAWACCCBDGTAGTCC -G GGACTACHVGGGTWTCTAAT -A TTACCGCGGCKGCTGGCAC -n 2 -o /path/to/unassembledseq/with primers/cutadapt/RO229D_R1.fastq -p /path/to/unassembledseq/with primers/cutadapt/RO229D_R2.fastq /path/to/with primers/filtN/RO229D_R1.fastq /path/to/unassembledseq/with primers/filtN/RO229D_R2.fastq`

I'm getting the error:

   `cutadapt: error: Too many parameters.`

For all my samples (several hundred). I have ambiguous nucleotides in the primers, but if I understood the method correctly that shouldn't be causing the problem. I also found that some people posted similar questions, but usuall it was a simple error such as missing spaces or wrong hyphen.

I have to note that I am following this [tutorial](https://benjjneb.github.io/dada2/ITS_workflow.html), so I'm running terminal through R and it's looping through all my samples. However, I tested whether this is the issue. So I ran the exact same code with one sample in the terminal and it gives me the same error.

I hope we can find a solution, I was really looking forward to use cutadapt instead of trimLeft methods...

Thank you in advance!

**Comment by marcelm** [comment]
Just a short question before trying to analyze this deeper: Are there by any chance spaces in any of the paths?

I realize that you did not write the actual path you are using, but if you do have a directory named `with primers/` in the path, then running the command as above won’t work.

This isn’t an issue with Cutadapt per se, but with any command that is run on the Linux shell: If there is a path with spaces in it, you need to either surround the path in quotes, as in `"my path with spaces"` (single quotes work as well), or you need to write a backslash before the space, as in `my\ path\ with\ spaces`. If you don’t do this, such a path is going to be interpreted as multiple arguments.

Here is how you could fix the above command:
```
cutadapt -g GTGCCAGCMGCCGCGGTAA -a ATTAGAWACCCBDGTAGTCC -G GGACTACHVGGGTWTCTAAT -A TTACCGCGGCKGCTGGCAC -n 2 -o "/path/to/unassembledseq/with primers/cutadapt/RO229D_R1.fastq" -p "/path/to/unassembledseq/with primers/cutadapt/RO229D_R2.fastq" "/path/to/with primers/filtN/RO229D_R1.fastq" "/path/to/unassembledseq/with primers/filtN/RO229D_R2.fastq"
```
I haven’t yet read the tutorial you linked to, so I cannot say how you could fix the problem there. Of course an easy workaround would be to rename the directory so that they don’t contain any spaces.

**Comment by marcelm** [comment]
No worries; I am glad I could help :-).

Perhaps I could even improve the error message a bit so people will get immediate advice on what could be wrong.

**Comment by marcelm** [comment]
The next version of Cutadapt will print this error message when you run the command above:
```
cutadapt: error: You provided 6 input file names, but either one or two are expected. The file names were:
 - 'primers/cutadapt/RO229D_R1.fastq'
 - 'primers/cutadapt/RO229D_R2.fastq'
 - '/path/to/with'
 - 'primers/filtN/RO229D_R1.fastq'
 - '/path/to/unassembledseq/with'
 - 'primers/filtN/RO229D_R2.fastq'
Hint: If your path contains spaces, you need to enclose it in quotes
```

**Comment by masumistadler** [comment]
This is great and very helpful. Thank you!
