### ISSUE TITLE
Finding all adapter occurrences in each read

### ISSUE THREAD

**Issue by awgymer** [marcelm/cutadapt#344]
- `cutadapt 1.13` and `Python 3.5.2`
- Installed with `pip`
Command line:

`cutadapt -g file:5p_adapters.fasta --times 8 -O 15 --info-file test.tsv -o /dev/null test.fasta`

I am trying to trim multiple adapters from a sequence and parse the info file to see what coordinates they were trimmed at. 
Unfortunately I can't provide the actual sequences used to trim or being trimmed. 

For this particular sequence I expect 3 adapters to be trimmed from the 5' end. 

I will call them `5p_a1`, `5p_a2`,  and `5p_a3`. 
They occur in this order in the target sequence and the adapters fasta I am using. 
When I run the above command however, `5p_a1` and `5p_a3` are removed but not `5p_a2`. 

I get the following output from `cutadapt`:

```
=== Adapter 5p_a1 ===

Sequence: AAAAAAAAAAAAAAAAAAAAAA; Type: regular 5'; Length: 22; Trimmed: 1 times.

No. of allowed errors:
0-9 bp: 0; 10-19 bp: 1; 20-22 bp: 2

Overview of removed sequences
length  count   expect  max.err error counts
8540    1       0.0     2       1

=== Adapter 5p_a2 ===

Sequence: GGGGGGGGGGGGGGGGGGGGG; Type: regular 5'; Length: 21; Trimmed: 0 times.

=== Adapter 5p_a3 ===

Sequence: CCCCCCCCCCCCCCCCCCCCC; Type: regular 5'; Length: 21; Trimmed: 1 times.

No. of allowed errors:
0-9 bp: 0; 10-19 bp: 1; 20-21 bp: 2

Overview of removed sequences
length  count   expect  max.err error counts
113     1       0.0     2       1

```

So `5p_a2` not trimmed. 
However if I remove `5p_a3` from the adpaters file I get the following output:

```
=== Adapter 5p_a1 ===

Sequence: AAAAAAAAAAAAAAAAAAAAAA; Type: regular 5'; Length: 22; Trimmed: 1 times.

No. of allowed errors:
0-9 bp: 0; 10-19 bp: 1; 20-22 bp: 2

Overview of removed sequences
length  count   expect  max.err error counts
8540    1       0.0     2       1

=== Adapter 5p_a2 ===

Sequence: GGGGGGGGGGGGGGGGGGGGG; Type: regular 5'; Length: 21; Trimmed: 0 times.
No. of allowed errors:
0-9 bp: 0; 10-19 bp: 1; 20-21 bp: 2

Overview of removed sequences
length  count   expect  max.err error counts
60      1       0.0     2       0 1
```

`5p_a3` trimmed!

I can see that the error counts are slightly different for `5p_a2` - `0 1` compared to `1`. 
But both have 1 total error so I am confused as to why this causes `5p_a2` to be skipped.

**Comment by awgymer** [comment]
I realised I have been reading the `error counts` column incorrectly. So I understand that `5p_a2` is skipped due to having more errors than the next left-most adapter (`5p_a3`). 

So I guess now my question would be: 
Is there a way to make it trim all the possible adapters, regardless of error rate?

**Comment by marcelm** [comment]
With the commandline, it’s a bit hard to express this type of read layout.

I think the only way to enforce the order in which adapters need to appear in the read is to run multiple Cutadapt process one after the other, one for each 5' adapter, instead of using `--times N`. This way, you can enforce that `5p_a1` must come first, then `5p_a2` etc. You would then need to parse multiple info files, though.

If you know how to program Python, another option would be to write some code that uses Cutadapt’s alignment routines directly. Cutadapt does not yet offer a stable API at the moment, but you could just restrict yourself to a certain Cutadapt version (1.13 is rather old, by the way). I could give you some example code if that is an option.

**Comment by awgymer** [comment]
Yeah, in general I'm able to achieve everything I want through the commandline and it's an incredibly useful tool. However this application is me somewhat abusing the software to detect possible cut sites rather than actually doing any removal. 

Ideally I would return just the first 8 (or n) leftmost matches in the sequence, regardless of number of errors (assuming they are below the cutoff). 

My brief study of the code had me considering some alternative to the `_best_match` method of `AdapterCutter`? 

Something like `_first_last_match` which used the `rstart`/`rstop` attribute of the `Match` to pick either the leftmost or rightmost match?

Some logic along the lines of:
`if best_match is None or match.rstop < best_match.rstop:`  to give you the first match

**Comment by marcelm** [comment]
I have very limited time this week, so just a brief note: There’s no way to tell the alignment algorithm to find all matches or even the rightmost one at the moment. You’d have to find the leftmost one, trim it, and repeat the process in order to enumerate all occurrences.

Oh, or you could reverse both sequence and adapter and then you would get the rightmost occurrence ...

I was originally thinking about using the `Aligner` directly, but perhaps the `AdapterCutter` could be coaxed into doing what you want.

Sorry for not being more helpful at the moment; I’ll try to get back next week, but ping me if I don’t.

**Comment by awgymer** [comment]
> You’d have to find the leftmost one, trim it, and repeat the process in order to enumerate all occurrences.
Yes this was the way I was considering doing it. It actually seems like a very simple addition, although I haven't run any comprehensive testing. 
For now I have added a `trim-first` `--action` and am rerouting the cutter from `_best_match` to `_first_match` (really it's leftmost but that is essentially first). 

```
first_match = None
for adapter in self.adapters:
    match = adapter.match_to(read)
    if match is None:
        continue
    if first_match is None or match.rstop < first_match.rstop:
        first_match = match
return first_match
```

For now I can get all the positions I want by treating 5 prime and 3 prime adapters as 5 prime and running with a large `--times`

Since I do not require the output sequences and only the info-file the fact this leaves me with just a small section of sequence is fine. 

I think the question for me now is whether it is worth my time to try and implement this behaviour more fully and push it, or whether it's not functionality your interested in and I should just fork?

**Comment by marcelm** [comment]
At the moment, I think that this is a somewhat special operation that is possibly only useful for you, so it may make more sense that you keep this in a fork. However, you didn’t say what type of experimental setup this is and why the data is structured this way, so perhaps this is actually a more common thing to do. (If you cannot tell me because it’s secret, that’s fine of course.)

Here are my thoughts anyway on an implementation of such a feature. It appears to me that this could be added as an option that one would use instead of `--times`, which would try to find all the provided adapters from left to right, in order, in each read. Perhaps `--find-all` or similar. Then the question would be what happens if one of the adapters cannot be found or the order in which adapters occur is incorrect.

Also, this mode of operation would be a bit inconsistent in relation to the others because the primary output would be the info file and the reads would be uninteresting.

Implementing this as an alternative `--action` is of course fine if it works for you, but I wouldn’t be too happy about this in a PR because the `--action` functionality is orthogonal, that is, I want to be able to specify this independently to something like a `--find-all` option.

So overall, as I said, this is probably too specialized of a feature, but on the other hand, it would really be a perfect use case for an API. So perhaps I should get started on that ... (if I had time).

**Comment by awgymer** [comment]
Thanks for your thoughts. I can expand a little on the use-case I think. Basically, I am looking at primer sequences used for PCR amplifications. There are multiple primers used and which one binds can be uncertain. I am looking to identify all possible primer options, and where they would be trimmed by cutadapt, in a reference database, so that when I am later identifying my sequences I know that I got exactly what I would expect based on the primers used. 

That may all sound a little confusing but I can promise it's a sensible option in my case. I like the idea of a `--find-all` and I agree with all your points about it not fitting with an `--action`. I just used the quickest and most obvious solution to me. If you have an idea of where/how one might adapt it to a `--find-all` I'd be happy to give that a go and put it in a fork which may or may not be reincorporated at some point.

I'm not sure I understand the problem of the order in which the adapters occur or aren't found. At least, with the implementation via `AdapterCutter` it doesn't seem to be a huge issue (I may be totally misunderstanding some of the code?). You simply get the leftmost adapter every time and if there are none your info-file will show that (In my use-case it's a possibility). Currently the biggest drawbacks I have are needing to set a large `--times` to ensure I capture all possible occurrences, and then having to do some wrangling of the start/stop coords in the info-file to give you the actual coordinates for any adapter after the first one.

**Comment by marcelm** [comment]
I guess I would try to add a new “Modifier” to `modifiers.py` that looks similar to AdapterCutter, but implements the new behavior. Regarding the order, I would just like to know what the behavior is if the reads don’t look as expected: Let’s say you want to find adapters A B C and you assume they occur in that order in the read. What should the output be if the read contains them in the order A C B? What if the order is A C B C: do you pick the second C to make the order as expected? It would be nice if this were explained in the documentation.

I may not be able to get back to you on this until after the holidays.

**Comment by awgymer** [comment]
Ah ok, I think I understand what your query is now. 

So the assumption is that I don't actually know the order the adapters occur in, or at least I may not. 
Part of the reason for performing this step is that, assuming we expected to see `A B C`  in the `A C B C` scenario we want to know that actually `C` could also trim there. So the intention would be that it would detect as many as possible by default I suppose , with `--times` in this case acting as a sort of limiter to enhance speed. 

In reality, I know roughly how many times I expect the adapter sequences to occur (once per adapter) but not how many of the sites are actually present (i.e. 2 out of 4 adapters v all 4). 

I will take some time over the holidays to play with some sort of Modifier class then, and see if I can come up with something which seems like it might be useful to more than just me.

**Comment by awgymer** [comment]
So I made a copy of the `AdapterCutter` modifier which just implements a `_first_match` rather than `_best_match`. Then I realised I have no idea how to allow it to output essentially two info-files, because all the other modifiers which can be used in conjunction with `AdapterCutter` don't have any output like that. 
I was also wondering about this from `Ideas/To Do` docs:

> Use parentheses to specify the part of the sequence that should be kept

and whether it was something you were currently working on?

**Comment by marcelm** [comment]
Let me take the easy part first:

> > Use parentheses to specify the part of the sequence that should be kept
> 
> and whether it was something you were currently working on?

No, not right now.

Regarding the info file: You’re right that the `AdapterCutter` itself doesn’t output the info file directly (perhaps that would be a better design; I don’t know). The idea is that the `AdapterCutter` only creates a list of matches, which is then later passed to the `InfoFileWriter` (in `filters.py`), which in turn prints one line for each of the matches in that list to the info file.

Each `Match` knows which adapter was matched at which position and against which read. The list of matches is structured "hierarchically": The first match is relative to the full read, the second is relative to a version of the read in which the first match has been trimmed, and so on. If `--times=n` was given, the length of the `matches` list is at most *n*.

It appears to me that you could just use the existing `InfoFileWriter`: Just Make sure that the list of matches that your custom `AdapterCutter` produces is sorted by position (left to right), and then the info file should contain the information you need.

As an alternative if you think the info format is too annoying to parse for this use case, you could implement a new `InfoFileWriter`, but you could still use the same list of matches to pass the information into it.

**Comment by marcelm** [comment]
Ok, another thought: You could actually skip `_best_match` entirely. If I understand correctly, you just want to know, for each adapter, where it occurs in the read. You can do this within `AdapterCutter.__call__`: Iterate over the adapters, match each against the (full) read and if a match was found, append it to your list of matches. Finally, sort the list of matches by start coordinate.

This would only work if you are fine with finding each adapter only at most once.

**Comment by awgymer** [comment]
I can't see myself submitting a pull request relating to this anytime soon. Close this issue?

**Comment by marcelm** [comment]
I’m closing this now as you suggested, but I’m adding it to my long-term to-do list (whatever that means).
