### ISSUE TITLE
Installing cutadapt in CentOS

### ISSUE THREAD

**Issue by akfourth** [marcelm/cutadapt#346]
Hello,

 I am using CentOS 7, and trying to install Cutadapt system-wide. I have python 2.7.5, and am trying to install the latest cutadapt (1.18). I used :

sudo pip install cutadapt

It finished without any errors. However, now I cannot use cutadapt without sudo. So if I just put 
cutadapt --help
the output is - 

Traceback (most recent call last):
  File "/usr/local/bin/cutadapt", line 7, in <module>
    from cutadapt.__main__ import main
  File "/usr/lib64/python2.7/site-packages/cutadapt/__main__.py", line 68, in <module>
    from xopen import xopen
ImportError: No module named xopen

If instead I do 
sudo cutadapt --help 
I get the correct output. 

Could you please let me know what the problem could be and how I can fix it so I can use just 'cutadapt' and it can be available to all users system-wide ? Thanks!

**Comment by marcelm** [comment]
Can you please run this command and paste the output here:
```
sudo python -c 'import xopen; print xopen.__file__'
```

**Comment by akfourth** [comment]
The output is:

/usr/lib/python2.7/site-packages/xopen.pyc

**Comment by marcelm** [comment]
Weird, the error message in your first post indicates that cutadapt was installed to `/usr/lib64/`, but `xopen`, which should have been installed at the same time as cutadapt because it is a dependency, seems to have been installed to `/usr/lib`. Perhaps this is a CentOS thing, but I am not familiar with it.

Please remove the current installation first with `sudo pip uninstall cutadapt`. Then you can try these commands to install cutadapt with the help of a virtual environment:
```
sudo virtualenv -p python2.7 /usr/local/cutadapt
sudo /usr/local/cutadapt/bin/pip install cutadapt
cd /usr/local/bin/
sudo ln -s ../cutadapt/bin/cutadapt
```

**Comment by akfourth** [comment]
Thank you so much !! That seemed to work. I now get the correct output when I run
cutadapt --help 
Hopefully all users will be able to use it as well.
