### ISSUE TITLE
fastq first and third lines

### ISSUE THREAD

**Issue by EEPuckett** [marcelm/cutadapt#349]
Dear Dr. Martin,

I'm trying to use cutadapt to demultiplex samples while removing adapters and am following the tutorial for the demultiplexing section.  I'm using cutadapt v1.18 and python 3.6.7.  My command line parameters were: 

cutadapt -b index10=CCGGTAC -b index11=AACTCCG -b index12=TTGAAGT -o trimmed-
{name}_R1.fastq.gz -p trimmed-{name}_R2.fastq.gz file_R1.fq.gz file_R2.fq.gz

I received the following error message: 
Processing reads on 1 core in paired-end legacy mode ...
cutadapt: error: At line 3: Sequence descriptions in the FASTQ file don't match ('HS1:109:C01CCABXX:3:1101:1429:2188/1' != 'file HS1:109:C01CCABXX:3:1101:1429:2188 length=100').
The second sequence description must be either empty or equal to the first description.

On an older message board (http://seqanswers.com/forums/archive/index.php/t-6936.html) I saw that if you modify the seqio.py file then you bypass this error if the first and third lines of the fastq file are not the same.  I tried that with the current version of cutadapt, specifically changing the second_header=True to second_header=False.  However, I still receive the error message when I run cutadapt.  Do you have other solutions for a work-around?

With thanks,
Emily

**Comment by marcelm** [comment]
Hi Emily,

the Seqanswers thread is quite old, and the advice given there no longer applies because the code for reading FASTQ files in `seqio.py` isn’t used anymore in the current version. Instead, the Cython code in `_seqio.pyx` is used. Modifying this would require re-compiling the module.

I would suggest instead that you fix the input FASTQ file. You can use a command like this to remove the sequence descriptions from the third line in each record (run it on both R1 and R2):
```bash
zcat input.fastq.gz | awk 'NR%4==3{$0="+"};1' | pigz > fixed.fastq.gz
```
Would that be good enough for you?

I may consider adding some kind of `--ignore-broken-fastq` option as well, but I don’t have the time for that at the moment.

**Comment by EEPuckett** [comment]
Yes, this is very helpful.  Thank you.
