### ISSUE TITLE
Quality trimming with minimum read length equal to read length throws away most reads

### ISSUE THREAD

**Issue by adrianreich** [marcelm/cutadapt#352]
cutadapt version 1.18, python version 3.6.3 installed on cluster (unknown method)

I have 80bp PE reads and would like to do quality/adapter trimming, but only retain reads that are still 80bp long after trimming (keep best of the best). Below is the command as well as the reported output. The issue that I am seeing is that the number of reads identified as having been quality trimmed is way, way lower than the number of reads that were thrown out as too short.

Command line parameters: -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT -j 16 --max-n 0.1 -m 80 --nextseq-trim=20 -o SubsetTest_R1.pair.trim.fastq.gz -p SubsetTest_R2.pair.trim.fastq.gz SubsetTest_R1.fastq.gz SubsetTest_R2.fastq.gz
Processing reads on 16 cores in paired-end mode ...
Finished in 1.77 s (18 us/read; 3.38 M reads/minute).

=== Summary ===

Total read pairs processed:            100,000
  Read 1 with adapter:                   2,932 (2.9%)
  Read 2 with adapter:                   3,764 (3.8%)
Pairs that were too short:              61,744 (61.7%)
Pairs with too many N:                      21 (0.0%)
Pairs written (passing filters):        38,235 (38.2%)

Total basepairs processed:    16,000,000 bp
  Read 1:     8,000,000 bp
  Read 2:     8,000,000 bp
Quality-trimmed:                 201,764 bp (1.3%)
  Read 1:        66,286 bp
  Read 2:       135,478 bp
Total written (filtered):      6,117,600 bp (38.2%)
  Read 1:     3,058,800 bp
  Read 2:     3,058,800 bp

If I run the exact same set of reads but lower the minimum read length (80 to 50), many more are retained...

Command line parameters: -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT -j 16 --max-n 0.1 -m 50 --nextseq-trim=20 -o SubsetTest_R1.pair.trim.fastq.gz -p SubsetTest_R2.pair.trim.fastq.gz SubsetTest_R1.fastq.gz SubsetTest_R2.fastq.gz
Processing reads on 16 cores in paired-end mode ...
Finished in 3.24 s (32 us/read; 1.85 M reads/minute).

=== Summary ===

Total read pairs processed:            100,000
  Read 1 with adapter:                   2,932 (2.9%)
  Read 2 with adapter:                   3,764 (3.8%)
Pairs that were too short:               1,303 (1.3%)
Pairs with too many N:                      48 (0.0%)
Pairs written (passing filters):        98,649 (98.6%)

Total basepairs processed:    16,000,000 bp
  Read 1:     8,000,000 bp
  Read 2:     8,000,000 bp
Quality-trimmed:                 201,764 bp (1.3%)
  Read 1:        66,286 bp
  Read 2:       135,478 bp
Total written (filtered):     15,631,494 bp (97.7%)
  Read 1:     7,824,861 bp
  Read 2:     7,806,633 bp

Here's the kicker, if I look at the length of all of the trimmed reads in the first run (-m 80) all reads are 80bp long as expected:
Count   Length
38235   80

When I look at the read lengths of all of the trimmed reads in the second run (-m 50), they are all at least 50bp, but most are 80bp! Why is it that in the first command, I only get 38K reads but in the second run, there are 64K reads that are 80bp long? Any help would be greatly appreciated and thank you.
Count   Length
4       50
6       51
8       52
3       53
4       54
3       55
8       56
10      57
18      58
21      59
18      60
11      61
15      62
26      63
21      64
29      65
30      66
25      67
41      68
44      69
67      70
83      71
120     72
182     73
336     74
737     75
1779    76
3413    77
6895    78
20752   79
63940   80

**Comment by adrianreich** [comment]
And if I set -m to 79, I recover almost 50% more reads that are 80bp long (53K reads are 80bp long, 17K are  79bp long). With -m 79, there are ~70k reads that are 79-80bp long, with -m at 50, there are ~84K reads at 79-80bp.

**Comment by marcelm** [comment]
Hi and thanks for using cutadapt.

> The issue that I am seeing is that the number of reads identified as having been quality trimmed is way, way lower than the number of reads that were thrown out as too short.

Are you referring to this part of the statistics:
```
Total basepairs processed: 16,000,000 bp
[...]
Quality-trimmed: 201,764 bp (1.3%)
```
Perhaps this could be made clearer in the output, but note that the figure 1.3% is relative to the total number of *basepairs* in the input – it is not the percentage of reads that were trimmed. The number of reads that were quality-trimmed is not included in the report as I consider it not very helpful to know in the typical case.

Does that explain the discrepancy you have seen? I can try to make the output a bit clearer, but as some tools parse Cutadapt’s report, I’ll wait for this until I can do some other changes in one go.

I don’t know what your application is, but my suggestion would be to reconsider the strict minimum-length filter. Throwing away an otherwise perfectly good read just because a couple of bases were quality-trimmed sounds quite wasteful! As you probably know, sequencing quality decreases towards the 3' end and if a few bases towards that end are of low quality, the others preceding it are very likely  still good. You could perhaps increase the quality-trimming threshold a bit, but that is another tradeoff where you could end up throwing away many good bases.

> When I look at the read lengths of all of the trimmed reads in the second run (-m 50), they are all at least 50bp, but most are 80bp! 

This could be because a read pair is considered to be too (and filtered) if at least one of the reads is too short. So if the lengths are 79 bp and 80 bp, the read is thrown away (when using `-m 80`). See also the documentation for `--pair-filter`.

**Comment by adrianreich** [comment]
Thank you for your response. Normally I never trim reads in such a manner but the downstream tool I am using requires all reads to be of the same length. Thank you for the reminder about the --pair-filter. When I went back to the reads, I was analyzing the forward read but was not taking into account the reverse read. Looking at it again, it all makes sense.
My new solution is to still filter for quality and adapters but use the --length option and trim up to 5bp off of each read. Since the order of operations is quality, adapter, then shortening, I will be able to preserve most of the read length (75 of 80bp) and most of the reads (~95%) so it's only about an 11% loss of total bps instead of 60+%. Thank you again.

**Comment by marcelm** [comment]
Great, glad I was able to help. Using `--length` sounds like the right way to approach this.
