### ISSUE TITLE
demultiplexing paired end CASAVA format

### ISSUE THREAD

**Issue by Meha44** [marcelm/cutadapt#353]
Hi Friends,
I understood I have to use Cutadapt plugin to demultiplexe in Qiime2. 

**I used this command:**
qiime cutadapt demux-paired \
>   --i-seqs MultiplexedPairedEndBarcodeInSequence \
>   --m-forward-barcodes-file metadata.tsv \
>   --m-forward-barcodes-column StaggerandBarcode \
>   --o-per-sample-sequences demultiplexed-seqs.qza \
>   --o-untrimmed-sequences untrimmed.qza \
>   --verbose

**But it gave error:**
Usage: qiime cutadapt demux-paired [OPTIONS]
Try "qiime cutadapt demux-paired --help" for help.

So what is the problem? What should I do? Why it does not work?
Thank you!

**Comment by Meha44** [comment]
newly I got this error!
qiime cutadapt demux-paired \
>   --i-seqs LibAImported.qza \
>   --m-forward-barcodes-file metadata.tsv \
>   --m-forward-barcodes-column StaggerandBarcode \
>   --o-per-sample-sequences demux_paired.gza \
>   --o-untrimmed-sequences untrimmed.gza
Plugin error from cutadapt:

  Parameter 'seqs' received an argument of type SampleData[PairedEndSequencesWithQuality]. An argument of subtype MultiplexedPairedEndBarcodeInSequence is required.

Debug info has been saved to /tmp/qiime2-q2cli-err-a121eqfm.log
(qiime2-2019.1) mpi@LIN8041:~/16Simported$

**Comment by marcelm** [comment]
Hi, can you please report this to the developers of the QIIME Cutadapt plugin? This repository is for Cutadapt only, and the error messages you are getting come from the QIIME plugin, not from Cutadapt itself. Their repo is at https://github.com/qiime2/q2-cutadapt .

I’m closing the issue for now, please get back to me if it turns out that this is a bug in Cutadapt!
