### ISSUE TITLE
Separating pooled primers

### ISSUE THREAD

**Issue by aimzvdr** [marcelm/cutadapt#364]
Hi there

I am fairly new to cutadapt, running it on a hpc and the version that is loaded is cutadapt/1.16-gimkl-2017a-Python-3.6.3.

While I am waiting for this to be updated I am trying to still test the code, as I see it will not differ too much between versions.

I have demultiplexed fastq files, however each file still contains two primer sets that were pooled. I am trying to filter the primers - a pair at a time, each time from my demultiplexed files. Firstly, is it possible to retain ONLY the trimmed sequences?

So far I have two codes I am trying- the both are doing a loop treating the forward and reverse as single reads and the other is treating it as paired end reads.

Single reads:

```
#Directories
DATADIR='/Test/Extracted'
Output='/Test2'
PrimerF='AGGGCAAKYCTGGTGCCAGC'
PrimerR='GRCGGTATCTRATCGYCTT' 
mkdir $Output/removed_primers

for i in $DATADIR/*_R1_001.fastq
do
R1=$i;

#replace "_R1_" with "_R2_" to get R2 file name
R2=${R1%_R1_001.fastq}_R2_001.fastq;

SAMPLE1=`basename ${R1%.fastq}`;
SAMPLE2=`basename ${R2%.fastq}`;


echo "processing $fqfileR1"
cutadapt \
-a $PrimerF \
--no-indels \
-e 0 \
--discard-untrimmed \
-o $Output/removed_primers/%$SAMPLE1.fastq \
$R1

echo "processing $fqfileR2"
cutadapt \
-a $PrimerR \
--no-indels \
-e 0 \
--discard-untrimmed \
-o $Output/removed_primers/%$SAMPLE2.fastq \
$R2

done
```

This seems to work fine, but when I try to import it into Qiime I get an error that the output cannot be read as a fastq file. 

> Qiime error: q2-SingleLanePerSamplePairedEndFastqDirFmt-2932vc8m/CR11_3_L001_R1_001.fastq.gz is not a(n) FastqGzFormat file
> 
> HOWEVER, CR11_3_L001_R1_001.fastq.gz is not the output file that is in that directory... 
> This is cutadapt 1.16 with Python 3.6.3
> Command line parameters: -a AGGGCAAKYCTGGTGCCAGC -A GRCGGTATCTRATCGYCTT --no-indels -e 0 --discard-untrimmed -o Test2/removed_primers/%CR11_S83_L001_R1_001.fastq -p removed_primers/%CR11_S83_L001_R2_001.fastq Test/Extracted/CR11_S83_L001_R1_001.fastq Test/Extracted/CR11_S83_L001_R2_001.fastq
> Running on 1 core
> Trimming 2 adapters with at most 0.0% errors in paired-end mode ...
> Finished in 7.35 s (22 us/read; 2.69 M reads/minute).

=== Summary ===

Total reads processed:                 329,471
Reads with adapters:                       171 (0.1%)
Reads written (passing filters):           171 (0.1%)

Total basepairs processed:    96,760,386 bp
Total written (filtered):         12,358 bp (0.0%)

=== Adapter 1 ===

Sequence: GRCGGTATCTRATCGYCTT; Type: regular 3'; Length: 19; Trimmed: 171 times.

No. of allowed errors:
0-19 bp: 0

Bases preceding removed adapters:
  A: 3.5%
  C: 7.6%
  G: 2.3%
  T: 11.1%
  none/other: 75.4%

=== Summary ===

Total reads processed:                 329,471
Reads with adapters:                       377 (0.1%)
Reads written (passing filters):           377 (0.1%)

Total basepairs processed:    96,535,222 bp
Total written (filtered):         52,385 bp (0.1%)

=== Adapter 1 ===

Sequence: AGGGCAAKYCTGGTGCCAGC; Type: regular 3'; Length: 20; Trimmed: 377 times.

No. of allowed errors:
0-20 bp: 0

Bases preceding removed adapters:
  A: 3.4%
  C: 17.5%
  G: 18.6%
  T: 7.2%
  none/other: 53.3%

Paired end:

```
#Directories
DATADIR='/Test/Extracted'
Output='/Test2'
PrimerF='AGGGCAAKYCTGGTGCCAGC'
PrimerR='GRCGGTATCTRATCGYCTT' 
mkdir $Output/removed_primers

for i in $DATADIR/*_R1_001.fastq
do
R1=$i;

#replace "_R1_" with "_R2_" to get R2 file name
R2=${R1%_R1_001.fastq}_R2_001.fastq;

SAMPLE1=`basename ${R1%.fastq}`;
SAMPLE2=`basename ${R2%.fastq}`;

cutadapt -a $PrimerF -A $PrimerR --no-indels -e 0 --discard-untrimmed -o $Output/removed_primers/%$SAMPLE1.fastq -p $Output/removed_primers/%$SAMPLE2.fastq $R1 $R2


done
```

This doesn't work, all sequences are removed.

`
=== Summary ===

Total read pairs processed:            329,471
  **Read 1 with adapter:                     377 (0.1%)
  Read 2 with adapter:                     171 (0.1%)**
Pairs written (passing filters):           120 (0.0%)

Total basepairs processed:   193,295,608 bp
  Read 1:    96,535,222 bp
  Read 2:    96,760,386 bp
**Total written (filtered):              0 bp (0.0%)
  Read 1:             0 bp
  Read 2:             0 bp**

`

Is it possible to filter reads, remove the primers and thus keep these sequences? If so, can you advise me where I may be going wrong? As I would think treating them as single or paired should not necessarily make much of a difference in the output...

Any advice/suggestions would be appreciated.

Many thanks
Aimee

**Comment by marcelm** [comment]
It appears that even the first command you tried did not work because the report says that the primer sequence was only found in 0.1% of all reads.

Can you please clarify how your reads are structured? In particular, I wonder where exactly the primers are located within the read. How many primers do you have in total? The code above lists two primer sequences, but you also say that you have two primer sets that were pooled, so I guess there are actually four primers in total (two forward, two reverse). I wonder also if you should actually use a [linked adapter](https://cutadapt.readthedocs.io/en/stable/guide.html#linked-adapters).

Cutadapt is very flexible in which type of adapters it can find and remove, but that also means you will have to know exactly what you want to do with the reads.

Did you read the [section in the documentation about adapter types](https://cutadapt.readthedocs.io/en/stable/guide.html#adapter-types)?

A couple more suggestions:

* You should definitely use the paired-end mode. Otherwise, forward and reverse reads will no longer be synchronized when you use any of the filtering options in Cutadapt (such as `--discard-untrimmed`).
* In your paired-end command, using `--discard-untrimmed` actually means: “Throw this read pair away if no adapter could be found in R1 *or* no adapter could be found in R2“. So only those read pairs will be kept that have both adapters. See [the documentation](https://cutadapt.readthedocs.io/en/stable/guide.html#filtering-paired-end-reads).
* Do not use `-e 0`, at least initially. Allowing errors will not only take care of sequencing errors, but would also allow you to find out whether you mistyped the adapter/primer sequence (the report would then show many matches at 1 error).

I am guessing that are trying to run Cutadapt to first find the one primer set, want to throw away all the reads without that primer, and then would want to run Cutadapt a second time to do the same for the second primer set. If that is correct, then you won’t actually have to do that. You could use two linked adapters, one for each primer set, and then let Cutadapt demultiplex the output into two file pairs. I’ll be happy to show you how to do that, but would first need to know whether the data you have is actually like this.

**Comment by aimzvdr** [comment]
Hi @marcelm 

Thanks for the speedy response, much appreciated.

So first off:

> You could use two linked adapters, one for each primer set, and then let Cutadapt demultiplex the output into two file pairs. I’ll be happy to show you how to do that, but would first need to know whether the data you have is actually like this.

I read about this, but decided not to pursue this option until I understood what I was doing wrong. I also thought it was not an option for the type of data by the explanation I had read in the docs.

I do have two primer pairs - one for COI  and another for 18S. The primers should be located at the front of the sequences. It should have been ADAPTERPRIMERSEQUENCE and since it has been demultiplexed it is now just PRIMERSEQUENCE.

So this is exactly what I am trying to achieve:

> I am guessing that are trying to run Cutadapt to first find the one primer set, want to throw away all the reads without that primer, and then would want to run Cutadapt a second time to do the same for the second primer set. 

I have uploaded a subset of the fastq files - https://drive.google.com/drive/folders/1SZrNdwicvUCWMCWPWrMEWhS031ygDb_5?usp=sharing - I am trying to work with, the number of sequences for each sample for each primer pair varies greatly. I have previously run this data, but I would very much like to switch to cutadapt in the future for my 'depooling' and so I do have results they can be compared to once I run them through my Qiime pipeline. 

Primers I am using:
18S_Forward: AGGGCAAKYCTGGTGCCAGC
18S_Reverse: GRCGGTATCTRATCGYCTT
COI_Forward: GGWACWGGWTGAACWGTWTAYCCYCC
COI_Reverse: TAIACYTCIGGRTGICCRAARAAYCA

Please let me know if there is any other information you need.

Cheers and many thanks
Aimee

**Comment by marcelm** [comment]
Ok, thanks for the data. I looked only at the first two files, but I understand now how your data is structured. Here is how I would run Cutadapt to split a dataset into two according to which primer it contains, removing the primer in the process (some line breaks added for readability):
```
mkdir demultiplexed
cutadapt
    -g COI=^GGWACWGGWTGAACWGTWTAYCCYCC
    -g 18S=^AGGGCAAKYCTGGTGCCAGC
    -G COI_RC=^TANACYTCNGGRTGNCCRAARAAYCA
    -G 18S_RC=^GRCGGTATCTRATCGYCTT
    -o demultiplexed/CR11_{name}_R1.fastq
    -p demultiplexed/CR11_{name}_R2.fastq
    CR11_S83_L001_R1_001.fastq
    CR11_S83_L001_R2_001.fastq
```
(Add `--discard-untrimmed`, `-e`, `--no-indels` etc. as you think appropriate.)

I replaced the `I` characters in your 18S_Reverse sequence with `N` because `I` is not (as far as I know) a IUPAC code for nucleotides.

Note that I used anchored 5’ adapters (option `-g` and a `^` at the beginning of the adapter sequence) because your primer is always at the 5’ end. (The `-a` option is for specifying 3’ adapters and would trim the primer and everything that follows, thus leaving a zero-length read.)

You are correct that linked adapters won’t work here as these are intended to be used when one of the reads (R1 or R2) contains two adapters, not when there is one adapter in R1 and one in R2. You can still provide the adapters separately (with `-g` and `-G`) as I did above.

There is a small problem with this (which I think you can ignore): As criterion for demultiplexing, Cutadapt will use only the information of which adapter it found in R1. The other read will still be trimmed correctly, but the information that your COI_Forward sequence on R1 should always occur together with a COI_Reverse sequence on R2 is not taken into account. Thus, read pairs in which the wrong combination of primers is found (e.g. COI_Forward on R1 and 18S_Reverse on R2) will not be filtered out. I don’t think it is an issue here, but if you would like to have this feature, follow the discussion in issue #347 (about a `--pair-adapters` option).

**Comment by aimzvdr** [comment]
Awesome!

Thanks for this will give it a run 👍

**Comment by marcelm** [comment]
I think this has been taken care of. Note that a `--pair-adapters` now exists as well.
