### ISSUE TITLE
Desyncing of paired-end reads

### ISSUE THREAD

**Issue by TonyKess** [marcelm/cutadapt#375]
I'm using cutadapt on paired-end RAD data from the bestRAD protocol: https://github.com/WhiteheadLab/Bench_Protocols/blob/master/BestRAD-Illumina-prep.md

Prior to demultiplexing in stacks I am using cutadapt to trim off the leading 2 bases from my reads, and removing repetitive sequence identified in fastqc. After demultiplexing of trimmed reads, I get the following error when I align my reads to a reference genome in bwa mem:

[mem_sam_pe] paired reads have different names: "489_7_1208_10581_48597", "489_7_1208_8430_48597"

This problem does not occur when I do not include adapter trimming flags in cutadapt.  Any idea why this is happening? 

I am working with python 2.7.3 and cutadapt 1.18 on a large cluster, and  python  3.6.3 and cutadapt 1.5 on a personal Mac (OSX 10.12.6)

The code I am using:

```
ls HI*R1*  |  sed 's/_R1.fastq.gz//'| \
 parallel ' ~/Desktop/cutadapt/cutadapt \
  --cut 2 \
 -a TCGGAAGAGCACACGTCTGAACTCCAGTCACCGATGTATCTCGTATGCCG \
 -a TCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTA \
 -o {}_R1_adaptrim.fastq \
 -p {}_R2_adaptrim.fastq \
 {}_R1.fastq.gz \
 {}_R2.fastq.gz'
```

**Comment by marcelm** [comment]
Cutadapt should never produce desynchronized paired-end files.

Can you please double-check the paired-end data that Cutadapt produces, that is, *before demultiplexing*?  Run `cutadapt -o /dev/null -p /dev/null sample_R1_adaptrim.fastq sample_R2_adaptrim.fastq`. This will just read in the file and check whether the reads are paired correctly. Then run the same command on the demultiplexed data. If it fails, the demultiplexing step is the problem.

Also, you may want to check that the `parallel` command works as you expect. Potentially you’re writing to a single output files more than once. You can easily do this by running `echo` instead of `cutadapt` within the command that you give to parallel.

**Comment by TonyKess** [comment]
Thanks for the quick feedback - I've checked running cutadapt on the trimmed reads and they appear to be correctly paired. The demultiplexing step in stacks may instead be the problem:  when I run the   read check in cutadapt on demultiplexed reads they are mis-paired in some files.

**Comment by jgbarnes** [comment]
Do you know how gracefully Stacks handles read pairs where one read direction is empty (but still present in the FASTA/Q)? After trimming, this might be happening and if Stacks isn't being clever, it may become desynchronized. If this is the culprit, try adding in a PE minimum length (of 1) filter to your Cutadapt command.

**Comment by TonyKess** [comment]
Thanks for this suggestion - the minimum length filter (I set   --minimum-length 90) solved the problem. The process_radtags module in Stacks was having trouble with retained reads of 0 length, which is where the de-syncing was happening.
