### ISSUE TITLE
IUPAC support issue

### ISSUE THREAD

**Issue by RoelKluin** [marcelm/cutadapt#379]
It seems that the IUPAC 'S' clipping does not work as should. I am trying to remove G's and C's at the start of the read, although the log indicated some trimming, the output still contains reads starting with G's.

cutadapt version 2.3
python-3.7.3
installed via conda.

```
cutadapt --quality-base=33 -O 7 -e 0.15 -m 20 -q 5 \
-g "^SSSSSSSSSSSSSSSSSSSS;max_error_rate=0.1;min_overlap=1" \
-a GATCGGAAGAGCACACGTCTGAACTCCAGTCAC \
  ${in_fastq}
```

It seems to be due to the anchoring. Example:

```
@XXX:2:2207:1408:1984 1:N:0:ACAGTG
GGGGGTACAGTGAAACTGCGAATGGCTCATTAAATCAGTTATGGTTCCTTTGGTCGCTCGCTCCT
+
BCCCCGGGGGGGGGGEGGGGGGGGGGGGGGGEGGGGGGGGEC>1FGEGGGDGGGDGGGGDGGGG@
```
I'd expect something like this
```
@XXX:2:2207:1408:1984 1:N:0:ACAGTG
TACAGTGAAACTGCGAATGGCTCATTAAATCAGTTATGGTTCCTTTGGTCGCTCGCTCCT
+
GGGGGGGGGGEGGGGGGGGGGGGGGGEGGGGGGGGEC>1FGEGGGDGGGDGGGGDGGGG@
```

**Comment by marcelm** [comment]
Yes, this is due to the anchoring. In short, try to use `-g XS{20}` instead.

Writing `S{20}` is a shorthand for writing 20 `S` characters. Anchoring the 5' adapter with `^` will require the read to begin with the adapter sequence, that is, the read will only be trimmed if it starts with exactly 20 G or C nucleotides.

**Comment by RoelKluin** [comment]
thank you I will try.
