### ISSUE TITLE
xopen backwards compatibility issue.

### ISSUE THREAD

**Issue by jkbaumohl** [marcelm/cutadapt#384]
Hello cutadapt developers,

I work on the KBase project and we have wrapped cutadapt app within KBase.
We recently ran into an issue where cutadapt was not working due to what appears to be
an underlying xopen version issue. We are currently running cutadapt 1.18

It gave the following error message.
Collecting xopen>=0.3.2 (from cutadapt==1.18)
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading https://files.pythonhosted.org/packages/5b/3a/11a853898a86fc6d95c65e25b7e8ac6ca787852ee77b68f58aa4414f1d48/xopen-0.7.0.tar.gz
    Complete output from command python setup.py egg_info:
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    error in xopen setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers

I was able to fix the issue with adding to my DOCKERFILE
RUN pip install xopen==0.3.2

Please recognize there appears to be an incompatibility issue between xopen-0.7 and your code.  I do not know at what point this issue started, but you may want to start pinning
an xopen version number in your builds or at least add an accurate compatible version range for xopen instead of a greater than version number.

Thank you,
Jason

**Comment by marcelm** [comment]
Hi Jason,

thanks for letting me know. I was able to reproduce the problem on Ubuntu 14.04.

The problem is that the version of setuptools that you use is older than required for the installation of xopen.  I think the proper fix in your case would be to run `pip install --upgrade pip setuptools` before issuing `pip install cutadapt==1.18`.

I’m a bit reluctant to pin the version. I would have to release a version 1.18.1 for this, but Cutadapt is actually compatible with xopen 0.7. Forcing a downgrade to 0.3.2 would eliminate some speedups that were added in later versions.

Not sure what the best way forward is, but perhaps I could add a version check to xopen that will error out and recommend to run the above `pip install --upgrade` command before proceeding.

May I ask why you are still at Cutadapt 1.18?

**Comment by jkbaumohl** [comment]
Hi Marcel,
I was doing a quick fix to try an identify the problem with why it was not
building.
I tried to update the Dockerfile to cutadapt 2.3, but got a what looked
like a Python 3 issue.
Currently we are still running Python 2.7, but will have a project level
effort to switch over to using Python3 that will be starting soon.
At that point we will also try and update version of apps if we can.

Thanks,
Jason

**Comment by marcelm** [comment]
You convinced me that it’s a good idea to restrict the versions of dependecies a bit more. I’ve added stricter pinnings now.

This will of course not apply to the old 1.18 release. That one is a bit special because it’s the last release to support Python 2.7, but for now I’ve decided not make a 1.18.1 release as it’s extra work and I prefer people to switch to Python 3 anyway. I may change my mind if this issue comes up again.

Thanks for taking the time to report this issue.
