### ISSUE TITLE
Empty reads

### ISSUE THREAD

**Issue by 3nrique0** [marcelm/cutadapt#392]
Hello,

This is more a suggestion.

The minimum length of reads being default 0 lead me to have empty reads (only header and + lines) 2 being completely empty.

This caused some other programs (process_radtags) to make a Segmentation error (Core dump)
Maybe a solution would be to make a min len default 1 or 2.

This only happened with R2. R1 reads didn't showed any empty reads.

Version of cutadapt: 2.4, version of python 3.6.5. I installed cutadapt using pip and I use it in a virtual environment.

**Comment by marcelm** [comment]
I see why this may be desirable. In fact, some users have been surprised by this behavior in the past, which is why I mention this explicitly in the documention. However, there are also reasons against it.

Right now, if you don’t use filtering options, the n-th read in the output will correspond to the n-th read in the input, which I think is a desirable default behavior. I’m also sure some users rely on this, so adding a filtering step by default would be a major backwards incompatible change.

To be honest, I also think that empty reads are totally legitimate and that a program that handles FASTQ files should be able to deal with them. If a program crashes due to an empty read, please report it to the developers!

Of course it’s not always practical to get those other programs fixed, and I realize people just want to get their work done, so I wonder whether it would be helpful to print a warning when there were any empty reads in the output. However, for the moment I will likely not change the minimum length default.
