### ISSUE TITLE
File name reading problem

### ISSUE THREAD

**Issue by soluna1** [marcelm/cutadapt#398]
Hi, 

I'm having an issue with Cutadapt reading input file names. The script lists all file names and sets them as input for Cutadapt, but for some unknown reason Cutadapt can't distinguish between some file names. 
Here is the script:

```DATA_DIR=data/raw
mkdir -p data/trimmed
OUT_DIR=data/trimmed

mkdir -p data/logs/cutadapt
LOG_DIR=data/logs/cutadapt

for SAMPLE in $(ls ${DATA_DIR}/*fastq* | awk -F"/" '{print $NF}' |  sed 's/_R[1,2].*$//g' | sort -u);do
  cutadapt \
    --discard-untrimmed \
    --pair-filter=any \
    --minimum-length=${MIN_LENGTH} \
    -g ${PRIMER_F} \
    -G ${PRIMER_R} \
    -o ${OUT_DIR}/${SAMPLE}_trimmed_R1.fastq.gz \
    -p ${OUT_DIR}/${SAMPLE}_trimmed_R2.fastq.gz \
    -O ${MIN_R} \
    ${DATA_DIR}/*${SAMPLE}*_R1.fastq* \
    ${DATA_DIR}/*${SAMPLE}*_R2.fastq* \
    > ${LOG_DIR}/${SAMPLE}.log
done
```

Here the file names:
COST-8B-B7_S20_R1.fastq.gz
COST-8B-B7_S20_R2.fastq.gz
COST-E1D0_R1.fastq.gz
COST-E1D0_R2.fastq.gz
E1D0_R1.fastq.gz
E1D0_R2.fastq.gz
E2D0_R1.fastq.gz
E2D0_R2.fastq.gz
E3D0_R1.fastq.gz
E3D0_R2.fastq.gz

The problem arises with E1D0_R1 or R2 and COST-E1D0_R1 or R2. See Cutadapt output:

> cutadapt: error: You provided 4 input file names, but either one or two are expected. The file names were:
  - 'data/raw/COST-E1D0_R1.fastq.gz'
  - 'data/raw/E1D0_R1.fastq.gz'
  - 'data/raw/COST-E1D0_R2.fastq.gz'
  - 'data/raw/E1D0_R2.fastq.gz'
 Hint: If your path contains spaces, you need to enclose it in quotes
 
Should I remove "-" between COST-E1D0?

It also has happened with other similarly named files.
Any idea? 

Thanks a lot!

- Cutadapt 2.4, and Python 3.7

**Comment by marcelm** [comment]
This isn’t a Cutadapt problem at all, but let me help anyway.

The problem is that `*${SAMPLE}*` matches both `E1D0` but also `DUST_E1D0`.

You can fix this by removing the `*` before `${SAMPLE}`, but you should actually use no wildcards at all here because you only want to match a single file. It’s better to be explicit. Just iterate over all `_R1_` files and derive the other file names from them. Something like this:
```
for r1 in data/raw/*_R1.fastq.gz; do
    sample=$(basename $r1 _R1.fastq.gz)
    r2=${r1%%_R1.fastq.gz}_R2.fastq.gz
    cutadapt \
        ... \
        -o ${OUT_DIR}/${sample}_trimmed_R1.fastq.gz \
        -p ${OUT_DIR}/${sample}_trimmed_R2.fastq.gz \
        ${r1} ${r2} > ${LOG_DIR}/${sample}.log
done
```
That way, you also don’t get this problem of `*fastq*` matching both R1 and R2 files and then having to remove half of the matches again with `sort -u`.

**Comment by soluna1** [comment]
Great thanks @marcelm!!!

**Comment by marcelm** [comment]
Glad I could help!
