### ISSUE TITLE
Check reverse complement when demultiplexing

### ISSUE THREAD

**Issue by koopkaup** [marcelm/cutadapt#402]
After demultiplexing using the new combinatorial dual indexes method I compared the number of reads per sample to mothur demultiplexed samples and saw that cutadapt was able to find about 50% of reads. When I looked closer I saw that many of the forward reads in the raw file contained reverse barcodes and primer and vice versa.
This is also explained in this post https://www.biostars.org/p/244732/
But mothur has a feature to check that during demultiplexing and I have always used that https://www.mothur.org/wiki/Trim.seqs#checkorient

Is it possible to add orientation check to cutadapt as well?

**Comment by marcelm** [comment]
There is an old issue #220 about reverse complements, which would solve this. Perhaps it’s time I implement this.

**Comment by marcelm** [comment]
Similar to Mothur, I’d like to implement this by searching both the read and its reverse complement for the adapter.

In your case, if the adapter was found on the reverse complement, would you like to have the reverse-complemented (and of course trimmed) sequence in the output? Or would you prefer to have it in the original orientation?

Reverse-complementing the output would be quite nice for a use case that I have because it would allow me to “normalize” the read orientation.

I will probably implement both options, but I’d like to know how to name them and with which one to start.

Brainstorming:

 * `--reverse-complements` (and perhaps `--rc=yes` or `--revcomp` as aliases) would not modify read orientations
* `--rc-normalize`, `--normalize` or perhaps `--rc=normalize` would modify read orientations.

I could then imagine that some people would want to have an indication of whether a read has been reverse-complemented by some extra string in the header. I’m not sure how to do this. One idea is to use the `--suffix` option and allow some special string such as `{rc}` in the given suffix.

Oh, and I guess we need to count how many reads were reverse-complemented and print that in the report.

**Comment by koopkaup** [comment]
I think it makes downstream analysis easier if reverse reads were reverse complemented. Maybe make that the default option and add --norevcomp for keeping the original orientation.

**Comment by marcelm** [comment]
Let’s move the discussion over to #220, which is the earlier issue. I’ll copy the relevant parts from above.
