### ISSUE TITLE
Plugin error from cutadapt

### ISSUE THREAD

**Issue by SerenaGalie** [marcelm/cutadapt#406]
Hi all of you,

I just run cutadapt plugin in order to demultiplex my data, which consist on single-end-sequences of 49 samples contained in a unique file. I had just previously run the same script for a similar file and it worked, but now I have this error, which I cannot understand. 

Someone could help me? I have used QIIME2/2018.2 version. Now I am trying the same with QIIME2/2019.4 in case there is some problem with the plugin. 

Plugin error from cutadapt:

  Command '['cutadapt', '--front', 'file:/scratch-local/mbloemen/tmprm7o4d8p', '--error-rate', '0.0', '-o', '/scratch-                                                            local/mbloemen/q2-CasavaOneEightSingleLanePerSampleDirFmt-folivkrq/{name}.1.fastq.gz', '--untrimmed-output', '/scratch                                                            -local/mbloemen/q2-MultiplexedSingleEndBarcodeInSequenceDirFmt-m5s3wjw_/forward.fastq.gz', '/scratch-local/mbloemen/qi                                                            ime2-archive-izl35vrj/2cc054c9-525f-4181-951e-9ea0e0c5b3c6/data/forward.fastq.gz']' returned non-zero exit status -9

Thank you very much in advance!

**Comment by marcelm** [comment]
Hi, you’re using the QIIME2 plugin for Cutadapt, which is maintained in a separate repository by other people, which means I cannot help you here. Please head over to https://github.com/qiime2/q2-cutadapt and report your problem there. If it turns out that the problem is with Cutadapt itself and not the plugin, please come back here and re-open this issue (or open a new one).

(One guess: Exit status -9 means that Cutadapt has been killed by signal 9 (SIGKILL). In case you are running this on a cluster, perhaps the batch job exceeded its allocated time.)
