### ISSUE TITLE
Problems with separating paired-end reads that have no adapter, one adapter, or both reads have adapter

### ISSUE THREAD

**Issue by ozerab** [marcelm/cutadapt#408]
Hi,
I am having a problem (at least the results dont make sense to me), where I would like to use cutadapt to seperate paire-end reads into 3 categories: pairs that have no adapter (as -/-), pairs that have a single adapter on one of the read pairs (-/+ or +/-), and pairs where both read-pairs have an adapter (+/+).
I am using Cutadapt 2.5 with Python 3.6.8, which was installed with the follwoing command;
sudo python3 -m pip install --upgrade cutadapt
{Just to be clear there was an earlier version of cutadapt (ver 1.15) that was installed by "sudo apt install cutadapt" and later removed by "sudo apt uninstall cutadapt"}

So to get the -/- class I used the following command line and the results are below;
cutadapt -a CCTGCAGGTCATTACCCTGTTATCCCTAT -A CCTGCAGGTCATTACCCTGTTATCCCTAT --action=none --pair-filter=any --discard-trimmed -o X_R1_NoAdapt.fastq.gz -p X_R2_NoAdapt.fastq.gz X_R1.fastq.gz X_R2.fastq.gz

=== Summary ===
Total read pairs processed:         51,056,541
  Read 1 with adapter:              24,403,066 (47.8%)
  Read 2 with adapter:              33,467,159 (65.5%)
Pairs written (passing filters):     1,858,931 (3.6%)

The problem is when I want to get the all read-pairs that have an adapter (-/+, +/-, or +/+), I use the following command and the results are below;
cutadapt -a CCTGCAGGTCATTACCCTGTTATCCCTAT -A CCTGCAGGTCATTACCCTGTTATCCCTAT --action=none --pair-filter=any --discard-untrimmed -o X_R1_wAdapt.fastq.gz -p X_R2_wAdapt.fastq.gz X_R1.fastq.gz X_R2.fastq.gz

=== Summary ===
Total read pairs processed:         51,056,541
  Read 1 with adapter:              24,403,066 (47.8%)
  Read 2 with adapter:              33,467,159 (65.5%)
Pairs written (passing filters):     8,672,615 (17.0%)

At this stage, based on the results from the previous results I expected to get roughly 49M (=51M-2M) read-pairs in the resulting file, or at minimum 33M (based on the results of the second results). 

I would really appreciate if someone could explain what am I missing and how to correct this issue. 

Thanks a lot in advance.

**Comment by marcelm** [comment]
Hi, good question! What is confusing here is that replacing `--discard-untrimmed` is *not* the inverse of `--discard-untrimmed` when trimming paired-end reads. This should perhaps be documented a bit better, but in theory [the table in the documentation](https://cutadapt.readthedocs.io/en/stable/guide.html#filtering-paired-end-reads) mentions this.

You’re using `--pair-filter=any` (note you could leave it out since it’s the default). When used in combination with `--discard-trimmed`, this means that a read is discarded if any read (i.e., at least one of them) has an adapter. That is, -/+, +/- and +/+ are discarded, so only -/- remains. So far this is what you want.

However, using `--pair-filter=any` with `--discard-untrimmed` means "discard the pair if one of the reads is *untrimmed*". That is, -/+, +/- and -/- are discarded, leaving you with +/+.

I think you can get what in the following way. First, run Cutadapt with the `--untrimmed-output` and `--untrimmed-paired-output` options and `--pair-filter=any`. The regular output files (`-o`,`-p`) will contain the +/+ read pairs, but the `--untrimmed-output` files will contain the others, that is -/-, -/+ and +/-. Then run Cutadapt on this file again (that is, on the one that contains the -/-, -/+ and +/- read pairs), but use the `--pair-filter=both` both. Again, use `--untrimmed-(paired-)output`. This will create two more file pairs, where one of them is -/- and the other contains the +/- and -/+ read pairs.

This is what I mean (commands untested, leaving out `-a CCTGCAGGTCATTACCCTGTTATCCCTAT -A CCTGCAGGTCATTACCCTGTTATCCCTAT --action=none` for both commands):
```
cutadapt  ... \
  --pair-filter=any \
  --untrimmed-output temporary.R1.fastq.gz \
  --untrimmed-paired-output temporary.R2.fastq.gz \
  -o both-have-adapters.R1.fastq.gz \
  -p both-have-adapters.R2.fastq.gz \
  X_R1.fastq.gz \
  X_R2.fastq.gz

cutadapt  ... \
  --pair-filter=both \
  --untrimmed-output neither-have-adapters.R1.fastq.gz \
  --untrimmed-paired-output neither-have-adapters.R2.fastq.gz \
  -o exactly-one-has-adapter.R1.fastq.gz \
  -p exactly-one-has-adapter.R2.fastq.gz
  temporary.R1.fastq.gz \
  temporary.R2.fastq.gz
```

**Comment by ozerab** [comment]
Hi Marcel,
Thanks for clarifying this. I have actually done something similar; using one of the adapters I first seperated read-pairs into -/? and +/?. I then seperated them into -/- and -/+, and +/- and +/+. Just in case this helps someone else in future.
Thanks again.

**Comment by marcelm** [comment]
Ah, that’s a good idea, thanks for sharing!
