### ISSUE TITLE
error: Too many parameters. 

### ISSUE THREAD

**Issue by fedeboio** [marcelm/cutadapt#420]
Hello, 

I'm working on 16S metabarcoding paired-end Illumina MiSeq data, in particular I would like to remove the primer sequences. I am very new in bioinformatics and command-line so I apologise in advance if my question is banal. 

I've cutadapt 1.18 and Python 3.7.4. Cutadapt was installed in conda.

As I've anticipated, I have no practical experience and I'm learning as self-taught how to process my data. I am following this tutorial at the moment: https://astrobiomike.github.io/amplicon/dada2_workflow_ex

I would like to remove the primer sequences from both reverse and forward reads. Since I have 96 samples, I'd like to process all the samples using only one command. Following the above tutorial, I have created a file with all the IDs of my samples called "samples" and I then I typed:

`for sample in $(cat samples)
do

    echo "On sample: $sample"
    
    cutadapt -a ^AGAGTTTGATCCTGGCTCAG...ACTCCTACGGGAGGCAGCA  \
    -A ^TGCTGCCTCCCGTAGGAGT...CTGAGCCAGGATCAAACTCT  \
    -m 305 -M 325 --discard-untrimmed \
    -o ${sample}_R1_trimmed.fq -p ${sample}_R2_trimmed.fq \
    ${sample}*R1*.fastq ${sample}*R2*.fastq \
    >> cutadapt_primer_trimming_stats.txt 2>&1

     done`

Could you please help me understand why I get the error "Too many parameters" ? 

Thank you!

**Comment by marcelm** [comment]
I am guessing that you get the message because the `*` wildcards in the input file names don’t work as expected, and that they actually expand to more than one file name.

You can try to find the problem by temporarily replacing `cutadapt` with `echo` in your command. Also, remove the output redirection. Then running the command will simply print out the command that would have been run, and you’ll see what the extra parameters are.

Perhaps you have a sample that has nearly the same name as another sample except for some additional characters.

As an example, let’s simplify a bit and assume you have only single-end reads (with R1 in the name). Let’s say you have `sampleA2_R1_001.fastq` and `sampleA23_R1_001.fastq` in your directory. When you then set sample to `sampleA2` and use `${sample}*R1*.fastq` as input file in your command, it will match *both* files. For paired-end, the problem would be the similar, just that you would have four input files.

Note that Cutadapt 1.18 is quite old and contains some bugs that have been fixed in more recent versions.

**Comment by marcelm** [comment]
Ah, and I remember another good reason to update: Recent Cutadapt version no longer print "Too many parameters":
```
$ cutadapt Too many file names.fastq
cutadapt: error: You provided 4 input file names, but either one or two are expected. The file names were:
 - 'Too'
 - 'many'
 - 'file'
 - 'names.fastq'
Hint: If your path contains spaces, you need to enclose it in quotes
```

**Comment by fedeboio** [comment]
Thank you very much! You were right, the input file in my command was matching more than one sample. 
First of all I have upgraded cutadapt (using `pip install --user --upgrade cutadapt`), then like you suggested, I printed the commands for every sample and I realised where was the problem. I've re-named those files and run the command again and it worked, but the output files were empty :( 

I thought that maybe the problem now is due to the sequences that I've asked cutadapt to trim. I checked with my collaborator and actually I had the wrong primer sequences so I tried to run the command with the new real sequences used in our protocol:  

`for sample in $(cat samples2); do  echo "On sample: $sample"; cutadapt -a ^ACACTCTTTCCCTACACGACGCTCTTCCGATCTNNNNNAGAGTTTGATCMTGGCTCAG…CTCCTACGGGAGGCAGCAAGATCGGAAGAGCACACGTCTGAACTCCAGTCAC -A ^GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCTTGCTGCCTCCCGTAGGAG…CTGAGCCAKGACCAAACTCTNNNNNAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT -m 305 -M 360 --discard-untrimmed -o ${sample}_R1_trimmed.fq -p ${sample}_R2_trimmed.fq ${sample}*R1*.fastq ${sample}*R2*.fastq; done `

But I've got the error: Allowed placement restrictions for a 3' adapter are ADAPTERX and ADAPTER$

So I tried this: 

`for sample in $(cat samples2); do  echo "On sample: $sample"; cutadapt -a ^ACACTCTTTCCCTACACGACGCTCTTCCGATCTNNNNNAGAGTTTGATCMTGGCTCAG…CTCCTACGGGAGGCAGCAAGATCGGAAGAGCACACGTCTGAACTCCAGTCAC -a ADAPTERX GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCTTGCTGCCTCCCGTAGGAG…CTGAGCCAKGACCAAACTCTNNNNNAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT -m 305 -M 360 --discard-untrimmed -o ${sample}_R1_trimmed.fq -p ${sample}_R2_trimmed.fq ${sample}*R1*.fastq ${sample}*R2*.fastq; done`

But I've got a new error: 
cutadapt: error: unrecognized arguments: sample1_R1.fastq sample2_R2.fastq

Would you be able to tell me what I am doing wrong?

Thanks a lot

**Comment by marcelm** [comment]
Just a wild guess, before thinking about this further: In the command that you copied above, you use the character `…` (Unicode "horizontal ellipsis") instead of three full-stops/dots: `...`. They are not easily distinguishable, but Cutadapt needs the three dots. Perhaps some document editor or e-mail program converted the three dots to the single-character version? I think that would explain the message.

**Comment by fedeboio** [comment]
Correct, I didn't realised it sorry! I copied and pasted the sequences from word. 

I fixed this problem but I still get the same error :(

**Comment by marcelm** [comment]
> I fixed this problem but I still get the same error :(

You had two different commands above (and two different errors). Just to make sure that I understand you correctly: Which one did you try now and which error did you get?

**Comment by fedeboio** [comment]
Sorry, I tried this:

`for sample in $(cat samples2); do  echo "On sample: $sample"; cutadapt -a ^ACACTCTTTCCCTACACGACGCTCTTCCGATCTNNNNNAGAGTTTGATCMTGGCTCAG...CTCCTACGGGAGGCAGCAAGATCGGAAGAGCACACGTCTGAACTCCAGTCAC -a ADAPTERX ^GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCTTGCTGCCTCCCGTAGGAG...CTGAGCCAKGACCAAACTCTNNNNNAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT -m 305 -M 360 --discard-untrimmed -o ${sample}_R1_trimmed.fq -p ${sample}_R2_trimmed.fq ${sample}*R1*.fastq ${sample}*R2*.fastq; done`

and I got this error for all my samples: 
cutadapt: error: unrecognized arguments: sample1_R1.fastq sample2_R2.fastq

**Comment by marcelm** [comment]
There is an extra `ADAPTERX` in there that you should remove.

**Comment by fedeboio** [comment]
Thank you!!

**Comment by marcelm** [comment]
Glad I could help.
