### ISSUE TITLE
ImportError: No module named cutadapt.scripts

### ISSUE THREAD

**Issue by Jomagrax** [marcelm/cutadapt#436]
Hi everyone
Im using cutadapt 1.18, I have installed it from conda (I think, Im using CAP-miRSeq and It requires a lot of programs and Im kind of lost).
Python version Python 2.7.15 :: Anaconda, Inc.

when I run cutadapt I find this problem
```
 /home/superuser/CAP-miRSEQ/bin/cutadapt -b AATCTCGTATGCCGTCTTCTGCTTGC -O 3 -m 17 -f fastq -q 20 /home/superuser/CAP-miRSEQ/sample_data/SRR326279_R1.fastq -o /home/superuser/CAP-miRSEQ/sample_output/fastqs//SRR326279.cutadapt.fastq --too-short-output=/home/superuser/CAP-miRSEQ/sample_output/fastqs//SRR326279.tooshort.fastq
Traceback (most recent call last):
  File "/home/superuser/CAP-miRSEQ/bin/cutadapt", line 9, in <module>
    from cutadapt.scripts import cutadapt
ImportError: No module named cutadapt.scripts
(base)
```
Im very new to bioinformatics so any help would be great.

Thankyou in advance, Jose

**Comment by marcelm** [comment]
The `cutadapt.scripts` module, which the error message refers to, was removed in Cutadapt 1.15, so it appears you somehow have an old Cutadapt installation (or parts of it) lying around.

So while I can say what the problem is, it’s a bit harder to solve it. I’m not familiar with CAP-miRSeq, and also there can be various places where that older installation of Cutadapt could be.

When Cutadapt is installed with Conda, you should not need to give the direct path to the program. Just typing `cutadapt` should already work. Have you tried this?

**Comment by marcelm** [comment]
I hope you fixed it. Get back to me if you still have the problem.
