### ISSUE TITLE
extend --times usage to linked adapters

### ISSUE THREAD

**Issue by frederic-mahe** [marcelm/cutadapt#444]
(using cutadapt 2.8 with python 3.7.3)

Linked adapters are great, and I use them to trim primers from amplicons (note: primer presence is _required_ in my pipeline, so `-g` option). However, a very small number of reads have more than one copy of each primer.

To tackle that issue, using the command `--times` would be nice but it does not seem to work with linked adapters:
```sh
# trim multiple times (expect gggg, get ccccACGTgggg)
printf ">test\nACGTccccACGTggggTAGC\n" | \
    cutadapt -g ACGT...TAGC -O 4 --times=2 - 2> /dev/null
```

Is there a way to marry linked adapters and `times`? If not, would you consider adding this feature?

Thanks,

**Comment by marcelm** [comment]
Hi, I think the behavior you see is due to you using the `-g` option for specifying the linked adapter. With `-g`, *both* adapters are required (in each round if you use `--times`). I think the above should work if you use `-a`. With `-a`, only the anchored adapters are required, so because there is a match in the first iteration, the second iteration should be run.

I’m not working at the moment, so any further replies may take a while.

**Comment by frederic-mahe** [comment]
Thanks for your answer. I think I have a better understanding of linked adapters now, so here's a more accurate description of what I am looking for.

I am interested in reads that contain both the adapters, other reads should be discarded. So, for a given read:
- both adapters are _required_ on the first iteration,
- reads with both adapters are subjected to a second iteration where both adapters are now _optional_

I realize it is a bit complicated. An easier solution for now is to chain two cutadapts:
- trim ADAPTER1 ntimes, keep trimmed,
- trim ADAPTER2 ntimes, keep trimmed

it achieves the same thing.
