### ISSUE TITLE
Error rate behaviour at "edges"

### ISSUE THREAD

**Issue by mbahin** [marcelm/cutadapt#456]
Hi,

Thanks for the great tool.
I have a question to be sure I understand how it works.
Let's say we a 10bp adapter. If we find the adapter with a deletion (then a 9bp  adapter), it will not be recognised whereas if there is an insertion (then a 11bp  adapter), it will be recognised. Am I right?
If so it's a bit unfair no?

Cheers,
Mathieu

**Comment by marcelm** [comment]
No, precisely because it would be unfair, the computation isn’t done that way. The error rate is computed by dividing the number of errors by the number of aligned nucleotides *in the adapter*. So you would get 1/10 in both cases. See also Section 2.2.6 (page 22) in [my dissertation](http://hdl.handle.net/2003/31824).

**Comment by soluna1** [comment]
Hi, 
Not exactly the same but in the line with Mathieu's comment, I would to be sure that this is what I think. This si my example: 


-g GTACACACCGCCCGTC;max_error_rate=0.2
	sequence: GTACACACCGCCCGTC; Type: regular 5'; Length: 16; Trimmed: 555528 times.
	No. of allowed errors:
	0-4 bp: 0; 5-9 bp: 1; 10-14 bp: 2; 15-16 bp: 3
The question is 16 x 0.2 = 3.2. Then this is the total errors allowed for this adapter, is it right? 
I'm confused because results show 1 bp between 5-9, 2bp between 10-14, and so on. So, my doubt if the final quantity (3) is the sum of each section or not.

Thanks for you work!

Sisi

**Comment by marcelm** [comment]
@soluna1 The numbers under the “No. of allowed errors” heading tell you how many errors are allowed for partial matches (the "regular 5'" adapter allows these), see also https://cutadapt.readthedocs.io/en/stable/guide.html#error-tolerance . So for example, for partial matches of 10 to 14 bp, there may be up to 2 errors.

**Comment by soluna1** [comment]
Thank you for your answer!!

**Comment by marcelm** [comment]
I believe this can be closed.
