### ISSUE TITLE
Remove 16s v3v4 primer sequences

### ISSUE THREAD

**Issue by termithorbor** [marcelm/cutadapt#465]
Hi all,

does anybody know what are the best settings to remove the 16s amplicon primers for the v3v4 region with cutadapt? 

I tried this code in R but it leads to at least some reads with 0 length, which seems strange.
```R
# Trim FWD and the reverse-complement of REV off of R1 (forward reads)
R1.flags <- paste("-g", FWD, "-a", REV.RC) 
# Trim REV and the reverse-complement of FWD off of R2 (reverse reads)
R2.flags <- paste("-G", REV, "-A", FWD.RC) 
# Run Cutadapt
for(i in seq_along(fnFs)) {
  system2(cutadapt, args = c(R1.flags, R2.flags, "-n", 2, # -n 2 required to remove FWD and REV from reads
                             "-o", fnFs.cut[i], "-p", fnRs.cut[i], # output files
                             fnFs.filtN[i], fnRs.filtN[i])) # input files
}
```
I am not sure if using the -g and -G here is really right.

Many thanks in advance :)

**Comment by marcelm** [comment]
For amplicon primer trimming, I suggest to use [linked adapters](https://cutadapt.readthedocs.io/en/stable/guide.html#linked-adapters-combined-5-and-3-adapter). The command line for specifying the adapters would be something like `-a ^FWD...REV.RC -A ^REV...FWD.RC`. And then `-n 2` is not needed.

How many reads are actually of length 0? In general (not from experience with this type of data), I’d expect there to be some zero-length reads since data is never perfect.
