### ISSUE TITLE
TypeError: cannot pickle '_io.BufferedWriter' object

### ISSUE THREAD

**Issue by JoshLoecker** [marcelm/cutadapt#469]
Cutadapt version: 2.10

Python version: 3.7.3

How did I install cutadapt? pip

What command line parameters have I used?
- cutadapt --revcomp --cores 0 --adapter 3'_PRIMER --front 5'_PRIMER --error-rate 0.15 --output /my/output/path/output_file.fastq /my/input/path/input_file.fastq

When running the above command in the terminal, I get an output of `TypeError: cannot pickle '_io.BufferedWriter' object`. I have the following python file set up to test what was happening in my main script; this problem occurs in both of them

```
import subprocess
from pathlib import Path

primer_5 = "TTTCTGTTGGTGCTGATATTGCAGRGTTYGATYMTGGCTCAG"
primer_3 = "ACTTGCCTGTCGCTCTATCTTCTACCTTGTTACGACTT"
error_rate = 0.15
output_file = "/Users/USERNAME/Desktop/cutadapt_output.fastq"
file = Path("/Users/USERNAME/PythonProjects/Results/Barcode/barcode81/barcode81_merged_reads.fastq")

message = "cutadapt --revcomp --cores 0 --adapter {primer_3} --front {primer_5} --error-rate {error_rate} --output {out_file_path} {in_file_path}".format(
                primer_3=primer_3,
                primer_5=primer_5,
                error_rate=error_rate,
                out_file_path=output_file,
                in_file_path=file
            )

subprocess.run(message.split(" "))
```

This has only happened recently, and the only difference I've made since this started happening was moving from Windows 10 to macOS Catalina (10.15).

**Comment by marcelm** [comment]
Can you please verify that you get the same error when you run the command directly from a shell?

Can you please also post the full stacktrace so that I can see where the error occurs?

I’m sure the error message comes from Python’s `multiprocessing` module, so you could work around the problem by using `--cores=1` (but of course it will be slower).

**Comment by marcelm** [comment]
Are you absolutely sure that Cutadapt is running under Python 3.7? Even if the above script is run under Python 3.7, it could still be that Cutadapt runs under a different Python version. You can check by applying the workaround I mentioned (`--cores=1`) and then look at the first couple of lines. (`This is Cutadapt x.yz running under Python a.b.c`)

The reason I am asking is that I believe that this is due to a change [in the multiprocessing module](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods) in Python 3.8 under macOS:
> *Changed in version 3.8:* On macOS, the *spawn* start method is now the default. The *fork* start method should be considered unsafe as it can lead to crashes of the subprocess. See bpo-33725.

I develop and test under Linux, where by default the *fork* method is used. If I explicitly switch to *spawn*, then I get the same error as you even under Linux.

I don’t know when I’ll have time to fix this for macOS. In the meantime, you can try to install Cutadapt under Python 3.7. If Cutadapt actually already runs under 3.7, then that won’t help of course, but then I don’t know what other problem there could be.

**Comment by marcelm** [comment]
Note to myself: One problem is that `WorkerProcess` in `pipeline.py` has an `_orig_outfiles` attribute.

**Comment by marcelm** [comment]
This should be fixed now. I still don’t have automated tests for macOS, but I manually added 
```
import multiprocessing
multiprocessing.set_start_method('spawn')
```
to `__main__.py` to simulate what Python 3.8 on macOS does, and after a couple of fixes, it worked.
