### ISSUE TITLE
Parameter to turn off reporting of time

### ISSUE THREAD

**Issue by and3k** [marcelm/cutadapt#477]
Hi!

It would be excellent, if there would a parameter or `--report=` option to get the default report, but without the timings (i.e., without `Finished in 0.22 s (28 us/read; 2.11 M reads/minute).`). This would then make the cutadapt report reproducible/identical every time.

Thanks!

Best,
Bela

**Comment by marcelm** [comment]
Hi, you can pipe the report through `sed '/^Finished in/d'` or `grep -v '^Finished in'` to get rid of that line, but you may know that already. Do you think that’s good enough for you? Since it’s relatively easy to use one of these commands, I would like to avoid adding an extra option. I can add this to the documentation as well.

I will keep the requirement for reproducible output in mind when I add anything else to the report.

**Comment by and3k** [comment]
Yes, I use sed at the moment. I just generally prefer formal solutions for reproducible output. But if you prefer to keep it simple, this is of course fine too and I’ll keep using sed :)

Thanks :)

**Comment by marcelm** [comment]
Hi, just to let you know that I’m working on adding a JSON-formatted report to Cutadapt. I decided not to include runtimes in that report just so it would be reproducible, also because of your feedback. See >https://cutadapt.readthedocs.io/en/latest/guide.html#json-report> (the documentation is still a work in progress).
