### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character '\xb5' in position 26

### ISSUE THREAD

**Issue by bbimber** [marcelm/cutadapt#494]
I am using cutadapt 3.0 with Python 3.6.9, installed via pip. 

The command is a simple one to crop reads, using a gzipped input:

cutadapt --length 26 -o s_32771_CKDL200158959-1a-SI_GA_C1_H3MFFDSXY_S14_L002_R1_001.crop.fastq.gz s_32771_CKDL200158959-1a-SI_GA_C1_H3MFFDSXY_S14_L002_R1_001.fastq.gz

Note: these are PE fastqs, but I want to crop read 1 only (this seemed to be the only way to do this. I am receiving this error, on three different input FASTQs:

--- Logging error ---
Traceback (most recent call last):
   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/logging/__init__.py", line 996, in emit
   stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\xb5' in position 26: ordinal not in range(128)
Call stack:
   File "/home/exacloud/gscratch/prime-seq/bin/primeseq-python/bin/cutadapt", line 8, in <module>
   sys.exit(main_cli())
   File "/home/exacloud/gscratch/prime-seq/bin/primeseq-python/lib/python3.6/site-packages/cutadapt/__main__.py", line 825, in main_cli
   main(sys.argv[1:])
   File "/home/exacloud/gscratch/prime-seq/bin/primeseq-python/lib/python3.6/site-packages/cutadapt/__main__.py", line 907, in main
   logger.log(REPORT, '%s', report(stats, elapsed, args.gc_content / 100))
Message: '%s'
Arguments: ('Finished in 1019.54 s (10 \xb5s/read; 5.83 M reads/minute).\n\n=== Summary ===\n\nTotal reads processed:              99,113,854\nReads with adapters:                         0 (0.0%)\nReads written (passing filters):    99,113,854 (100.0%)\n\nTotal basepairs processed: 14,867,078,100 bp\nTotal written (filtered):  2,576,960,204 bp (17.3%)',)

All three complained about '\xb5', which is "µ", I think. That shouldnt appear in any of these files. Is it possible it's trying to read the zipped files as text? 

Despite these errors, cutadapt completes, exits with exit code 0, and makes an output file. Have you seen similar error messages before? Is there anything I should check on my inputs?

Thanks for any help.

**Comment by marcelm** [comment]
The error refers to the message that Cutadapt wants to print: "Finished in 1019.54 s (10 µs/read)"

Older Cutadapt versions wrote "us" instead of "µs". (Changed in https://github.com/marcelm/cutadapt/commit/cc79de248412b320404f52358fe037d17ea34980.)

The problem may be that you don’t use a UTF-8 locale. What does the command `locale` output on your system? (Are you running this in a Docker container or similar?)

**Comment by marcelm** [comment]
I was able to reproduce the problem on Python 3.6 by setting `LC_ALL=C`. Also, it appears that [Python 3.7 fixes this](https://docs.python.org/3.7/whatsnew/3.7.html#whatsnew37-pep538) by automatically switching to a UTF-8 locale.

**Comment by marcelm** [comment]
I’ve fixed the problem in the development version.

Note also that you can ignore this logging error for now unless you need a correctly formatted summary report. The output file(s) will still be created correctly. (I changed this just now, so in the future the exit code will not be 0 on logging errors because I don’t think that errors should be silenced, but up to Cutadapt 3.0, logging errors are ignored.)

**Comment by bbimber** [comment]
@marcelm that makes sense - thank you for the rapid fix!

**Comment by marcelm** [comment]
No problem! :-)
