### ISSUE TITLE
Feature request: use parentheses to specify the part of the adapter that should be kept.

### ISSUE THREAD

**Issue by DriesSchaumont** [marcelm/cutadapt#501]
Hi, 

I read in the [documentation ](https://cutadapt.readthedocs.io/en/stable/ideas.html) that you would consider implementing a feature where parentheses are used to specify the part of the adapter that should be kept. I just encountered a usecase where such a feature would greatly improve my workflow. Is there any chance that this feature will be included somewhere in the future?

Thanks in advance,
Dries

**Comment by marcelm** [comment]
I don’t know if that is sufficient for your purposes, but since version 3.1, which was released two weeks ago, you can use `--action=retain` to leave the adapter sequence itself in the read, see #443.

The idea with the parentheses would allow more fine-grained control, so that you could for example remove only half of an adapter, but it’s more complicated to implement: At the moment, the alignment algorithm only detects where an adapter starts and ends within a read. But because insertions and deletions are possible, this is not enough information for cutting at the correct position in case you want to do remove only parts of the adapter. I would therefore need to find full alignments (that is, which base in the read was aligned to which base in the adapter).

(I should update that To Do/Ideas part of the documentation, it’s a bit outdated.)

**Comment by DriesSchaumont** [comment]
Thank you for the quick response!

Leaving the adapter in the read is not really what I am looking for. Perhaps I should explain what I am trying to achieve.
I am working with paired-end reads originating from Genotyping-by-Sequencing experiments.

The DNA in the library looks like this.
```
            ...|--adapter 1--|--sample_barcode--|--RE1--|--genomic insert--|--RE2--|--adapter spacer--|--adapter 2--|...
forward sequencing_primer --->
                                                                                                       <------reverse sequencing_primer
```
After sequencing, the reads look like this (note that I intentionally left out the orientation of the sequences because that would overcomplicate things)
```
Forward-reads:
|sample_barcode--|--RE1--|--genomic insert--|--RE2--|--adapter spacer--|--adapter 2...
Reverse reads:
|adapter spacer--|--RE2--|--genomic insert--|--RE1--|--sample_barcode--|--adapter 1...
```
RE1 and RE2 are sequences that must flank the insert, because they are remnants of the sites that were recognized by the restriction enzymes to remove insert from the genome. All othet sequences were added during library preparation.
Adapter 1 and 2 represent the Illumina sequencing adapters (i5 or i7). We have also added a sample-specific barcode so that we can pool samples and sequence them in a single run. 

Recently, sequencing providers have been introducing variable length spacers in the adapter sequences. This is to make sure that sequencing many identical reads happend out-of-phase so that the dectors of the sequencer do not get overloaded. For example, the spacer sequence can be any of the following: `GACT, GAC, GA, G` or no spacer.

Note that in the forward reads, `RE2` + `adapter spacer` + `adapter 2` may or may not be present, or only in part, depending on the read length. Same goes for `RE1` + `sample_barcode` + `adapter 1` for the forward read.

The steps I want to perform are:

1. Look for one of the possible spacers at the beginning (anchored) of the reverse read. Ideally, this could be done in combination with the RE2 sequence to improve the pattern matching. However, only the spacer should be removed, which was the reason why I was interested in being able to specify which part of the sequence should be removed. 
2. Based on the length of the spacer that was trimmed from the beginning of the reverse read, a number of bases should be removed from the end of the reverse read. This is to ensure that no bias will be introduced in further downstream analyses because there is more sequence to match on for the read that got a shorter spacer. For example, if the spacer is `GACT`, 0 bases should be removed from the end of the reverse read, for `GAC`  1 extra base should be removed, for `GA` 2, etc...  
3. Based on which spacer was found at the beginning of the reverse read, remove the spacer and the adapter from the end of the forward read if present.

I was thinking that a combination of `linked` and `--pair-adapters` could be used to solve this usecase:

For the trimming of the reverse reads multiple `linked adapters` could be used: 

- `^GACT+RE2...sample barcode+adapter1X`
- `^GAC+RE2...N+sample barcode+adapter1X;min_overlap=1`
- `^GA+RE2...NN+sample barcode+adapter1X;min_overlap=2`
- `^G+RE2...NNN+sample barcode+adapter1X;min_overlap=3`
- `^RE2...NNNN+sample barcode+adapter1X;min_overlap=4`

These sequences could be paired with adapters for trimming the forward reads. Note that if for example the spacer `GACT` is found at the beginning of the reverse read, the reverse complement of that spacer should be present at the end of the forward read if the forward read is long enough.

- `RE2+GACT+adapter 2X`
- `RE2+GAC+adapter 2X`
- `RE2+GA+adapter 2X`
- `RE2+G+adapter 2X`
- `RE2+adapter 2X`

A couple of questions that I had were (let me know if this issue is no longer the correct place to ask these).

- It would be nice to be able to look for the spacer + RE2 at the beginning of the reverse reads, but only remove the spacer. This would increase the specificity of the matching. However, things might work by only matching the spacer, so it is not really a must-have. From you explanation I understand now that implementing this feature for partial matches is indeed complicated, so let's just leave that alone for now.
- How does using `--pair-adapters` interact with `--pair-filter=` and `--discard-untrimmed`? In this case, the trimming of the reverse read is required, while it is optional for the forward read. If I understand correctly, this is not possible because `--pair-adapters` will look for an adapter in the forward read first, and only if that succeeds look for an adapter in the reverse read? I think I might need to be able to set `--pair-filter=second`. 
- I was wondering if the wildcards (`N`) in the linked adapters will ensure that the end of the reverse reads are adjusted based on the spacer that was removed (see 2. above)

I hope my explanation was somewhat clear.
Thank you in advance!

**Comment by marcelm** [comment]
You caught me on my last working day of this year, so it may take some time for further replies. But here is what I can think about already now.

> From you explanation I understand now that implementing this feature for partial matches is indeed complicated

The annoying thing for this and many other features that are on my "nice to have" list is that implementing only the algorithm would actually be not complicated at all, but all the work surrounding that, such as designing the command-line interface, documentation and testing, take much more time. I like the notation with a `+`, by the way, perhaps that would be the way it could look if I ever implement this.

I don’t know if you’ve thought about this already, but some problems can be solved by running Cutadapt multiple times. I haven’t thought this through, but you could run it once to remove the spacers, and then run it a second time with `-g ^RE2` and `--action=none --discard-untrimmed`. The first round would give you false positive matches, but the `--discard-untrimmed` in the second round ensures that you continue only with sequences that start with RE2.

If you do this and the beginning of RE2 can look like the spacer, then you get false positive matches in the first round that remove part of RE2, but if you then in the second round *do not* anchor RE2, but use `-g RE2;min_overlap=` with a minimum overlap length that is slightly lower than the length of RE2, it would still work.

> I was wondering if the wildcards (`N`) in the linked adapters will ensure that the end of the reverse reads are adjusted based on the spacer that was removed (see 2. above)

That should work.

If you only trim spacers in the first round and your reads have constant length, you could also trim reads to a constant length (for example `--length=96` if your original reads have length 100) instead of doing that trick.

Another minor point: If you search for `^GACT+RE2` and also for `^RE2` but using the same error rate, the actual *number* of errors allowed for the longer sequence is higher. And if you do allow errors, they can also be in the spacer. Not sure if this is something to worry about, though. (I am also not sure if there are other effects because the sequences are so similar.)

>  * How does using `--pair-adapters` interact with `--pair-filter=` and `--discard-untrimmed`? In this case, the trimming of the reverse read is required, while it is optional for the forward read. If I understand correctly, this is not possible because `--pair-adapters` will look for an adapter in the forward read first, and only if that succeeds look for an adapter in the reverse read? I think I might need to be able to set `--pair-filter=second`.

No, please let me know if this could be clarified in the documentation: The `--pair-adapters` option requires that an adapter is found *both* on R1 *and* on R2. So `--pair-filter` should be irrelevant: If the adapter was found on R1, but not on R2 or vice versa (or on neither read), none of the reads are modified and the pair is considered to be untrimmed (and discarded with `--discard-untrimmed`).

Thanks for the very clear explanation, by the way, I really appreciate it.

**Comment by DriesSchaumont** [comment]
Hi! 

My apologies for the late follow-up. I managed to figure it out by running cutadapt multiple times!

Thank you for answering my questions, I am going to close this issue.

**Comment by marcelm** [comment]
Many bug reporters don’t get back to me at all, so I’m glad you did :-). Good you solved it!
