### ISSUE TITLE
Feature request: specify pre-built index for demultiplexing

### ISSUE THREAD

**Issue by jdc8890** [marcelm/cutadapt#503]
Hi,

We use cutadapt for demultiplexing and often use the same set of barcode sequences across sequencing runs.  Is it possible to provide a pre-built index of sequencing adapters instead of building it each time cutadapt is run?  This presumably would speed up processing time for cases when a common set of adapter sequences is repeatedly used.

Thanks so much for your help and support!

**Comment by marcelm** [comment]
Can you give me some numbers? How many barcodes do you provide, how long are they, at which error rate, and how long does it roughly take to build the index?

It may be easier to just make the index creation faster. I never optimized it because I thought that the time for index creation is neglible compared to the overall runtime.

**Comment by jdc8890** [comment]
Thanks so much for your help and prompt reply.

We usually have 48 or 96 adapter sequences with lengths of 18 to 30 bp and
run cutadapt with at most 2 errors (including indels) allowed (i.e. the
--no-indels option is not specified).  Usually takes 3-4 minutes to build
the index and < 1 minute to demultiplex the reads.  We repeat this process
on many samples, so a lot of time is spent repeatedly building the same
index over and over.

**Comment by jdc8890** [comment]
Thanks so much for your help and prompt reply.

We usually have 48 or 96 adapter sequences with lengths of 18 to 30 bp and run cutadapt with at most 2 errors (including indels) allowed (i.e. the --no-indels option is not specified).  Usually takes 3-4 minutes to build the index and < 1 minute to demultiplex the reads.  We repeat this process on many samples, so a lot of time is spent repeatedly building the same index over and over.

**Comment by marcelm** [comment]
There is an (undocumented) option `--no-index` that you could try. Demultiplexing itself will be slower, but you save the index creation time, so perhaps it’s faster overall.

**Comment by jdc8890** [comment]
That certainly seemed to help a lot--thank you.  Would obviously be even faster with the pre-built index (roughly 10x from comparing the actual demultiplexing times).  Any chance that feature can be incorporated in a future release?

**Comment by marcelm** [comment]
I’m looking into it. What I recommended is only a workaround for the moment. For me creating an index of 96 barcodes with lengths 18 to 30 bp takes eight minutes, which is of course unacceptably slow, and I think I can get this down significantly.

Adding infrastructure for persisting the index would be a lot more work because I would have to come up with a file format for it, code for writing and reading that format, new command-line options and tests for all of this; I would need to add documentation, and then users would have to learn about this, so I would really prefer to just make index creation faster.

**Comment by marcelm** [comment]
I implemented the index creation differently and was able to reduce the time from 8 minutes to 5 seconds.

Is that good enough for your use case?

**Comment by marcelm** [comment]
I’ve just released Cutadapt 3.2 with this change included.

**Comment by jdc8890** [comment]
This works great.  Thank you so much!
