### ISSUE TITLE
Crashes on multicore when conducting "Demultiplexing paired-end reads"

### ISSUE THREAD

**Issue by aoki0623mriid2** [marcelm/cutadapt#504]
Thank you for a fantastic tool. However, I have trouble in using it In the "Demultiplexing paired-end reads with combinatorial dual indexes" approach on Illumina pair-end data.

A single threaded run works as expected i.e:
cutadapt -g adaptor=^(adaptor sequence)
 --report=minimal
 --cores=1
 -O 6 -o {name}_Read2.fastq.gz -p {name}_Read1.fastq.gz\
 Read2.fastq.gz Read1.fastq.gz

However, multi threaded run (i.e. --cores=2) dose not work with the error

Traceback (most recent call last):
  File "c:\users\username\anaconda3\lib\runpy.py", line 193, in _run_module_as_ma
in
    "__main__", mod_spec)
  File "c:\users\username\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\username\AppData\Roaming\Python\Python37\Scripts\cutadapt.exe\__
main__.py", line 9, in <module>
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\cutadapt\
__main__.py", line 845, in main_cli
    main(sys.argv[1:])
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\cutadapt\
__main__.py", line 912, in main
    stats = r.run()
  File "C:\Users\username\AppData\Roaming\Python\Python37\site-packages\cutadapt\
pipeline.py", line 802, in run
    assert isinstance(connection, Connection)
AssertionError

I run version 3.2 under python 3.8.3 installed using "pip install --user --upgrade cutadapt"

Best regard, 
Hiroyasu

**Comment by marcelm** [comment]
The file names refer to Python 3.7, but you say that you are running it under Python 3.8, so something is a little off. What does Cutadapt itself say? (The `This is Cutadapt 3...` message)

Since the error message does not contain enough information, do you think you could do the following: Open the file `C:\Users\username\AppData\Roaming\Python\Python37\site-packages\cutadapt
pipeline.py` in a text editor, go to line 802 and change
```
assert isinstance(connection, Connection)
```
to
```
assert isinstance(connection, Connection), connection
```
and then run the command again? Then post the log output again.

I don’t develop or test Cutadapt under Windows, so this may be a Windows-specific thing.

**Comment by aoki0623mriid2** [comment]
Thank you for your kind reply.

First, I am so sorry that I misunderstood the version of Python. My cutadapt 3.2 runs with Python 3.7.3.

Following your message, I changed the cutadapt pipeline.py script, then ran cutadapt again.
However, multi thread run did not work with the error message as below, 
Traceback (most recent call last):
  File "c:\users\aokimpm\anaconda3\lib\runpy.py", line 193, in _run_module_as_ma
in
    "__main__", mod_spec)
  File "c:\users\aokimpm\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\AokiMPM\AppData\Roaming\Python\Python37\Scripts\cutadapt.exe\__
main__.py", line 9, in <module>
  File "C:\Users\AokiMPM\AppData\Roaming\Python\Python37\site-packages\cutadapt\
__main__.py", line 845, in main_cli
    main(sys.argv[1:])
  File "C:\Users\AokiMPM\AppData\Roaming\Python\Python37\site-packages\cutadapt\
__main__.py", line 912, in main
    stats = r.run()
  File "C:\Users\AokiMPM\AppData\Roaming\Python\Python37\site-packages\cutadapt\
pipeline.py", line 802, in run
    assert isinstance(connection, Connection), connection
AssertionError: <multiprocessing.connection.PipeConnection object at 0x000002244
AABFFD0>

Please give me a suggestion to solve this problem.

Hiroyasu

**Comment by marcelm** [comment]
> My cutadapt 3.2 runs with Python 3.7.3.

Thanks for clarifying.

> However, multi thread run did not work with the error message as below,

That is expected, the change was only so that the error message would give me more information, and it did.

Can you now edit the file again, but this time just *remove* the line with the `assert` (line 804)? That could actually fix the problem. If it does, then please let me know and will make that change in Cutadapt itself so others benefit from it.

**Comment by aoki0623mriid2** [comment]
My cutadapt run well after removing the line 802!!!

Thank you for your kindness!!! I am very grateful for your help.

**Comment by marcelm** [comment]
Perfect! I’ll change this also in Cutadapt (next week) and then close this issue. Thanks for reporting!
