### ISSUE TITLE
cutadapt error message: reads are improperly paired

### ISSUE THREAD

**Issue by Vieira34** [marcelm/cutadapt#505]
Dear Martin,

First of all, sorry if this particular issue has been posted already (I did not found it). I have read the previous issues on the topic and couldn't figure out a potential workaround for me (if have one).

I'm facing an issue trying to use cutadapt to remove primers in a particular dataset (16S V4 region ~275bp. Of 37 samples, just 1 sample passed the cutadapt process without an error). 

some info:
cutadapt 2.10 with Python 3.8.2
python3 -m pip install --user --upgrade cutadapt
command line parameters: -g GTGCCAGCMGCCGCGGTAA -a ATTAGAWACCCBDGTAGTCC -G GGACTACHVGGGTWTCTAAT -A TTACCGCGGCKGCTGGCAC -n 2 -o Z2_1.fq.gz -p Z2_2.fq.gz ZZ2_1.fq.gz ZZ2_2.fq.gz
Processing reads on 1 core in paired-end mode ...
cutadapt: error: Error in sequence file at unknown line: Reads are improperly paired. Read name 'FCHGYVCBCX3:1:1101:9900:5591#G_GTTAACCT_TTCGGATT/1' in file 1 does not match 'FCHGYVCBCX3:1:1101:9900:5591#A_GTTAACCT_TTCGGATT/2' in file 2.

As you see the name differences come from the sequences fragments added to the read name (these files come from a sequencing provider and I'm not sure what this means. Maybe adapters or links?). All the 36 samples/files have the same error message, the X read name in file 1 differ from the X name in file 2. The differences come from these sequence fragments. The one sample that passed the cutadapt process has the same read names in file and 1 and in file 2 (include the sequences fragments). Any suggestion to go around it?

Thank you for your time and attention.

Best,
Fabricio

**Comment by marcelm** [comment]
Hi Fabricio,

first, I would suggest that you report this to whoever produced these files if you can because they are, in my opinion, incorrect or at least don’t follow best practice. Nonidentical read identifiers can lead to problems with tools that assume the IDs are in fact identical. For example, if these IDs end up in a BAM file, they may not be recognized as paired-end, but as two single-end reads.

As a workaround, you can modify the FASTQ headers such that the read IDs become identical. Note the terminology in case it’s unclear: The part before the first whitespace is the read ID, the rest is the read comment or description. See also [this section in the documentation](https://cutadapt.readthedocs.io/en/stable/guide.html#rename-renames-reads
).

You can for example turn the `#` into a whitespace and then the `G_GTTAACCT_TTCGGATT/1` part would become part of the read description. It’s possible that your read names are then no longer unique, perhaps that is something to watch out for.

Here’s a `sed` command to do this for a single file (untested):
```
zcat ZZ2_1.fq.gz | sed '1~4s/#/ /' | pigz > ZZ2_fixed_1.fq.gz
```
Use `gzip` instead of `pigz` if you don’t have the latter.
 
There is currenly no option in Cutadapt to disable the check for identical read names.

By the way, instead of specifying a 5' and 3' adapter and using `-n 2`, you may want to use [https://cutadapt.readthedocs.io/en/stable/guide.html#linked-adapters](linked adapters). With `-n 2`, Cutadapt could theoretically remove the 5' (or 3') adapter twice. With linked adapters, that doesn’t happen.

**Comment by Vieira34** [comment]
Hi Martin,

I also found this a little strange too. These fastq files come from a big sequencing provider and prob out there have a lot of people with these types of fastq files. I realized it because I ended up using cutdapat to check for primer instead of the pipeline that I'm planning to use which uses a completely different approach to check or remove primers (and in this approach, the unmodified fastq files [headers] worked but I was not happy with the results and then decided to use cutadapt to check it). Yes, I'll contact them to understand what happened.

I do not saw the cutadpat documentation targeting fastq names and/or read identifiers (my bad. thanks for it). The sed command that you provided works on Linux/ubuntu but I don't know yet the behavior of modified files (do the reads identifiers still unique?). I'll test it and if I see an issue I'll back to this post.

Thank you for the suggestions about the cutadapt parameters and I'll try it. I'm using cutadapt in a loop in R following the pipeline from that R package.

I think I hit the button that closes this issue (accidentally).

Thank you for your time and attention.

Best,
Fabricio

**Comment by marcelm** [comment]
Thanks for the feedback.

I added the documentation about read IDs very recently, no wonder you haven’t seen it.

If you need to change the read IDs in a different way so that they stay unique, let me know and I may be able to help.

**Comment by Vieira34** [comment]
Martin,

Using the sed command that you provided (zcat ZZ2_1.fq.gz | sed '1~4s/#/ /' | pigz > ZZ2_fixed_1.fq.gz) worked but the end of the read ID no longer has the number 1 or 2 in the end (see example below). On the other hand, look like the read ID still unique and match in file forward and file reverse. Do you see this as an issue for cutadapt or other tools?

Read Id before sed command:
@FCHGYVCBCX3:1:1101:9900:5591#G_GTTAACCT_TTCGGATT/1 in file 1
@FCHGYVCBCX3:1:1101:9900:5591#A_GTTAACCT_TTCGGATT/2 in file 2

Read Id after sed command:
@FCHGYVCBCX3:1:1101:3516:2191 CAATATA_GGTGTTAA_TTCAAGGT/1
@FCHGYVCBCX3:1:1101:3516:2191 ATCA_GGTGTTAA_TTCAAGGT/2

I would like to know what you have in mind to try to change the read identifiers in a different way than the sed command, if you can share it with us.

Thank you,
Fabricio

**Comment by marcelm** [comment]
The `/1` and `/2` suffixes are a convention used in some old Illumina FASTQ files. These are not used nowadays and Cutadapt just ignores them if it finds them.

If these are not already old FASTQ files, then the provider of those files was inspired by that old convention and added them to the read ID. If you use a custom program afterwards that requires these suffixes, you you should replace the `#` with `/1 ` in the first file and with `/2 ` in the second file. You can modify the sed command like this: Use `sed '1~4s_#_/1 _'` for the R1 file and `sed '1~4s_#_/2 _` for the R2 file.

Another way to fix the files is to force the read ID of the R2 file to be identical to the read ID of the R1 file. Here is a way to do it, assuming your input is in `paired.1.fastq.gz` and `paired.2.fastq.gz`:
```
paste <(zcat paired.1.fastq.gz | paste - - - -) <(zcat paired.2.fastq.gz | paste - - - -) | awk -vFS="\t" -vOFS="\t" '{$5=$1}; 1' | tr '\t' '\n' | cutadapt --interleaved -o out.1.fastq.gz -p out.2.fastq.gz -
```
Output is `out.1.fastq.gz` and `out.2.fastq.gz`.

* The `paste` command converts the input FASTQ files into an 8-column, tab-separated format (one read-pair per line).
* The `awk` command (in particular, the `$5=$1` part) sets column 5 (header of file 2) to column 1 (header of file 1)
* The `tr` command converts to interleaved FASTQ format
* The final `cutadapt` command converts from interleaved FASTQ to two-file (noninterleaved) FASTQ and compresses the output at the same time

It’s not pretty, but you asked for it ...

**Comment by Vieira34** [comment]
These files were generated at the end of last year (2020) and I curious to hear back from the provider what these fragments mean at the end of the read name. Thanks, very interesting notes about it.

Well, the solution maybe is not elegant but is efficient (the command works, and I'm loading the pipelines to see what happens).

Thanks,
living and learning...
