### ISSUE TITLE
Install cutadapt v3.4 on windows

### ISSUE THREAD

**Issue by elpape** [marcelm/cutadapt#523]
Hi,

I tried to install Cutadapt v 3.4 on my windows machine (windows 10) using the exe file from the GitHub page, but it does not work. First of all, I get several warnings the file is "suspicious" and I should not download it. If I disregard those comments and try to run it anyways, nothing happens..

Any thoughts?
Thank you!
Ellen

**Comment by marcelm** [comment]
Sorry, the instructions for this are a bit incomplete because this is still experimental. I also get the warning that the file is suspicious. I haven’t investigated how to get rid of this.

You need to run the `cutadapt-3.4.exe` file from the command line. So you need to run `cmd.exe` (or Powershell), use the `cd` to go to your downloads directory and then type in `cutadapt-3.4` to run it.

If you just double-click the file, nothing will happen indeed because it does not have a graphical interface.

**Comment by elpape** [comment]
Hey,

Thanks for your quick answer! Now the exe file cannot even be downloaded; Windows "says" it contains a virus..

Ellen

**Comment by marcelm** [comment]
Sorry about that. I use PyInstaller to create the Windows executable. PyInstaller is unfortunately also sometimes used by malware authors. It embeds parts of itself into the output file, and if the antivirus vender then recognizes that part as malware, even other, legitimate programs created with PyInstaller will be recognized as malware.

The PyInstaller people are aware of that problem, but cannot really do anything about it. They recommend to report the issue to the antivirus vendor. I agree when they say that these kinds of false positives should be fixed in the antivirus software, and not by the software authors.

There appears to be a recent change in PyInstaller that may reduce the problem, but the released PyInstaller version does not contain this, yet.

In general, I usually think that Linux is a better choice for bioinformatics work because lots of other bioinformatics software isn’t available for Windows at all. Bioconda packages are only provided for Linux and macOS, for example. I do realize that Windows is a more familiar territory for many people, though, so when I found PyInstaller, I thought that it would be nice to provide executables to those folks on Windows who cannot or don’t want to install Linux. However, if this turns out to be too much work, then I cannot do this. I don’t use Windows myself, so my interest is limited. And I’d rather spend time working on improving other aspects of Cutadapt.

If you, or anyone else reading this, want to help out, please submit the `.exe` file to your antivirus vendor and tell them that they should not classify it as malicious.

By the way, I don’t know how well this works, but an alternative to installing a full Linux is to try out the Windows Subsystem for Linux (WSL), which provides a Linux environment within Windows. That would allow one to run Linux programs, including Cutadapt.

**Comment by elpape** [comment]
Hi,

In the meantime I installed Linux via a VirtualBox, and managed to install cutadapt via pip (following your installation instructions). I once was told the virtualBox is preferred over a WSL, but don't remember the exact reasons for that..

Thanks anyways!
Ellen

**Comment by marcelm** [comment]
If you are happy with VirtualBox, that is totally fine!

I’ll leave this issue open for a while until the mentioned PyInstaller improvement is available.

**Comment by marcelm** [comment]
PyInstaller now contains a feature to reduce these types of false positives (EXE checksums, see <https://pyinstaller.readthedocs.io/en/stable/CHANGES.html#id11>), so in the hope that it fixes the problem, I’m closing this.

To others reading here that are still on Windows: You may want to test the exe available at <https://github.com/marcelm/cutadapt/actions/runs/1177458667> under the "Artifacts" heading, which was created with a recent PyInstaller version.
