### ISSUE TITLE
Larger size of the output file after discarding trimmed reads

### ISSUE THREAD

**Issue by VakilT** [marcelm/cutadapt#534]
- Cutadapt and Python version: **cutadapt version 3.4**, **python/3.7.4**
- How you installed the tool: **pip**
- Which command-line parameters you used: **cutadapt -g "GACTGGTTCCAATTGAAAGTGCTCTTCCGATCT;e=0.1;min_overlap=27" --discard-trimmed -o OUTPUT.fastq.gz INPUT.fastq.gz**

Hello,

I had the following output of cutadapt:

Total reads processed:              14,214,892
Reads with adapters:                    43,904 (0.3%)
Reads written (passing filters):    14,170,988 (99.7%)

I independently confirmed that INPUT.fastq.gz and OUTPUT.fastq.gz had 14,214,892 and 14,170,988 reads, respectively. However, I was surprised to see that INPUT.fastq.gz has the size of 666M, whereas OUTPUT.fastq.gz - 702M. Thus, although OUTPUT.fastq.gz has 43,904 reads less, the file actually has a bigger size. Could you please tell me if there may be some kind of error? Thanks a lot!

Kind regards,
Vakil

**Comment by marcelm** [comment]
This is probably due to the gzip compression level. Cutadapt sets it to 6 by default, but up to 9 is possible. If you want, you can use `--compression-level=7` to change this (or `=8`, `=9`). However, with this, most of the time spent processing the reads will be spent on compression, so it may not be worth it.

**Comment by VakilT** [comment]
Thanks a lot!
