### ISSUE TITLE
Trimming nested/tiled amplicon primers when library prep involves fragmentation?

### ISSUE THREAD

**Issue by charlesfoster** [marcelm/cutadapt#543]
Hi,

I'm interested in using `cutadapt` to trim amplicon primers prior to downstream analyses (variant calling etc.). However, I'm not sure what would be the best command to do so, or if it's even possible in my case.

We're (partially) amplifying a viral genome using a nested/tiled PCR scheme. After PCR amplification, we carry out library prep using a Nextera approach that includes a fragmentation step. Accordingly, after sequencing, the reads won't necessarily start and end with the amplicon primer sequences. I'm not sure whether using tiled amplicons complicates the matter either. For example, these are some of the tiles primers and where they target:

ForwardPrimer|Sequence|Position_in_Genome|ReversePrimer|Sequence|Position_in_Genome
-- | -- | -- | -- | -- | --
HKU1-pol-LPW1465-F | GTTCAAGTGTCGCTGTTCA | 13557-13575 | HKU1-pol-LPW1822-R | CTATCATTATCACAATCCACAG | 14477-14456
HKU1-pol-LPW1467-F | GGGTATGAAGTATCATCCTA | 14433-14452 | HKU1-pol-LPW1825-R | GATAATCCCAACCCATAAGAAC | 15421-15400

There are 22 primers (11 forward, 11 reverse) in total, and I have them within a fasta file. I guess I have two main issues/questions here:

1. Does fragmentation during library prep make it impossible to trim the amplicon primers from the sequencing reads?
2. Do partially overlapping amplicons cause an issue for `cutadapt`?

I hope to properly trim these primers from the sequencing reads with `cutadapt` (e.g., using linked adapters). I don't have a sample command line code because I haven't tried it yet - not sure where to start.

Thanks

**Comment by charlesfoster** [comment]
Thank you for the very helpful and well thought out answer - much appreciated. Based on what you've summarised, can I please confirm that the following command should do as we expect?

```
cutadapt -j0 \
-a primers_reverse.fa \
-g primers_forward.fa \
-A primers_reverse.fa \
-G primers_forward.fa \
--prefix {name} \
--action lowercase \
-o trimmed_R1.fq.gz \
-p trimmed_R2.ffq.gz \
$R1 $R2
```
I'm masking them as lowercase to inspect the results. Thanks!

**Comment by marcelm** [comment]
Just a thought before going into this: Have you considered not trimming the primers at all and map the reads unmodified? It will give you higher coverage at the loci where the primers are and therefore bias your variant calling somewhat, but at the very least, you can get a first impression of your data and you can compare before/after primer trimming to check whether it worked.

Regarding your command line, reverse complements and paired-end make things a little bit more complicated.

When I wrote `-a A_revX` above, I did not mention that you should actually provide the reverse complement of `A_rev`. Cutadapt needs all the sequences that you give it to be in the orientation in which they occur in a read.

Also, I forgot to mention that I was assuming the sequencing direction is always from "left to right", but since you have fragmentation, that is probably not the case. As a consequence, you need to consider the case where the read is reverse-complemented relative to the drawing above. 

So if this were single-end data, I think you would need this:
```
-a file:revcomps_of_reverse_primers.fa
-a file:revcomps_of_forward_primers.fa
-g file:forward_primers.fa
-g file:reverse_primers.fa
```
To simplify, put all primers (each prefixed with `X`) into a single `primers.fa` and all reverse primers into a single `reverse_primers.fa` (each suffixed with `X`) and use a single `-a` option and a single `-g` option:
```
-a file:revcomps_of_primers.fa
-g file:primers.fa
```
Finally, to trim paired-end data, you can then use the same files with the uppercase versions of these options:
```
cutadapt ... \
-a file:revcomps_of_primers.fa \
-g file:primers.fa \
-A file:revcomps_of_primers.fa \
-G file:primers.fa \
```
After running Cutadapt, check the report to see whether all of the adapters/primers actually get found because I haven’t tested this myself.

Note also that the `--prefix` option is outdated and you should use `--rename` instead. If you use `--rename` with paired-end reads, Cutadapt ensures that the read identifiers of paired-end reads are identical even after renaming. With the older `--prefix` option, it doesn’t do that and read ids may not match. In your case, (prefixing the name of the found adapter), they will actually not match most of the time. Some tools will then complain or you get confusing results.

**Comment by charlesfoster** [comment]
@marcelm thanks for the detailed reply (again)!

I'm planning on comparing the BAM files both with and without `cutadapt` trimming to see the effect. I'm hopeful that the trimming will work well because I've seen some instances recently where improperly trimmed primers led to a variant being missed in a primer region, which, in turn, affected the public health implications (SARS-CoV-2, but the current virus I'm working with is different).  I've tried the following command now:

```
cutadapt -j0 \
-a file:revcomps_of_primers.fa \
-g file:primers.fa \
-A file:revcomps_of_primers.fa \
-G file:primers.fa \
--rename '{id} adapter={adapter_name} {comment}' \
--action lowercase \
-o trimmed_R1.fq.gz \
-p trimmed_R2.ffq.gz \
$R1 $R2
```
(after observing the soft clipping, I'll modify the command to remove `--action lowercase`. 

When I have time, I'll compare the mapping and variant calling to non-`cutadapt`ed reads. I can report back with some results if of interest, otherwise this can probably be closed because the command you provided should work :)

**Comment by marcelm** [comment]
> I'm hopeful that the trimming will work well because I've seen some instances recently where improperly trimmed primers led to a variant being missed in a primer region,

I wasn’t aware that this could be an issue, that is very interesting! (And will keep it in mind when I make future recommendations.)

Closing this now because I want to tidy up the issue list a bit before the next release.
