### ISSUE TITLE
Anchored linked adapter, but allowing smaller overlaps

### ISSUE THREAD

**Issue by marlaux** [marcelm/cutadapt#551]
Hello Marcel, I hope you are doing fine
About a year ago we talked about using linked adapter for an unusual Ion Torrent dual index design (issue #400), do you remember?
- cutadapt/2.10 and Python-3.8.2
- Installed in server with slurm queue system

The default minimum tag overlap described in Cutadapt user guide is 5 matches (-O 5), but in the Cutadapt --help it says default 3. I'm losing a lot of sequences because this and -O argument is not working for me, or I'm doing wrong at all. I've been checking and several trimmed sequences were actually with the right tag pair, however discarded because the minimum overlap. Two examples below:
gttgGGAGCCCGC...TTCACAgaaatgaagtgc
ttgTGAATTGCA...AAGCGGGgaaatgaagtgc
both "gttg" and "ttg" are the tail of the the right matching tags and I've been trying to make Cutadapt keep them with -O 3, but unsucessfully. 
How could I do that? keep the amplicon when at least 3 sequential "tail" tag bases are correctly linked and attached to the amplicon? I mean "tail" because for me it happened in the 5' end of the amplicons, but it could be in the 3' end also, eventually, I figure...
The demultiplexing is generally working ok the way I am running it:
`### demultiplex Ion dual indexed (Linked Adapter) ###
INPUT="Amplicons_530chip_30pM.fastq"
PAIR1="Barcodes_alt1anch.fa"
PAIR2="Barcodes_alt2anch.fa"
PAIR3="Barcodes_alt3anch.fa"
PAIR4="Barcodes_alt4anch.fa"
cutadapt        \
        -a file:${PAIR1}        \
        -a file:${PAIR2}        \
        -a file:${PAIR3}        \
        -a file:${PAIR4}        \
        -o "{name}_ion_LA_both_anch.fq"  \
        --action=lowercase      \
        ${INPUT}
`
The Barcodes in "-a file:${PAIR1}" were customized specifically for this design, with the help of the sequencing lab technician, who oriented me to search for 4 exact tag pairs alternatives, in accordance to the Ion Torrent library tag-primers attachment possibilities.
I wrote a script to create those 4 barcode files, the script is available here: [https://github.com/marlaux/Metabarcoding-script-by-script/blob/3b7a9ed16358dcc7a3dba006377e34303ebfbce3/2_demulti/preparing_tags_LCPI.pl](url)

Is there a way to solve this?
Thank you very much
Best

**Comment by marcelm** [comment]
> The default minimum tag overlap described in Cutadapt user guide is 5 matches (-O 5), but in the Cutadapt --help it says default 3.

The `--help` text is correct: The default is 3. I guess you read it in the table [in the section about the adapter-trimming parameters](https://cutadapt.readthedocs.io/en/stable/guide.html#adapter-trimming-parameters), but the `-O 5` I put there was just meant as an example. This was a bit confusing, and I have tried to make this a bit clearer now.

I have a couple of questions.

- You say that sequences were discarded. With that, did you man that they ended up in the `unknown_...fq` file?
- Can you clarify the example `gttgGGAGCCCGC...TTCACAgaaatgaagtgc`. Is that the input sequence? (Because you used `--action=lowercase`, this could also be an output sequence. Did you change the characters to lowercase manually?)
- How did you specify the linked adapters in the FASTA file? Did you use any "anchoring" characters `^` or `$`?

I don’t think I fully understand your setup, but it appears that you want your tags to be found even if a couple of bases are missing in the beginning (for the 5' tag). If that is the case, you should not anchor the 5' tag, that is, you need to specify the linked adapter without the `^` as the first character. How long are the tags and how many bases do you expect to be missing sometimes?

You may also need to use the `-g` instead of the `-a` option, but I can probably only say that when I know a bit more about the setup.

If necessary, you can specify a minimum overlap length separately for the 5' and 3' parts of a linked adapter like so:
`-a ACGT;min_overlap=7...TTAAGGCC;min_overlap=5`
