### ISSUE TITLE
trims more than adapter length

### ISSUE THREAD

**Issue by therealgenna** [marcelm/cutadapt#566]
Hi,

I used cutadapt 3.2 with Python 3.8.6 (installed through conda) for the following fastq (tmp.fq) with one read:
```
@NAME
AAAAAAAAAAAAAAAGTGAACTAATGCTTTAATGCTATTGCGATCTTTCTG
+
GGGGGIIIIIIIIIIGGGGGGIGIIIIGGGIGGIIIGIIIIIIIIGIIGGA
```
with the following command:
`cutadapt -g "XAAAAAAAAAAAAAAAA;e=0.34" tmp.fq`

Why does it trim 19 bases from 5' when the adapter is only 16 bases long [full output is below]? Especially when the last trimmed are mostly not A bases

Also, generally I am trying to remove polyA stretches at the 5' ends of reads, which often have N bases in addition to A, and I don't want to go beyond 16 bases. What's the right way to do it?

Thank you

Here is the cutadapt output:
```
This is cutadapt 3.2 with Python 3.8.6
Command line parameters: -g XAAAAAAAAAAAAAAAA;e=0.34 tmp.fq
Processing reads on 1 core in single-end mode ...
[8<----------] 00:00:00             1 reads  @   1523.3 µs/read;   0.04 M reads/minute
Finished in 0.00 s (3796 µs/read; 0.02 M reads/minute).

=== Summary ===

Total reads processed:                       1
Reads with adapters:                         1 (100.0%)
Reads written (passing filters):             1 (100.0%)

Total basepairs processed:            51 bp
Total written (filtered):             32 bp (62.7%)

=== Adapter 1 ===

Sequence: AAAAAAAAAAAAAAAA; Type: non-internal 5'; Length: 16; Trimmed: 1 times

No. of allowed errors:
1-1 bp: 0; 2-4 bp: 1; 5-7 bp: 2; 8-10 bp: 3; 11-13 bp: 4; 14-16 bp: 5

Overview of removed sequences
length	count	expect	max.err	error counts
19	1	0.0	5	0 0 0 1
@NAME
ACTAATGCTTTAATGCTATTGCGATCTTTCTG
+
GGIGIIIIGGGIGGIIIGIIIIIIIIGIIGGA
```

**Comment by therealgenna** [comment]
I guess I need to add `--no-indels` flag - then I get
```
Overview of removed sequences
length	count	expect	max.err	error counts
15	1	0.0	5	1
@NAME
GTGAACTAATGCTTTAATGCTATTGCGATCTTTCTG
+
GGGGGGIGIIIIGGGIGGIIIGIIIIIIIIGIIGGA
```

But can I provide `--no-indels` on a per-adapter basis? In general, I have multiple adapters in my real command. Also, what exactly the error counts mean? Above, I had `0 0 0 1`, so I assume the last one is for indel(s); what are the first three?

Thank you

**Comment by marcelm** [comment]
As you found out, indels are the explanation for the 19 bp sequence being trimmed.

> which often have N bases in addition to A

You may want to use `--match-read-wildcards` (but note that if you then have a read consisting mostly of `N` bases, an adapter will essentially match anywhere in it).

> But can I provide --no-indels on a per-adapter basis?

No, but it would be good if it were supported. I have opened #567 for this. As a workaround, you would need to run Cutadapt twice, once with the adapters that you want to allow indels for and once for those for which you want `--no-indels`.

> Also, what exactly the error counts mean? Above, I had 0 0 0 1, so I assume the last one is for indel(s); what are the first three?

This is a breakdown of what is in the `count` column by the number of errors in the match. Let’s say you have `7 5 3` here and length = 15. Then this means that
* 7 sequences of length 15 were removed due to an adapter match containing 0 errors
* 5 sequences of length 15 were removed due to an adapter match containing 1 error
* 3 sequences of length 15 were removed due to an adapter match containing 2 errors

In your case with `0 0 0 1`, it means that the match that caused the sequence of length 15 to be removed had 3 errors.

There’s no breakdown by insertions/deletions/mismatches.

**Comment by therealgenna** [comment]
Ah, I see. Thank you very much for such a prompt and detailed response. I'll check the `--match-read-wildcards`.
