### ISSUE TITLE
Cutadapt as a python module - recommendations

### ISSUE THREAD

**Issue by CCranney** [marcelm/cutadapt#568]
Hi, I'm rewriting a series of bash scripts (see GitHub repository [here](https://github.com/SorenKarst/longread_umi)) into a python package for easier maintainability and usability. The bash scripts rely heavily on cutadapt, so I'm exploring whether or not I can use cutadapt as a python module rather than from the command line.  The current scripts generate a large number of intermediary files for cutadapt input and output, and I'd like to avoid that moving forward. I've experimented with doing so, but after running into several errors thought I'd ask if this was a recommended course of action.

At a base level, would you discourage developers from using cutadapt as a python module? I'm providing a basic summary of what I'm trying to accomplish below for context, and would welcome any tips if you feel this is a doable task, though I'm primarily asking if you would recommend such in the first place.

Given a string sequence, I'm trying to extract an 18bp sequence from between two linked adapter sequences. In my code [here](https://github.com/JGEnglishLab/longread_umi_python/blob/CutAdaptPython/umi_binning.py) I've managed to extract a sequence of undetermined length using cutadapt's LinkedAdapter and related classes, but haven't succeeded in utilizing cutadapt's filtering methods to identify the best 18bp sequence, should one exist.

**Comment by marcelm** [comment]
I’d love to have a proper Python-level API for Cutadapt, and I’ve done a lot of refactoring to make that possible. For example, I split out `xopen` and `dnaio` into separate packages so that they would be usable on their own. For the rest of Cutadapt, I’m not quite there in my opinion, and because of that, there’s no API documentation and I don’t make guarantees about API backwards compatibility. So if you do go down that route, you’d have to pin the Cutadapt version or would need to ensure that you test it with newer Cutadapt releases.

That said, I have made the adapter classes a bit nicer last year, and the interface for them is probably going to stay the way it is. I would suggest, though, that you avoid the `AdapterParser` and its `parse_multi` method. It’s necessary for interpreting what the user meant on the command line, but in Python, you can express more clearly what you want by instantiating the adapter classes directly, somewhat like this:
```
fwd_adapter = FrontAdapter("ACGT", max_errors=2)
rev_adapter = BackAdapter("GGAATT", min_overlap=5)
linked_adapter = LinkedAdapter(fwd_adapter, rev_adapter, front_required=True, back_required=False, name="alinkedadapter")
```
(Writing this down, I think I’ll need to make the "name" argument optional.)

Even if you don’t end up using the API in the end, I would like to hear more about your particular use case because I keep a document with use cases that the API should enable. What do you mean by "utilizing filtering methods" and "best 18bp sequence"? If you want to determine which of a number of adapters best matches a read, you can use the `MultipleAdapters` class.

**Comment by CCranney** [comment]
This is perfect, thank you so much! In hindsight after reading through your post, I think I was making the matter more complicated than it needed to be. I was looking into using classes like `AdapterCutter` in addition to `AdapterParser`, and I think that was leading me down some unnecessary rabbitholes. I'm going to go ahead and implement cutadapt using the API, but I'll try to stick to using the `Adapter` child classes.

My use case is for a method introduced in the SorenKarst Github repository linked above to enhance the accuracy of nanopore sequencing. In this method, desired nucleotide sequences are tagged on both ends with random unique molecular identifiers (UMIs). Each UMI is a (mostly) random 18bp sequence, and is sandwiched between two known, linked adapter sequences. These full, dual tagged nucleotide sequences are then amplified with PCR and run through the nanopore sequencer. Because the original sequence had a unique forward UMI tag and a unique reverse UMI tag, all of its amplified copies will have the same UMI-UMI pairing. The part I am trying to replicate now, called UMI binning, is to find sequences with identical UMI pairs and bin them together so I can generate an accurate consensus sequence.

I'm using cutadapt to extract the forward and reverse UMIs from each sequence so I can bin it appropriately. In the SorenKarst test script, they used the following code as a command line argument:

```
$CUTADAPT -j $THREADS -e 0.2 -O 11 -m 18 -M 18 \
  --discard-untrimmed \
  -g $FW1...$FW2 -g $RV1...$RV2 \
  -G $RV2R...$RV1R -G $FW2R...$FW1R \
  -o $UMI_DIR/umi1.fq -p $UMI_DIR/umi2.fq \
  $UMI_DIR/reads_tf_start.fq $UMI_DIR/reads_tf_end.fq
```

with variables $FW1 being the sequence of the first forward adapter, $FW1R being it's reverse complement, and so on. I managed to extract UMI sequences using the `LinkedAdapter` class, but noticed there were often UMI sequences that were longer than 18bp in length. I was investigating if I could use the code triggered by the `-m` or `-M` flags to filter out incorrect lengths of UMI sequences. I could do that myself pretty easily, bit I wasn't sure how multiple matches on the same string might exclude the correct UMI sequence over a more-accurately-identified longer UMI sequence. For example, if I filtered out a more accurate UMI match that was perhaps 25bp long I might accidentally ignore a second, unreported match on the same string that was the correct 18bp long. I think my rabbithole journeys were based around tracing the `-m` and `-M` flag logic, when I'll probably just need to ignore UMIs of the incorrect length for the time being - unless I missed something crucial in the `Match` child classes that tracks multiple matches?

That's the gist of this stage of the project. I should be able to make it work with the `Adapter` classes, but I hope it illustrates the use case!

**Comment by marcelm** [comment]
>  The part I am trying to replicate now, called UMI binning, is to find sequences with identical UMI pairs and bin them together so I can generate an accurate consensus sequence.

Cool, I’ve done something similar in another project (but with Illumina sequences).

> I'm using cutadapt to extract the forward and reverse UMIs from each sequence so I can bin it appropriately. In the SorenKarst test script, they used the following code as a command line argument:
> 
> ```
> $CUTADAPT -j $THREADS -e 0.2 -O 11 -m 18 -M 18 \
>   --discard-untrimmed \
>   -g $FW1...$FW2 -g $RV1...$RV2 \
>   -G $RV2R...$RV1R -G $FW2R...$FW1R \
>   -o $UMI_DIR/umi1.fq -p $UMI_DIR/umi2.fq \
>   $UMI_DIR/reads_tf_start.fq $UMI_DIR/reads_tf_end.fq
> ```
> 
> with variables $FW1 being the sequence of the first forward adapter, $FW1R being it's reverse complement, and so on. I managed to extract UMI sequences using the `LinkedAdapter` class, but noticed there were often UMI sequences that were longer than 18bp in length. I was investigating if I could use the code triggered by the `-m` or `-M` flags to filter out incorrect lengths of UMI sequences.

The `-m` filter is essentially just an `if len(read) < threshold: continue`. For paired-end reads, it is `if len(r1) < threshold or len(r2) < threshold: ...`. Writing that yourself is indeed easier than trying to set up the `Filter` classes properly.

> I could do that myself pretty easily, bit I wasn't sure how multiple matches on the same string might exclude the correct UMI sequence over a more-accurately-identified longer UMI sequence. For example, if I filtered out a more accurate UMI match that was perhaps 25bp long I might accidentally ignore a second, unreported match on the same string that was the correct 18bp long.

Yes, that is a good point. Finding the best adapter that matches and length filtering are independent steps in Cutadapt, so if you first trim the best-matching adapter and then filter by length, you’ll get the same results as the command line would give you.

(A nice feature I’ll have to keep in mind would be if Cutadapt allowed to constrain the number of bases between the forward and reverse adapter.)

Do you expect the read to start with the 5' adapter? If so, you should use an anchored 5' adapter. And perhaps you do this already, but you could then slice your sequence *before* matching the adapter against it, setting it to the length of the of the forward adapter plus 18 plus the length of reverse adapter, perhaps with some slack depending on whether you allow indels or not.

> I think my rabbithole journeys were based around tracing the `-m` and `-M` flag logic, when I'll probably just need to ignore UMIs of the incorrect length for the time being - 

Simple filtering I think that is easiest and my gut feelin is that you don’t lose much. You could even argue that those reads that you filter out although you could have saved them are those where something fishy is going on anyway and not using would be a good choice.

> unless I missed something crucial in the `Match` child classes that tracks multiple matches?

No, each instance only tracks a single match.

> That's the gist of this stage of the project. I should be able to make it work with the `Adapter` classes, but I hope it illustrates the use case!

Thanks, that was insightful and got me thinking again about how best to design the API. Good luck!

Closing this now because I answered the question, but I added some notes to a document I keep elsewhere.
