### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by vinkwok** [marcelm/cutadapt#569]
Hello, I was trying to install the cutadapt using pip.  Specifically I was under the python 3.6.8 version, I used the following code to install cutadapt
`pip3 install cutadapt --user`

But it report an error 
`Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/work/tmp/pip-build-99qf2cmx/isal/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-7kbwjcaz-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /work/tmp/pip-build-99qf2cmx/isal/`

I guess the problem is due to the dependency, so I run the following code to install tokenize (which is import in the previous error message)

`pip3 install tokenize --user`

and the error message is

`Collecting tokenize
  Could not find a version that satisfies the requirement tokenize (from versions: )
No matching distribution found for tokenize`

May I ask if you can share some wisdom on this installing issue?

Thanks in advance!

**Comment by marcelm** [comment]
`tokenize` is a built-in Python library which cannot be pip-installed, so that is not the problem. You did not share the full error message, but there is something about `isal` in the section you posted. I believe the problem occurs because this dependency of Cutadapt is not available as a binary package (wheel) for your combination of Python and pip versions, so pip tries to compile it from sources. That fails because you don’t have the necessary development packages installed.

This would be a good opportunity to start using Conda, which will not lead to these types of problems!

If that is not an option at the moment, I think the safest way to solve this is to install Cutadapt into a virtual environment:
```
python3 -m venv cutadapt-venv
cutadapt-venv/bin/pip install --upgrade pip
cutadapt-venv/bin/pip install cutadapt
```
To run Cutadapt, you’ll then need to write `cutadapt-venv/bin/cutadapt` (you can also create a symlink in `~/.local/bin/` that points to that file).

@rhpvorderman We’d need a Python 3.6 manylinux1 wheel of python-isal to avoid this in the future. Are you planning a new release anytime soon? Then we’d benefit from your work in pycompression/python-isal#93.

**Comment by vinkwok** [comment]
Thanks for the explanation! It's resolved!
