### ISSUE TITLE
demultiplexing with indicies in different file

### ISSUE THREAD

**Issue by FabianRoger** [marcelm/cutadapt#578]
Hi,

I have raw illumina data (paired-end) with dual indices. In total I have 4 files: a forward file (R1) a reverse file (R2) a forward index file (I1) and a reverse index file (I2). I believe this is standard for raw illumina data. However it means that the indices are not included in the reads but in separate file(s). 

Doe cutadapt support demultiplexing in this situation? It would need to read the indices from seperate files and then filter based on line numbers I guess. No trimming required.  

Right now I do it with a custom R script but it's not terribly efficient and doesn't allow for missmatches...

**Comment by marcelm** [comment]
That’s unfortunately not possible directly with Cutadapt, at least at the moment. I’m not sure supporting this would fit so well into the way the tool is structured at the moment because a lot is based on the fact that there are one or two input files.

As a workaround, you could concatenate all sequences from I1 with its corresponding sequence in R1 and the same for I2/R2, then use Cutadapt to demultiplex and finally remove the added index sequences again. It’s a bit ugly, but you would get error tolerance.

It may also be an idea to write a Python script that uses the appropriate functions in Cutadapt. If you don’t need multithreading, that would probably be a relatively short script.

**Comment by FabianRoger** [comment]
I fully understand. Yes I have thought about the cat solution, it would probably work. 

However I found a specialized tool written for this situation and with a better error model (using PHRED scores) here: [https://biosails.github.io/pheniqs/](https://biosails.github.io/pheniqs/), in case anybody is interested. 

From a first check, it seems to work well (only 6% of my reads discarded vs 15% when not allowing any error tolerance)

Thanks for the quick reply!

**Comment by marcelm** [comment]
Yes, using a different tool is probably a good idea in this case. Thanks for the pointer, will have a look.
