### ISSUE TITLE
Different results with the same command

### ISSUE THREAD

**Issue by amitjavilaventura** [marcelm/cutadapt#595]
Dear Marcel,

I am currently using cutadapt v. 3.5 (from a singularity image) to run a pipeline in a cluster. I have previously used v. 3.4 (locally) and it was working perfectly. 

However, using the same command I am experiencing issues, since the resulting "trimmed" fastq files are very different in size. For example, the original file is 1.8Gb, the trimmed file with v3.4 is 1.5Gb and the trimmed file is 1.2Gb. Then, if I want to map those reads in the genome using bowtie and samtools, the resulting bam has a size of kb, when it normally would be several gb. 

The command command is: 

Locally (old pipeline): 
```
cutadapt -a TGGAATTCTCGGGTGCCAAGGAACTCCAGTCAC -O 9 -j 0 -m 19 -M 36
     --trimmed-only -o <output> <input>
```

Cluster with singularity (new pipeline): 
```
singularity exec <sing_image> \
cutadapt --cores 0 \
     -a <adapter> \
     --overlap 9 \
     --minimum-length 19 \
     --maximum-length 36 \
     --trimmed-only \
     --output <output> \
     <input> 
```

In both cases the options are the same (I use the spelled versions in the new pipeline), and the only difference is that the adapter is not hard-coded in the new pipeline (it depends on the sample to be trimmed, although it is the same for all the samples). 

I think the version is not the problem, since using the v3.4 in the cluster (out of the singularity image) gives the same results as v3.5. So it is possible that the error is coming from the environment? Could by different python versions (or anything else) or is there something different in the commands?

I have not seen any error. The only thing that I have seen is an EOF error when using subsets of the original fastq files. 

Now I am rerunning the same pipeline locally to see whether I have the same result or not.

If you know the source of these differences, I would be very grateful if you can share your suggestions.

Thank you very much.

Adrià.

**Comment by marcelm** [comment]
What does the report say in both cases? Are any of the numbers different?

Is the output compressed?

**Comment by marcelm** [comment]
So first I would want to find out in which way the files are different. Some reasons for size differences:
- One file was truncated (because the disk got full, for example)
- Compression was different
- The filtering was done differently
- The trimming was done differently

If you still have the reports, that would be the most important place to look.

Another thing you can do is to check the number of lines in the files with `zcat file.fastq.gz | wc -l`.

You can also try to run Cutadapt on the two files, pretending that they are paired-end reads: `cutadapt --interleaved -o /dev/null file1.fastq file2.fastq` Cutadapt will check whether the read names match and complain if they aren’t. That will allow you to see if the read filtering was done differently in both files (then you get an error about non-matching read names) or whether one of the files is truncated (then you get a different error).

**Comment by amitjavilaventura** [comment]
Hello,

Thank you for the quick answer. 

Both the input and the output are compressed in both cases, locally and the singularity. The only difference is that locally I used the original file, whereas in the cluster first I copy it with `cp` to the pipeline directory.

Regarding the reports, both look equal.

Now I see the "error". Basically, in the pipeline there is a step that requires decompressing the fastq.gz. In the old pipeline I do `gunzip` and later `gzip --fast`. In the current one I do `zcat fastq.gz > tmp.file`, so yes, the compression is different. Nevertheless, I still have an error in producing the BAM files, but it is not due to the FASTQs _per se_.

Sorry for the silly error.

Adrià.

**Comment by marcelm** [comment]
Ok, so do I understand correctly that this is no longer anything that has to do with Cutadapt?

**Comment by amitjavilaventura** [comment]
In theory, it does not have anything to do with Cutadapt.
