### ISSUE TITLE
Discard output file garbled when used for multiple filter cases

### ISSUE THREAD

**Issue by ressy** [marcelm/cutadapt#607]
When I specify the same path for both `--too-short-output` and `--untrimmed-output`, the records aren't cleanly separated in the output.  With a fastq.gz output path the gzip data itself gets garbled, so it's more immediately obvious, but I think that's just a side-effect of the conflicting writes to the same file.

For example, with this input:

```
@read1
AAAAAAAATTTTTTTTGGGGGGGG
+
IIIIIIIIIIIIIIIIIIIIIIII
@read2
AAAAAAAATTTTTTTT
+
IIIIIIIIIIIIIIII
@read3
GGGGGGGG
+
IIIIIIII
@read4
AAAAAAAA
+
IIIIIIII
```

This works OK, with two extra fastq outputs with one read each:

```
cutadapt -g ^AAAAAAAA --untrimmed-output untrimmed.fastq --too-short-output short.fastq --minimum-length 5 -o trimmed.fastq.gz input.fastq.gz
```

But this doesn't work as I'd expect, because trash.fastq ends up looking strange:

```
cutadapt -g ^AAAAAAAA --untrimmed-output trash.fastq --too-short-output trash.fastq --minimum-length 5 -o trimmed.fastq.gz input.fastq.gz
```

What I get in trash.fastq:

```
@read4

+

GGGG
+
IIIIIIII
```

If I add `--maximum-length 12 --too-long-output trash.fastq` I get *only* the too-long read in the output, and not the too-short or untrimmed ones.  So it looks to me like the different outputs are stepping on each other's toes here.  (Maybe this is a weird use case, but it could halt and complain at the start if this is unsupported, I'm thinking?)

This is with Cutadapt 3.7 and Python 3.9.10 installed via conda.

**Comment by marcelm** [comment]
Hi, this is indeed not supported at the moment. I have now changed it so that Cutadapt prints an error message when an output file is specified multiple times. I think this is the best I can do at the moment because I think that getting this to work reliably may require some deeper changes to the way in which files are opened. In particular, the way files are opened when running on multiple cores embeds the assumption of unique output files quite deeply.

That said, I keep refactoring the code somewhat regularly and I’ll try to keep this use case in mind. Perhaps it becomes doable.

**Comment by ressy** [comment]
Thanks!  Not at all a pressing need for me so the new behavior looks like a fine fix as far as I'm concerned.
