### ISSUE TITLE
Discard read if more than one adapter is detected

### ISSUE THREAD

**Issue by iquasere** [marcelm/cutadapt#611]
If there any way to discard reads that have more than one adapter with the maximum score? Or is the first found always the one kept?

**Comment by marcelm** [comment]
The alignment algorithm stops early when it finds an exact adapter match while searching the read left to right. That means that the information of whether there is a second occurrence is not available.

Perhaps you could run Cutadapt multiple times. Something like this might work:
```
cutadapt -a ADAPTER --untrimmed-output zero.fastq -o oneplus.fastq input.fastq
cutadapt -a ADAPTER --untrimmed-output exactlyonce.fastq -o twoplus.fastq oneplus.fastq
```
Then the output files would be as follows:
* Reads in `zero.fastq` contains zero adapter occurrences
* Reads in `oneplus.fastq` contain one or more adapter occurrences
* Reads in `exactlyonce.fastq` contain exactly one adapter occurrence
* Reads in `twoplus.fastq` contain two or more adapter occurrences.

If you don’t actually want to trim the adapters and therefore need `--action=none`, that won’t work like this, though, because the intermediate `oneplus.fastq` file needs to have the adapters removed.

Another option: If you know that the multiple occurrences are always adjacent, just search for `-a ADAPTERADAPTER`.

**Comment by iquasere** [comment]
Thank you for the detailed answer!
