### ISSUE TITLE
Adapter match - first match vs best match

### ISSUE THREAD

**Issue by anujg30** [marcelm/cutadapt#612]
Python 3.8.12
Cutadapt 3.7
Installation method: pip 

In my pipeline, I have a list of 300 barcodes of 10bp length. I allow for 2 errors (-e 0.2) including indels. I realized that cutadapt identifies the first match and not the best match. For example, a barcode 2 errors from a match and occuring first in barcode.fasta is used in output over barcode with 1 error from a match and occuring lower in barcode.fasta.

1. Is this correct observation? Or am I missing something?
2. Is there a workaround to get the best match (forcing cutadapt to evaluate all 300 barcodes)? I understand that this will cost time.

Thanks

**Comment by marcelm** [comment]
I may have more time to think about this tomorrow, but you can try using `--no-index` (undocumented command-line option).

**Comment by marcelm** [comment]
I believe what happens depends on whether an index is built for your adapters or not. Do you see a message "Building index of 300 adapters ..."? Then it’s possible that not the best match is found. This would be a bug and I think I can fix it without too much effort.

On the other hand, when no index is created for the barcodes, then the best match should always be found. The order of the barcodes should then matter only if there are multiple best matches with the same score. Then among those best matches, the first in the file would be reported.

**Comment by anujg30** [comment]
Here is an example of the possible bug:
Consider 2 barcodes in testrt.fa
`>372
^CAGAGCN{12}CCTTGTTCGA
>145
^CAGAGCN{12}CCTTGCCTTA`
Consider the read in test.fa
`>r1
CAGAGCAATATACCTTCGCCTTGCATTACGAGGACCGCTCTGATGCAGCCCTGTCTCTTATACACATCTCCGAGCCCACGAGACTCGCCGCCGGATCTCGTATGCCGTCTTCTGCTTGAAAAAAGGGGGGGGGGGGGGGGG`

To find and trim the barcode I run:
`cutadapt -g file:testrt.fa -e  0.2 test.fa`

The above command allows for 3 errors. Cutadapt identifies barcode 372 (with 3 errors) and not barcode 145 (with 1 error).

**Comment by marcelm** [comment]
Thanks for the good example!

So the good news is that this has already been fixed in the development version of Cutadapt. You can read an explanation in [the documentation](https://cutadapt.readthedocs.io/en/latest/algorithms.html#alignment-algorithm-changes-in-cutadapt-4). In short, Cutadapt 3.7 prefers the alignment with the highest number of matching nucleotides when deciding which one is better. In your case, let us ignore `N` wildcards of the barcodes (the problem still occurs). These are the two alignments it finds:
```
CAGAGCCCTTG--TT-CGA (barcode 372)
|||||||||||  || |||
CAGAGCCCTTGCATTACGAGGACCGCTCTGATG (read)
||||||||||||x|||
CAGAGCCCTTGCCTTA (barcode 145)
```
For barcode 372, there are 16 matches, and for barcode 145, there are only 15, so 372 is preferred. I totally agree this is unexpected, which is why I have changed the behavior.

> On similar lines, do substitution errors have preference over indels? For example, barcode hit with 1 substitution error is selected over barcode hit with 1 indel. In my tests, that appears to be the case but I wanted to confirm.

The algorithm in 3.7 does not always prefer substitutions, but the new one does.

I’ll release a new Cutadapt version with the changes very soon.
