### ISSUE TITLE
Statistics are incorrect when --nextseq-trim is combined with -q

### ISSUE THREAD

**Issue by marcelm** [marcelm/cutadapt#616]
`cutadapt -q 15,0`:
```
Total basepairs processed:   218,527,840 bp
Quality-trimmed:               7,116,934 bp (3.3%)
Total written (filtered):    211,410,906 bp (96.7%)
```
`cutadapt --nextseq-trim=20`:
```
Total basepairs processed:   218,527,840 bp
Quality-trimmed:              18,457,253 bp (8.4%)
Total written (filtered):    200,070,587 bp (91.6%)
```
`cutadapt -q 15,0 --nextseq-trim=20`:
```
Total basepairs processed:   218,527,840 bp
Quality-trimmed:                   2,155 bp (0.0%)
Total written (filtered):    200,068,432 bp (91.6%)
```
See #615

**Comment by ForestCat1** [comment]
Hi, Marcel! Many thanks for testing.
As your results, the statistics of the third test didn't match well with the first two. 

I think the correct statistics can be obtained by performing "--nextseq-trim=20" and "-q 15,0" with two sequential Cutadapt run (the output of the former as the input of the latter, vice versa), so I ran following test runs with pair-end data (cutadapt 3.7 installed by conda, with Python 3.8.12).

Although the statistics of "total written (filtered)" of test-run-1b, test-run-2 and test-run-3b are almost consistent, "Quality-trimmed" in test-run-2 is obviously incorrect.
-------------------------
-------------------------
#test-run-1a
```
cutadapt  \
	--no-indels --nextseq-trim=10 -m 36  \
	-a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA  \
	-A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT  \
	-o out.1a_1.fq.gz -p out.1a_2.fq.gz  \
	reads.R1.fq.gz reads.R2.fq.gz
```

Total basepairs processed: 5,831,026,500 bp
  Read 1: 2,915,513,250 bp
  Read 2: 2,915,513,250 bp
Quality-trimmed:              23,228,430 bp (0.4%)
  Read 1:     5,328,804 bp
  Read 2:    17,899,626 bp
Total written (filtered):  5,763,282,923 bp (98.8%)
  Read 1: 2,881,840,786 bp
  Read 2: 2,881,442,137 bp
-------------------------
#test-run-1b
```
cutadapt  \
	-q 15,0 -m 36  \
	-o out.1b_1.fq.gz -p out.1b_2.fq.gz  \
	out.1a_1.fq.gz out.1a_2.fq.gz

```
Total basepairs processed: 5,763,282,923 bp
  Read 1: 2,881,840,786 bp
  Read 2: 2,881,442,137 bp
Quality-trimmed:                 763,276 bp (0.0%)
  Read 1:       293,035 bp
  Read 2:       470,241 bp
**Total written (filtered):  5,762,505,140 bp (100.0%)**
  Read 1: 2,881,534,793 bp
  Read 2: 2,880,970,347 bp
-------------------------
-------------------------
#test-run-2
```
cutadapt  \
	--no-indels -q 15,0 --nextseq-trim=10  -m 36  \
	-a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA  \
	-A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT  \
	-o out.2_1.fq.gz -p out.2_2.fq.gz  \
	reads.R1.fq.gz reads.R2.fq.gz
```

Total basepairs processed: 5,831,026,500 bp
  Read 1: 2,915,513,250 bp
  Read 2: 2,915,513,250 bp
**Quality-trimmed:                 768,588 bp (0.0%)**
  Read 1:       294,449 bp
  Read 2:       474,139 bp
**Total written (filtered):  5,762,505,140 bp (98.8%)**
  Read 1: 2,881,534,793 bp
  Read 2: 2,880,970,347 bp
-------------------------
-------------------------
#test-run-3a
```
cutadapt  \
	-q 15,0 -m 36  \
	-o out.3a_1.fq.gz -p out.3a_2.fq.gz  \
	reads.R1.fq.gz reads.R2.fq.gz

```
Total basepairs processed: 5,831,026,500 bp
  Read 1: 2,915,513,250 bp
  Read 2: 2,915,513,250 bp
Quality-trimmed:                 776,621 bp (0.0%)
  Read 1:       294,454 bp
  Read 2:       482,167 bp
Total written (filtered):  5,830,239,897 bp (100.0%)
  Read 1: 2,915,209,501 bp
  Read 2: 2,915,030,396 bp
-------------------------
#test-run-3b
```
cutadapt  \
	--no-indels --nextseq-trim=10 -m 36  \
	-a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA  \
	-A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT  \
	-o out.3b_1.fq.gz -p out.3b_2.fq.gz  \
	out.3a_1.fq.gz out.3a_2.fq.gz
```

Total basepairs processed: 5,830,239,897 bp
  Read 1: 2,915,209,501 bp
  Read 2: 2,915,030,396 bp
Quality-trimmed:              23,219,314 bp (0.4%)
  Read 1:     5,328,715 bp
  Read 2:    17,890,599 bp
**Total written (filtered):  5,762,507,114 bp (98.8%)**
  Read 1: 2,881,536,138 bp
  Read 2: 2,880,970,976 bp
-------------------------
-------------------------
I feel sorry that I don't know why incorrect statistics appeared in your test run #3 and my test run #2, and two sequential Cutadapt runs as above are at least acceptable for me (because the statistics of these sequential runs are understandable).

**Anyway, thanks a lot for your reply! I hope the debugging goes well :)**
-------------------------
-------------------------
-------------------------
(By the way, I'm not sure whether I directly reply to #615 can cause that closed issue re-open, so here I add my comment about your reply in #615:
As you said, toward the unexpected error counts of my anchored 5'- adapter, "the reported error counts actually show the total number of errors (errors in the 5' adapter plus errors in the 3' adapter)".

So do you mean the 4 numbers of 5'- error counts in **that report** refer to
trimed time of 0-error 5'- adapter;
trimed time of 1-error 3'- adapter;
trimed time of 2-error 3'- adapter;
trimed time of 3-error 3'- adapter, respectively? (**In other words, the 5' trimmed time is 32981415 rather than 32999357, right?**)

Here is what I called **that report**:
=== First read: Adapter 1 ===

Sequence: RECsite1...RECsite2AGATCGGAAGAGCACACGTCTGAACTCCAGTCA; Type: linked; Length: 6+39; 5' trimmed: 32999357 times; 3' trimmed: 602797 times

Minimum overlap: 6+9
No. of allowed errors: 0

No. of allowed errors:
1-9 bp: 0; 10-19 bp: 1; 20-29 bp: 2; 30-39 bp: 3

Overview of removed sequences at 5' end
length count expect max.err error counts
6 32999357 8110.2 0 *32981415 14556 2551 835*

Overview of removed sequences at 3' end
(omitted)

**Comment by ForestCat1** [comment]
Oh, the layout of last comment seems so strange, sorry for the inconvenience.

**Comment by marcelm** [comment]
> I think the correct statistics can be obtained by performing "--nextseq-trim=20" and "-q 15,0" with two sequential Cutadapt runs (the output of the former as the input of the latter, vice versa),

Yes, the problem appears only when combining the two options in one run. And note that the trimming itself is done correctly, it’s just the statistics that are off.

> (By the way, I'm not sure whether I directly reply to #615 can cause that closed issue re-open, so here I add my comment about your reply in #615: As you said, toward the unexpected error counts of my anchored 5'- adapter, "the reported error counts actually show the total number of errors (errors in the 5' adapter plus errors in the 3' adapter)".
> 
> So do you mean the 4 numbers of 5'- error counts in **that report** refer to trimed time of 0-error 5'- adapter; trimed time of 1-error 3'- adapter; trimed time of 2-error 3'- adapter; trimed time of 3-error 3'- adapter, respectively? (**In other words, the 5' trimmed time is 32981415 rather than 32999357, right?**)

Hm, I don’t think that’s how it was, but to be honest, I have "only" fixed it and haven’t spent time on trying to figure out in which way it was wrong. Just install the development version of Cutadapt or wait for the next release and you’ll have the right numbers.

**Comment by marcelm** [comment]
The problem this issue is about has also been fixed.

**Comment by ForestCat1** [comment]
> The problem this issue is about has also been fixed.

That's great! Thank you!
