### ISSUE TITLE
filtered output reads have different lengths

### ISSUE THREAD

**Issue by Jigyasa3** [marcelm/cutadapt#618]
Hey all,

I using cutadapt on some publicly available 16S raw reads. As, I don't have the adapter sequence information, I decided to cut the first 15 bps directly and quality filter based on PHRED score.

code used-
#remove the first 15bps and reads below quality 19 and all readlengths to 150bps-
`cutadapt -u 15 -q 19 -l 150 -o ${OUT_DIR}/${file2} ${IN_DIR}/${file1}`

When I use the filtered  reads for downstream OTU clustering methods `deblur` and `dada2`, I am getting the following error-

#for `deblur`-
`ValueError: Not all sequence have the same length. Aligned lengths: 4069, sequence lengths: 128, 129, 130, 131, 132, 133, 134, 135, 136, 122, 123, 124, 125, 126, 127`

#for `dada2` (no. of ASVs per read length)
`  131   132   133   134   135   136`
 `   4    12    66   468  1272 24187`

I also ran dada2 read filtering, and that seems to be running without generating this error, suggesting that cutadapt is producing reads of different lengths. 
Any suggestions?

##Information-
I am using Cutadapt 1.18 and Python version 3.5.2
I used pip to install the tool

**Comment by marcelm** [comment]
The `-q 19` option [trims off low-quality bases from each read](https://cutadapt.readthedocs.io/en/latest/guide.html#quality-trimming), so sufficiently bad reads become shorter than 150 bp. The `-l 150` option only affects reads that are longer than 150 bp so you get some reads that are shorter in the end.

If the tools you use require identical-length reads, you can use Cutadapt with option `-m 150` to discard reads that are shorter than 150 bp. But make sure you don’t lose too many reads that way.

One remark regarding your Cutadapt and Python versions: Cutadapt 1.18 is super old and has bugs that have been fixed in more recent versions. The reason you get that old version may be that your Python version is also quite old. Both 3.5 and 3.6 are end-of-life now. Don’t worry about it too much at the moment, the command you showed should work fine, but if you get any weird output or strange statistics you cannot explain, you should update.

**Comment by marcelm** [comment]
Closing this now since there hasn’t been a response. I hope you got it working and let me know if there are any open questions!
