### ISSUE TITLE
Cutadapt adapter trimming with error behavior 

### ISSUE THREAD

**Issue by pkhoueiry** [marcelm/cutadapt#619]
I would like to understand why cutadapt trimmed an 8 bp sequence from the read below

`cat in.fastq`

@A00278:129:HFKCGDRXX:1:1101:1904:1031 1:N:0:TAGGCATG+CTCTCTAT
GTGGATGCCCTGGCAGTCAGAGGCGATGAAGGGCGTGCTAATCTGCGATAAGCGCCGGTAAGGTGATATGAACCGTTATAACCGGCGATACCCGAATGGGG
+
FFFFFFFFFFFFFFFFFF:FFFFFFFF:FFFFFF:FFFFFFFFFFFFF:FFFFF:FFFFFFFFFFFFFFFFFFFF:FF:F:FFFFFFFFFFFFFFF::F:F

Here is the command used

`cutadapt -j 10 -u 20 -u -3 -m 20 -q 30 -a "A{100}" -g GATGGTTGAGGATGTGTGGAGNNNNNN -o o.fastq in.fastq
`

The output is the following:
GTGGATGCCCTGGCAGTCAG: Trimmed by -u 20
**AGGCGATG**: Trimmed for matching the adapted 2 (-g GATGGTTGAGGATGTGTGGAGNNNNNN) ?
AAGGGCGTGCTAATCTGCGATAAGCGCCGGTAAGGTGATATGAACCGTTATAACCGGCGATACCCGAA: Kept
TG: Trimmed for low quality 
GGG: Trimmed by -u -3

**I don't understand why the "AGGCGATG" was trimmed. It does have 3bp match with the adapter, reason for which it was considered, but I find this behaviour penalising as this sequence, and many others that I checked, are real genomic sequences** 

**Also, the log shows only 1 error. I am curious to know how is this the case**

Cutadapt is removing sequences with partial match with the adapter, independent of the position of the match and independent of the size of the query sequence that match, as long as a 3bp of the query match with the adapter sequence. The 2 errors tolerated, are calculated based on the adapter sequence length, and not that of the alignment between sequence that is going to be trimmed  and the adapter (8 bp here). 

This is cutadapt log

```
This is cutadapt 4.0 with Python 3.9.9
Command line parameters: -j 10 -u 20 -u -3 -m 20 -q 30 -a A{100} -g GATGGTTGAGGATGTGTGGAGNNNNNN -o o.fastq in.fastq
Processing single-end reads on 10 cores ...
Done           00:00:00             1 reads @ 35959.7 µs/read;   0.00 M reads/minute
Finished in 0.05 s (51023 µs/read; 0.00 M reads/minute).

=== Summary ===

Total reads processed:                       1
Reads with adapters:                         1 (100.0%)

== Read fate breakdown ==
Reads that were too short:                   0 (0.0%)
Reads written (passing filters):             1 (100.0%)

Total basepairs processed:           101 bp
Quality-trimmed:                       2 bp (2.0%)
Total written (filtered):             68 bp (67.3%)

=== Adapter 1 ===


Sequence: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA; Type: regular 3'; Length: 100; Trimmed: 0 times

=== Adapter 2 ===

Sequence: GATGGTTGAGGATGTGTGGAGNNNNNN; Type: regular 5'; Length: 27; Trimmed: 1 times

Minimum overlap: 3
No. of allowed errors:
1-9 bp: 0; 10-19 bp: 1; 20-21 bp: 2

Overview of removed sequences
length	count	expect	max.err	error counts
8	1	0.0	0	1

```

Thanks,

**Comment by marcelm** [comment]
(It’s generally a good idea to trim down the question so that only the relevant parts remain.) I think the essence of your question is: Why does `-g GATGGTTGAGGATGTGTGGAGNNNNNN` trim the sequence `AGGCGATGxyz` to `xyz`?

The found alignment is this one:
```
GATGGTTGAGGATGTGTGGAGNNNNNN
                   ||||||||
                   AGGCGATGxyz
```
When you use `-g`, you explicitly allow this case. There’s just no way to know whether the unsequenced bases before the `AG` are `...ATGTGTGG`, so without any other information, this is considered a match.

Note that this would even apply when you provide an "adapter" sequence that is almost entirely degenerate:
```
$ echo -e '>r\nGCCGCCTTT' | cutadapt -g ANNNNNN --quiet -
>r
TTT
```

> I don't understand why the "AGGCGATG" was trimmed. It does have 3bp match with the adapter [...]

It’s considered to be an 8-bp match.

> but I find this behaviour penalising as this sequence, and many others that I checked, are real genomic sequences

You didn’t say what your intention is (what type of sequence that is you are removing). To avoid the behavior you are seeing, you could use an anchored 5' adapter instead if that is appropriate, or you could increase the minimum overlap.

> Also, the log shows only 1 error. I am curious to know how is this the case

It’s actually zero errors. Here’s the relevant part of the report again:
```
Overview of removed sequences
length	count	expect	max.err	error counts
8	1	0.0	0	1
```
The last row shows that one sequence of length 8 has been removed at zero errors. The numbers under the "error counts" columns are frequencies in the order "number of zero-error matches", "number of one-error matches", "number of two-error matchs" etc.

**Comment by marcelm** [comment]
I hope the answer was helpful, closing this issue now since there hasn’t been a response. Feel free to re-open!
