### ISSUE TITLE
Need suggestions for demultiplexing and trimming

### ISSUE THREAD

**Issue by Yyeserin** [marcelm/cutadapt#623]
Hello,

Please find the details of the cutadapt version, and sequence samples in the end.

I have a complex issue, and have been working on it for several weeks. I have ddRADseq data, multiplexed in combinatorial way. I use a list of barcodes to demultiplex the raw data. Each barcode  is 8 bp in length. Demultiplexing works fine. I used _retain_ option to see how the output looks like. The output is like this

_R1:  i7.barcode/MseI.adapter/MseI.cutsite/genomic sequence/AciI.cutsite/i5.barcode
R2: i5.barcode/AciI.cutsite/genomic sequence/MseI.cutsite/MseI.adapter/_

3'ends of each read may or may not have the cutsites or adaptors. MseI.adapter is in R1 reads: "5'-GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCTG-3'"

I need to clean the barcodes and adaptors from both 5' and 3' ends of R1 and R2 reads. Is there way to do it after demultiplexing using loop? Do I need to use linked adaptors?  I tried the script below, but cutadapt doesn't seem to recognize min_overlap function when a barcode file is introduced. I get this error: No such file or directory: 'i5_barcodes.fasta;min_overlap=1'

**cutadapt --action trim -m 40 --no-indels --trim-n -g "**CCGATCTG**; min_overlap:8" -a "file:i5_barcodes.fasta; min_overlap1" -G "file:i5_barcodes.fasta; min_overlap:1" -A  "CCGATCTG; min_overlap:1" -o trim.round1-{name1}-{name2}.1.fastq -p trim.round1-{name1}-{name2}.2.fastq input_R1 input_R2**
No such file or directory: 'i5_barcodes.fasta;min_overlap=1'

 May be there is a smarter way of doing it like during demultiplexing? I will appreciate any suggestions to end my misery.

Many thanks.

Note: **CCGATCTG** is the last 8 bp of MseI.adapter

------------
- Cutadapt and Python version: **cutadapt 4.0 with Python 3.9.5**
- Installed in **rackham**
- command-line parameters used
**cutadapt --action trim -m 40 --no-indels --trim-n  -j 0 -g file:i7_barcodes.fasta -G file:i5_barcodes.fasta -o trimmed_round1/round1-{name1}-{name2}.1.fastq -p trim_round1/round1-{name1}-{name2}.2.fastq input_R1_001.fastq.gz input_R2_001.fastq.gz**

If you report unexpected trimming behavior, this would also be helpful:

An example **input** read (or read pair)
**R1 reads:**
_@A00181:277:H3CF5DSX2:3:2452:16432:11569 2:N:0:110
TCGCAGCTAAGACCTTTATCGTGTCAACCTTTACGAATTTAGCAGGGCTCACTCCAACCTCTGTCCTCTCGCAATTAGTTGCTGGTAGCAATTATATTGCGACCTACGTCCTAGCTGATGGTTCAATAGTTACTGTGAAGGTGTATGTTAC
+
@A00181:277:H3CF5DSX2:3:2369:29930:6136 2:N:0:110
TGGGCTACACGCAAAAGGTAACCAGTTTTTCTAGAACTTAGGGGCGCCGCCCCTCCCAGTAGACTGATTTCCCCGTCTGGGCCTCCGGCCATTTTTGGGACTCGCATTATGTATAAAAATATTTATGTATTAGTTTACTCACATATATTAC
+_

**R2 reads:**
_@A00181:277:H3CF5DSX2:3:2452:16432:11569 1:N:0:110
GAGCCCTGCTAAATTCGTAAAGGTTGACACGATAAAGGTCTTAGCTGCGATCCATGAGGCAGAGGTGAGGCTGGCTGCCTGATATCCTCCCACAACTGGTGAACTAGAAGCACGAAGGGAGTTGGCTACGCTTCCAGCGCTGTACCA
+
@A00181:277:H3CF5DSX2:3:2369:29930:6136 1:N:0:110
TGGCCGGAGGCCCAGACGGGGAAATCAGTCTACTGGGAGGGGCGGCGCCCCTAAGTTCTAGAAAAACTGGTTACCTTTTGCGTGTAGCCCATATGATCCCGATCATATTTCCGGCCCTCCGGGGTCGGTCTCGGCCCTCCGCGACTCCTAC_

- The **output**:
**R1:**

@A00181:277:H3CF5DSX2:3:1101:2121:1031 1:N:0:110
_GAGACGATGTGACTGGAGTTCAGACGTGTGCTCTTCCGATCTGTAAGTAAAAAATGCGTTTTTTGCTATTTTCCGAAATTTCTTGATTTTTGTCTATTTTTCAACGTACTTTTGCGCGGTCTGCAA
+
@A00181:277:H3CF5DSX2:3:1101:12066:1031 1:N:0:110
GAGACGATGTGACTGGAGTTCAGACGTGTGCTCTTCCGATCTGTAAAAGAGAACTTTGAAGGAAGTATGCAGAACGCTACATATAGCATAAATACTCACTCAAAAACTACGGCGAGTAAAGGTGCGGTCTGCAA_
+

**R2:**

_@A00181:277:H3CF5DSX2:3:1101:2121:1031 2:N:0:110
TTGCAGACCGCGCAAAAGTACGTTGAAAAATAGACAAAAATCAAGAAATTTCGGAAAATAGCAAAAAACGCATTTTTTACTTAC
+
@A00181:277:H3CF5DSX2:3:1101:12066:1031 2:N:0:110
TTGCAGACCGCACCTTTACTCGCCGTAGTTTTTGAGTGAGTATTTATGCTATATGTAGCGTTCTGCATACTTCCTTCAAAGTTCTCTTTTAC_

**Comment by marcelm** [comment]
So given this description of how the original reads look:
```
R1: i7.barcode/MseI.adapter/MseI.cutsite/genomic sequence/AciI.cutsite/i5.barcode
R2: i5.barcode/AciI.cutsite/genomic sequence/MseI.cutsite/MseI.adapter/
```
How do you want the reads to look afterwards? Like this?
```
R1: MseI.cutsite/genomic sequence/AciI.cutsite
R2: AciI.cutsite/genomic sequence/MseI.cutsite
```

**Comment by Yyeserin** [comment]
Hi again. Yes, I want them to look like exactly like that:

R1: MseI.cutsite/genomic sequence/AciI.cutsite
R2: AciI.cutsite/genomic sequence/MseI.cutsite

**Comment by Yyeserin** [comment]
By the way, the original reads looks like longer depending on the reads. But they should look like this if the reads are sequenced totally.

R1: **Illumina.adapter**/i7.barcode/MseI.adapter/MseI.cutsite/genomic sequence/AciI.cutsite/i5.barcode/**Aci.adapter****/Illumina.adapter**
R2: **Illumina.adapter/AciI.adapter**/i5.barcode/AciI.cutsite/genomic sequence/MseI.cutsite/MseI.adapter/i7.barcode/**Illumina.barcode.**

**Comment by Yyeserin** [comment]
I skipped illumina adapters, because I recover more reads if I directly use i5 and i7 barcodes with -g and -G options.

**Comment by marcelm** [comment]
I think I still don’t fully understand how your input reads look, but let me try to answer a couple of things.

Removing the adapters at the same time as demultiplexing can be done by combining each barcode with the adapter sequence next to it. So instead of demultiplexing by searching for i7 barcodes, you search for i7 barcode + MseI.adapter, for example. That is, you would need to open the `i5_barcodes.fasta` and `i7_barcodes.fasta` files and copy and paste the correct adapter sequences into it either to the left or right of the barcode depending on where the adapter occurs relative to the barcode.

I would probably not do this and rather run Cutadapt multiple times.

So let’s start with this:
R1: i7.barcode/MseI.adapter/MseI.cutsite/genomic sequence/AciI.cutsite/i5.barcode/Aci.adapter/Illumina.adapter
R2: AciI.adapter/i5.barcode/AciI.cutsite/genomic sequence/MseI.cutsite/MseI.adapter/i7.barcode/Illumina.adapter

First, trim off the 3' i5.barcode from R1:
```
cutadapt -a AciI.cutsite-sequence --action=retain -o out_a.1.fastq.gz -p out_a.2.fastq.gz in.1.fastq.gz in.2.fastq.gz
```
That should give you:
R1: i7.barcode/MseI.adapter/MseI.cutsite/genomic sequence/AciI.cutsite
R2: AciI.adapter/i5.barcode/AciI.cutsite/genomic sequence/MseI.cutsite/MseI.adapter/i7.barcode/Illumina.adapter

Then trim AciI.adapter and i7.barcode from R2. This is done in a separate step because we used `--action=retain` above, but don’t want it here (it cannot be set separately for R1 and R2):
```
cutadapt -G ^AciI.adapter...MseI.adapter -o out_b.1.fastq.gz -p out_b.2.fastq.gz out_a.1.fastq.gz out_a.2.fastq.gz
```
That should give you:
R1: i7.barcode/MseI.adapter/MseI.cutsite/genomic sequence/AciI.cutsite
R2: i5.barcode/AciI.cutsite/genomic sequence/MseI.cutsite

Now comes the demultiplexing. Because the i7.barcode and i5.barcode appear directly at the 5' end of the read, you can use an anchored adapter, that is, you should prefix the sequnce in the FASTA file with a `^`.
```
mkdir demuxed
cutadapt -g file:anchored_i7_barcodes.fasta -G file:anchored_i5_barcodes.fasta -o demuxed/round1-{name1}-{name2}.1.fastq -p demuxed/round1-{name1}-{name2}.2.fastq
```
That should give you:
R1: MseI.adapter/MseI.cutsite/genomic sequence/AciI.cutsite
R2: AciI.cutsite/genomic sequence/MseI.cutsite

Finally, we need a loop to trim MseI.adapter:
```
cd demuxed
mkdir ../final
for f in round1-*.1.fastq; do
  echo cutadapt -g ^MseI.adapter -o ../final/$f -p ../final/${f%%.1.fastq}.2.fastq $f ${f%%.1.fastq}.2.fastq
done
```
The above will only print out the commands (`echo`), but not actually run them. Try it first in this way and then when you think it looks good, remove the `echo` to actually run it. The $f is the name of the R1 file (`.1.fastq`). The `${f%%.1.fastq}` removes the`.1.fastq` suffix from the file name, and then `.2.fastq` is added to it to get the R2 file name. (Yes, this is not intuitive and I have to look it up.)

Add `-j 0` or `--no-indels` or similar to the above commands as required.

---
Here are some more comments (I wrote these first, you can probably ignore them now).

> By the way, the original reads looks like longer depending on the reads. But they should look like this if the reads are sequenced totally.
> 
> R1: Illumina.adapter/i7.barcode/MseI.adapter/MseI.cutsite/genomic sequence/AciI.cutsite/i5.barcode/Aci.adapter/Illumina.adapter

The read itself should not contain the Illumina adapter at the 5' end because the sequencing process starts right after it. You would see the Illumina adapter only the other side (at the 3' end) if the read is long enough.

> I get this error: `No such file or directory: 'i5_barcodes.fasta;min_overlap=1'`

Using `file:` together with specifying adapter-trimming parameters such as `min_overlap=...` is not supported at the moment. (I have opened issue #624 about this.) That is, when you write `-a file:i5_barcodes.fasta;min_overlap=1`, the `;min_overlap=1` part is considered to be part of the file name, so Cutadapt complains that it cannot open a file named `i5_barcodes.fasta;min_overlap=1`.

One solution is to use the global option `--overlap=...` and set it to the value that you want for all the adapters/barcodes in FASTA files. Then use `min_overlap=...` (as you do now) for those adapters where you want a minimum overlap that is different from this default (so write `-g "CCGATCTG; min_overlap=8"` as before, for example).

Another solution is to write the `;min_overlap=1` text directly into the FASTA file. So having something like this in the file would work (just an example):
```
>barcode1
ACGT;min_overlap=7
```
However, are you sure you need to change the minimum overlap from the default (3) at all? Why do you change it?

**Comment by Yyeserin** [comment]
Hi Marcel,

That data is not usable. We have to resequence the library again. So, you
can close the issue.

Thank you very much for your help. I wouldn't be able to figure out the
problem without your suggestions.

Best regards,
Yeserin.

**Comment by marcelm** [comment]
Oh sorry to hear – but maybe it’s good to get a fresh start. Good luck!
