### ISSUE TITLE
i5 and i7 adaptor sequences as input 

### ISSUE THREAD

**Issue by amy-houseman** [marcelm/cutadapt#636]
- Cutadapt and Python version
Cutadapt version 3.5 with Python 3.9.2
- How you installed the tool (conda or pip, for example)
Via pip

Hello, I know this has been answered similarly before but I would really appreciate some help. I have been given this list of adaptors for each dataset E132 and E036 and their samples:

![Image 06-08-2022 at 16 08](https://user-images.githubusercontent.com/110385188/183255243-efb15f00-4e41-410d-b2cc-ad1c9186f15c.jpg)
![Image 06-08-2022 at 16 20](https://user-images.githubusercontent.com/110385188/183255272-5845568f-3e36-47b8-8d27-beb8a2416914.jpg)

I can see from your documentation that you have this option https://cutadapt.readthedocs.io/en/latest/guide.html#illumina-truseq

When looking in here: https://dnatech.genomecenter.ucdavis.edu/wp-content/uploads/2013/06/illumina-adapter-sequences_1000000002694-00.pdf

I can see these: 
D501–D508 Adapters
AATGATACGGCGACCACCGAGATCTACAC[i5]ACACTCTTTCCCTACACGACGCTCTTCCGATCT 
D701–D712 Adapters
GATCGGAAGAGCACACGTCTGAACTCCAGTCAC[i7]ATCTCGTATGCCGTCTTCTGCTTG

and 
Nextera Index Kit – PCR Primers Index 1 Read
5’ CAAGCAGAAGACGGCATACGAGAT[i7]GTCTCGTGGGCTCGG
Index 2 Read
5’ AATGATACGGCGACCACCGAGATCTACAC[i5]TCGTCGGCAGCGTC

I'm sorry it is messy, this is how the data was given to me, and I am not an expert, but very stressed about inputting the wrong adapters. 

Thanks!
Amy

**Comment by marcelm** [comment]
Hi Amy, can you say what you want to do and which data you have?

Looking at the spreadsheet, it appears that [combinatorial dual indexing](https://emea.support.illumina.com/bulletins/2018/08/understanding-unique-dual-indexes--udi--and-associated-library-p.html) was used. I would expect your sequencing provider to have demultiplexed this data into one FASTQ file pair (R1 and R2) for each sample. If you do not already have one file pair per sample, you would [need to do the demultiplexing yourself](https://cutadapt.readthedocs.io/en/stable/guide.html#demultiplexing-paired-end-reads-with-combinatorial-dual-indexes). For an overview, https://teichlab.github.io/scg_lib_structs/methods_html/Illumina.html may also be helpful.

If the demultiplexing has already been done, you can ignore the i7 and i5 sequences. Then the next thing is to decide whether you need to trim adapters at all. If these are sequences from shotgun sequencing, for example, then usually very few reads will have adapters at all, and explicit adapter trimming wouldn’t be strictly necessary because the read mapper ignores (soft-clips) the remaining ones.

**Comment by amy-houseman** [comment]
Hi Marcel, 

Thank you for your reply!!

I do have R1 and R2 reads for each sample. The E132 sequences were created using exome libraries using the Illumina TruSeq DNA Exome kit on the Illumina HiSeq 4000 and the E036 were created using Nextera Exome Enrichment Kit on the Illumina HiSeq 2500 in HO (high output) mode.

I would like to do variant calling (Indels/SNVs) and CNV calling. I will make my repository public for what I plan to do: https://github.com/amy-houseman/snv_indel_pipelines (the cutadapt adaptors are not correct for the E132 or E036 dataset). 

I hope that makes sense!
Amy

**Comment by marcelm** [comment]
For TruSeq (E132), the adapter sequences from the [Cutadapt TruSeq section](https://cutadapt.readthedocs.io/en/latest/guide.html#truseq) should work (almost the same as what you have already now, except that the one for `-A` should be shorter or include a couple of `N`s where the i5 is located). I haven’t worked with Nextera data myself, to be honest, so I don’t know whether the same works for E036.

To determine whether trimming adapters at all is necessary, I would run Cutadapt on one sample only and look at the report. If very few adapters are trimmed, it’s just an unnecessary step. Also, I see that you are using BWA-MEM. BWA-MEM will soft-clip adapters as I mentioned.

**Comment by amy-houseman** [comment]
Hi Marcelm,

Thank you for your reply! 

Sounds good - I do have some adaptors still present in the NG0921 dataset - cutadapt trimmed around 36,000 adaptor sequences from read 1 and then around the same for read 2. 
![Screenshot 2022-08-10 at 09 18 50](https://user-images.githubusercontent.com/110385188/183853103-6d3a2cb7-4024-4a29-bfd7-0a0ba1c1d067.png)

I do still get a little adaptor present after using fastqc on the trimmed lot (less than before trimming) - do you think that amount would be okay to leave?

**Comment by marcelm** [comment]
> do you think that amount would be okay to leave?

I think it’s fine for this application.

**Comment by amy-houseman** [comment]
Thanks Marcelm, you've been really helpful! I hope you have a great rest of your week!

**Comment by marcelm** [comment]
Thank you!

**Comment by amy-houseman** [comment]
Hi Mercelm,

Hope you're well! I was a just wondering I think for the Nextera I need to use these CTGTCTCTTATACACATCT+AGATGTGTATAAGAGACAG.

I assume that means that both adapter sequences should be checked for in both sequences? Do you know how to do that with cutadapt? 

Thanks! Amy
