### ISSUE TITLE
Trimming multiple types of adapters

### ISSUE THREAD

**Issue by bounlu** [marcelm/cutadapt#638]
I want to trim 5' adapter, 3' adapter and poly A/T/G/C at the same as long as they are present in the same read from SE50 data.

I am using the below script:

```
    cutadapt \\
        --cores $cores \\
        --overlap 10 \\
        --front $five_prime_adapter \\
        --adapter $three_prime_adapter \\
        --anywhere "A{50};max_errors=0" \\
        --anywhere "T{50};max_errors=0" \\
        --anywhere "G{50};max_errors=0" \\
        --anywhere "C{50};max_errors=0" \\
        --minimum-length 10 \\
        --maximum-length 50 \\
        --max-n 0.1 \\
        --nextseq-trim 20 \\
        --discard-untrimmed \\
        --output ${prefix}_trimmed.fq.gz \\
        ${prefix}.fastq.gz \\
        > ${prefix}_trimming_report.txt
```

I have read the docs but wanna be sure for the below complex cases. So I am wondering:

1. What will be the order of trimming between 5', 3' and poly A/T/G/C trimming?

2. What happens if there are both poly A and poly G?

3. Is it needed to specify `-n` parameter for my purpose? If so, what value should it be?

4. What happens if multiple copies of 3' adapter are present?

5. Do I need to run `cutadapt` multiple times?

**Comment by marcelm** [comment]
> I want to trim 5' adapter, 3' adapter and poly A/T/G/C at the same as long as they are present in the same read from SE50 data.

What is "SE50 data"? Does this refer to single-end reads that are 50 bp long?

> I am using the below script:
> 
> ```
>     cutadapt \\
>         --cores $cores \\
>         --overlap 10 \\
>         --front $five_prime_adapter \\
>         --adapter $three_prime_adapter \\
>         --anywhere "A{50};max_errors=0" \\
>         --anywhere "T{50};max_errors=0" \\
>         --anywhere "G{50};max_errors=0" \\
>         --anywhere "C{50};max_errors=0" \\
> ```

I’m not so sure you really want `--anywhere`. It’s a weird hybrid option that exists mainly for historical reasons. If you know that the sequence appears at the 5' end, use `-g`, and if you know that the sequence appears at the 3' end, use `-a`.

Also, there can be sequencing errors within poly-A/C/G/T sequences, so you may want to allow some errors.

> ```
>         --minimum-length 10 \\
>         --maximum-length 50 \\
> ```

If you sequences are 50 bp, then `--maximum-length 50` will no have effect (but it doesn’t hurt either).

> ```
>         --max-n 0.1 \\
>         --nextseq-trim 20 \\
>         --discard-untrimmed \\
>         --output ${prefix}_trimmed.fq.gz \\
>         ${prefix}.fastq.gz \\
>         > ${prefix}_trimming_report.txt
> ```
> 
> I have read the docs but wanna be sure for the below complex cases. So I am wondering:
> 
>     1. What will be the order of trimming between 5', 3' and poly A/T/G/C trimming?

Cutadapt searches for all given adapter sequences in each read. It then determines which one matches best and removes that one. So for example, if it determines the 3' adapter to match best, it won’t remove the 5' adapter nor any of the poly-N sequences.

>     2. What happens if there are both poly A and poly G?

As above, only the best match is removed. But since your command uses `--discard-untrimmed`, it doesn’t matter which one is found since the entire read is discarded anyway (the statistics will show how often which one was found, however).

>     3. Is it needed to specify `-n` parameter for my purpose? If so, what value should it be?

See below.

>     4. What happens if multiple copies of 3' adapter are present?

Cutadapt finds the leftmost occurrence. When it removes that one, the other occurrence to the right is automatically removed as well.

>     5. Do I need to run `cutadapt` multiple times?

The easiest option, but not quite correct way, is to use the `-n` option to do multiple rounds of adapter removal. With `-n 3`, you can find a 5' adapter, a 3' adapter and a poly-N sequence. However, it is not guaranteed that it finds at most one of each. So Cutadapt might, for example, trim the 3' adapter three times from a read. This will probably happen rarely, so it’ll probably be ok.

To trim both a 5' and a 3' adapter from a read, you can use linked adapters (see the documentation), so you’d write `-a ${five_prime_adapter}...${three_prime_adapter}`. This works a bit like `-n 2`, but is guaranteed to trim at most one 5' and at most one 3' adapter. To additionally trim poly-N sequences, you could run Cutadapt a second time (before or after adapter removal). If you pipe one command into the other, this is quite efficient, so roughly something like this (showing only the most relevant options):
```
cutadapt -a A{50} -a C{50} -a G{50} -a T{50} input.fastq.gz 2> polyn.log | \
  cutadapt -a ${five_prime_adapter}...${three_prime_adapter} -o output.fastq.gz - 2> trim.log
```
Piping avoids disk I/O and compressing/decompressing the data.

**Comment by bounlu** [comment]
Yes you guessed correct, SE50 means Single End with 50 bp long.

Based on your suggestions, I removed `--anywhere`, and I will run cutadapt multiple times to achieve my goal. This seems to be the safest way rather than trying to achieve everything in one go.

Thanks a lot.

**Comment by bounlu** [comment]
Following up on this, I am wondering why I still have reads containing polyA/T/G/C of 10+ nt long after the below command line? Shouldn't they all be removed due to the `--discard-trimmed` and `--overlap 10` flags?

    cutadapt \\
        --cores $cores \\
        --overlap 10 \\
        --front $five_prime_adapter \\
        --anywhere "A{50}" \\
        --anywhere "T{50}" \\
        --anywhere "G{50}" \\
        --anywhere "C{50}" \\
        --minimum-length 10 \\
        --maximum-length 50 \\
        --discard-trimmed \\
        --output ${prefix}_trimmed.fq.gz \\
        ${prefix}.fastq.gz \\
        > ${prefix}_trimming_report.txt

**Comment by marcelm** [comment]
I tried to explain this above, but I realize I wasn’t clear enough: Cutadapt will remove only *one* of the sequences that you provided. So it chooses one of the five sequences you provided and removes the best matching one. If a read contains the 5' adapter *and* a poly-A tail, but the 5' adapter matches better, then only the 5' adapter is removed. The poly-A tail remains in the read.

The easiest way to fix this is to tell Cutadapt to run the adapter removal multiple times with `--times`. It appars to me that `--times=2` would work in your case. The other way to fix this is to run Cutadapt twice, once to remove the 5' adapter and once to remove any of the poly-N tails.

**Comment by bounlu** [comment]
I understand that cutadapt will remove only _one_ of the sequences provided, but this does not explain my question. I use `--discard-trimmed`, which means whichever the adapter is removed, the trimmed read must be discarded. So in any case, none of the remaining reads should contain any of the adapters provided. Yet I still do see poly A/T/G/C in the remaining reads.

For example;

Let this be my read:
`ATGCATGCATGCAAAAAAAAAAGCTACGTACATG`

Let this be my 5' adapter:
`ATGCATGCATGC`

Trimmed read will be:
`AAAAAAAAAAGCTACGTACATG`

due to longer adapter (12nt) which matches better than polyA (10nt).

And it will be discarded due to:
`--discard-trimmed`

If my adapter is:
`GCGCGCGCGC`

Then trimmed real will be:
`ATGCATGCATGC`

or

`ATGCATGCATGCGCTACGTACATG`

due to polyA with `--overlap 10`.

and in either case it will be discarded too.

I can't think of any scenario that remaining reads will still contain polyA/T/G/C of 10+ nt if cutadapt works the way I understand.

**Comment by marcelm** [comment]
You’re right, I missed the `--discard-trimmed` part.

If you attempt to trim 
```
ATGCATGCATGCAAAAAAAAAAGCTACGTACATG
```
with `-a A{50}`, Cutadapt will not actually find a match. A 3' adapter must match from a position in the read onwards until either the end of the read or the end of the adapter has been reached. So the best alignment would look like this:
```
ATGCATGCATGCAAAAAAAAAAGCTACGTACATG  read
            ||||||||||xxx|xxx|x|xx  
            AAAAAAAAAAAAAAAAAAAAAAAAAAA...  adapter
```
The error rate for this alignment is too high, so it won’t be considered. Since you actually use `--anywhere` instead of `-a`, the following would also be an alignment candidate:
```
      ATGCATGCATGCAAAAAAAAAAGCTACGTACATG  read
      |xxx|xxx|xxx||||||||||
...AAAAAAAAAAAAAAAAAAAAAAAAA  adapter
```
Again, this has too many errors and is therefore not considered. 

So `-a A{50}` only works if your read ends with a run of `A` nucleotides. `-g A{50}` only works if your read begins with a run of `A`. And `--anywhere A{50}` only works if the read begins or ends with a run of `A`. To achieve this, you can remove the 5' adapter first and the poly-A afterwards.

Regarding your second example:

> If my adapter is:
> `GCGCGCGCGC`
> Then trimmed real will be:
> `ATGCATGCATGC`
> or
> `ATGCATGCATGCGCTACGTACATG`

Cutadapt never removes a sequence from the middle of a read. For a 3' adapter, it always removes the match itself and anything potentially following it. For a 5' adapter, it removes the match itself and anything potentially preceding it.

**Comment by bounlu** [comment]
I got it crystal clear now, thanks a lot for the clarifications!

I never thought the mismatch thing extends to the full adapter length. Instead I thought it would trim the adapter of any length from 50 to 10 as long as the error rate is met _within_ the overlapping region.

It seems my design works like a polyA/T/G/C **tail** trimmer, rather than **low sequence complexity** remover, due to the kind of matching requirement at the ends.

To get rid of those reads, I should additionally specify shorter adapter lengths with decreased error rate, something like:

`--anywhere "A{20}"`

`--anywhere "A{10};max_error_rate=0"`

Any of these match will eventually discard the read.

Thanks again.
