### ISSUE TITLE
Publish Release 4.1...?

### ISSUE THREAD

**Issue by djmce** [marcelm/cutadapt#647]
Hi,
The [cutadapt changelog](https://cutadapt.readthedocs.io/en/stable/changes.html) refers to v4.1 as being the latest release, dated 2022-06-07. 
However, the [latest published release](https://github.com/marcelm/cutadapt/releases) on the GitHub repo is v4.0, dated 2022-05-11. 
Are you planning to publish v4.1 on the [releases page](https://github.com/marcelm/cutadapt/releases)?
(The reason I ask is that we are using v4.1 and would like to reference the URL of a source code `tar.gz` in our open-source license compliance documentation)

**Comment by marcelm** [comment]
I make releases primarily to PyPI. I created a couple of GitHub releases merely so that I would have a place where I could offer a `cutadapt.exe` file for download. (I understand this is confusing and that I should probably disable the GitHub releases or use them as they are intended.)

The canonical download URLs are on the [PyPI project page](https://pypi.org/project/cutadapt/). So for version 4.1, that would be https://files.pythonhosted.org/packages/a3/30/4a889a6916d7480c153774777e634b89865f95cb02f2c3209762c7ef984b/cutadapt-4.1.tar.gz.

The following shorter URL also works (it redirects to the above), and is much easier to adjust if the version changes:
https://pypi.io/packages/source/c/cutadapt/cutadapt-4.1.tar.gz

**Comment by djmce** [comment]
That's very helpful - thank you for confirming the PyPI URL for the release.
