### ISSUE TITLE
ValueError: FASTQ record does not fit into buffer

### ISSUE THREAD

**Issue by plutoxliu** [marcelm/cutadapt#660]
Hello,
I found a closed issue having the same problem  #462 , but by increasing the buffer size (to even 100MB) still gave me the same error.
- Using Python 3.8 and cutadapt 3.5

`cutadapt -a AGATCGGAAGAGC -A AGATCGGAAGAGC -j 8 -o "${base}".1.trim.fq.gz -p "${base}".2.trim.fq.gz "${base}".1.fq.gz "${base}".2.fq.gz -m 25:20 -q 10`

The error trace back to 
` File ".../cutadapt/3.5-gimkl-2020a-Python-3.8.2/lib/python3.8/site-packages/dnaio/chunks.py"$    raise ValueError("FASTQ record does not fit into buffer")
ValueError: FASTQ record does not fit into buffer`

I'm trying to trim Illumina universal adapters, reads from Illumina hiseq 2500.

Thanks very much!

**Comment by plutoxliu** [comment]
dnaio version is 0.10.0. I have tried upgrade it but still same error unfortunately.

**Comment by marcelm** [comment]
Can you possibly make the files available?

**Comment by marcelm** [comment]
Here are a couple of things you could try to help us diagnose the problem in case you cannot share the data:
1. Remove the `-a` and `-A` options and let us know whether the problem persists (it should).
2. Additionally, use `-o /dev/null` and `-p /dev/null` and see whether the problem persists (it should).
3. Run cutadapt separately on the two input files (pretending it’s single-end): `cutadapt -j 8 -o /dev/null "${base}".1.trim.fq.gz` and `cutadapt -j 8 -o /dev/null "${base}".2.trim.fq.gz`. Is the problem still there and if so, with which of the input files?
4. Open the `.../site-packages/dnaio/chunks.py` file mentioned in the error message and change this line
    ```
    raise ValueError("FASTQ record does not fit into buffer")
    ```
    to this:
    ```
    raise ValueError(f"FASTQ record does not fit into buffer. {len(buf1)}, {len(buf2)}, {buf1[:10]}, {buf2[:10]}")
    ```
    Run the command from step 2 again (that is, not the single-end command) and let us know the error message.

**Comment by plutoxliu** [comment]
Thank you very much for this! I tried the first three:

  1.  The problem persists
  2.  The problem persists
  3.  No problem. And fastqc output looks fine
  4.  It’s a bit more complicated to change the file as I’m running it on a shared HPC computer. But if it helps to debug I’ll try to ask them about this?
I might also be able to make part of the files available just need to ask for permission first if that would be helpful?

**Comment by marcelm** [comment]
Thanks, that was helpful. I think I’ve found a way to reproduce the problem.

Is it possible that one of the input files contains more reads than the other? If you still have the report from when you ran cutadapt separately on the two input files, you can check the number of reads there. Are they different? Otherwise, run `zcat "${base}.1.trim.fq.gz" | wc -l` and `zcat "${base}.2.trim.fq.gz" | wc -l`. This will print the number of lines in the input files. Are they identical?

It seems there is a bug in the code that reads paired-end FASTQ files: If one of the input files contains more reads than the other, it will fill one of the buffers until it is full and then print the "FASTQ record does not fit into buffer" error message.

So it appears to me that there is a problem with the input files, but that the error message that is printed is wrong.

**Comment by plutoxliu** [comment]
Thanks very much for your help! Yes I think that's exactly the issue.

**Comment by marcelm** [comment]
Ah, great! The misleading error message will be fixed in the next release of dnaio (the library that Cutadapt uses to parse FASTQ files).
