### ISSUE TITLE
feature request: move `times` option into adapter string

### ISSUE THREAD

**Issue by y9c** [marcelm/cutadapt#664]
The `-n` / `--times` option in cutadapt is very confusing and it is not easy to use it properly.

take this example seq as example

```
>test
GGGGGGTTTTTTTTTTAAAAAA
```

If I want to remove one 5' ^GGG and all 3' AAA adapter at the same time, the `-n` need to be specified. And the expected output will be `GGGTTTTTTTTTT`

- By default, cutadapt will only trim one time

```
$ cutadapt -g ^GGG -a AAA test.fa 2>/dev/null

>test
GGGTTTTTTTTTTAAAAAA
```

- By setting `-n 2`, cutadapt does not loop all adapter, but trim the 1st adapter twice. 

```
$cutadapt -n 2 -g ^GGG -a AAA test.fa 2>/dev/null

>test
TTTTTTTTTTAAAAAA
```

- By setting `-n 3`, cutadapt trimmed both 5' and 3' adapter, but the 5' is not as expected.

```
$ cutadapt -n 3 -g ^GGG -a AAA test.fa 2>/dev/null

>test
TTTTTTTTTT
```

---

It would be better if `times` option could be specified into each adapter, in the same way as 'e=', 'o='. If so, the user can customize the trim behavior for each adapter.

```bash
cutadapt -g "^GGG;n=1" -a "AAA;n=1" test.fa
```

**Comment by y9c** [comment]
Note:

Another [issue](https://github.com/marcelm/cutadapt/issues/633) show a similar idea, but more specific case.

Set n for different adapter can be general solution.

**Comment by marcelm** [comment]
> The `-n` / `--times` option in cutadapt is very confusing and it is not easy to use it properly.

I understand that you may be frustrated, but please note that the way you phrased your request is not a good way to start a discussion about a feature request. (Writing "I find the option confusing" would be a less absolute judgement.)

The `--times` option simply does multiple rounds of adapter trimming (as [documented](https://cutadapt.readthedocs.io/en/latest/guide.html#more-than-one)). In each round, the best-matching adapter among all provided adapters is searched and removed. In each round, which type of adapter has been removed in the previous round is not considered. The `--times` option was added to Cutadapt a long time ago to process data where the same adapter was sometimes found multiple times. I agree it is not suitable for use cases like yours.

Would [linked adapters](https://cutadapt.readthedocs.io/en/latest/guide.html#linked-adapters) work in your case?

Otherwise, would the solution suggested in #633 work? Then I could focus on that.

The solution you propose has the issue that the behavior would change just because `n=1` is specified. With `-g "^GGG" -a AAA`, Cutadapt removes the best-matching adapter, but with `-g "^GGG;n=1" -a "AAA;n=1"` it would need remove each adapter individually up to a certain number of times. Also, I wonder how the behavior would need to be if some adapters are provided with `n` and some without `n`. Additionally, the other options `o=`, `e=` just override global defaults, so `-e 0.3 -a AAA` is the same as `-a 'AAA;e=0.3'`, but `-n 2 -a AAA -g GGG` would not be the same as `-a "AAA;n=2" -g "GGG;n=2"`.

**Comment by y9c** [comment]
Thank you very much for the clear explanation. It is very helpful. I tried link adapter and it did solve most of the problem in my application. But there are some expectations. I will organize my a issue with more proper examples. Sorry for my inappropriate expression.
