### ISSUE TITLE
Anchoring a file to the 3' end using -a?

### ISSUE THREAD

**Issue by ryandward** [marcelm/cutadapt#674]
Hey, I've installed cutadapt using conda, and it's working pretty much as intended, except I can't seem to figure out the syntax for anchoring something on the 3'-end. Anchoring to the 5'-end works fine:

`cutadapt -j12 -e 0 --no-indels -g ^file:promoters.fasta...`

But, I've tried tons of incarnations of placing the `$`, and I just get errors.

` -a file'$':spacers.fasta`
` -a file$:spacers.fasta`
` -a file:spacers.fasta$`
` -a file:spacers.fasta'$'`

Got any ideas?

**Comment by marcelm** [comment]
I couldn’t decide which syntax to use for this case, see #361, so I actually only implemented anchoring of 5' adapters using `^file:`. To anchor 3' adapters, you’ll have to add the `$` character to each sequence in the input FASTA for now.

Since you tried `file$:` and that is one of the suggestions I had in #361, I’ll try to implement that. Please leave this issue open so I’ll be reminded.

**Comment by marcelm** [comment]
I added the `file$:` notation. This will be part of Cutadapt 4.3.
