### ISSUE TITLE
Disable partial match for regular 5' and 3' adapters

### ISSUE THREAD

**Issue by racng** [marcelm/cutadapt#681]
cutadapt 4.2 with Python 3.10.9

Full sequence match is available for only anchored/non-internal 5' and 3' adapters. 
How can we disable partial match when looking for regular adapters?

For example, for the following sequence input:
aFIRSTmysequenceSECONDb
aRSTmysequenceSECb

A command with `-g FIRST...SECOND` would generate the output
FIRSTmysequenceSECOND (trimmed)
RSTmysequenceSEC (trimmed)

My concern is that my sample index is in the middle of the adapter, and if the adapter is not included and there is a tie and the read would get assigned to the first fastq by default based on documentation. 

I want to get the output
FIRSTmysequenceSECOND (trimmed)
aRSTmysequenceSECb (not trimmed) -> not demultiplexed

Some options I considered:
- I don't want to set min_overlap to equal the adapter length using `-g FIRST;min_overlap=5...SECOND;min_overlap=6` because that implies error tolerance of 0. 
- A pattern like `XN{10}FIRST...SECONDN{10}X` wouldn't work because it allows partial matches.
- I tried `^N{i}FIRST...SECONDN{i}$`, where `i` = some integer, but it requires the extra sequences to be exactly `i` nt long to get a match.

Example: 
```
# test_input.fasta
>seq1
ATTTTAGAGACCCCA
>seq2
TGGGGTCTCTAAAAT

# test_adapters.fasta
>A1
^N{3}GGGG...AAAAN{3}$

# command
cutadapt -e 0.3 --no-indels --revcomp -g file:test_adapters.fasta test_input.fasta

# output
>seq1
ATTTTAGAGACCCCA
>seq2
TGGGGTCTCTAAAAT
```
Output for i = 2
```
>seq1 rc
CTC
>seq2
CTC
```
Output for i = 1
```
>seq1 rc
TCTCT
>seq2
TCTCT
```

Thanks!

**Comment by marcelm** [comment]
To disable partial matches, you can set `min_overlap` to the length of the adapter.
> I don't want to set min_overlap to equal the adapter length using `-g FIRST;min_overlap=5...SECOND;min_overlap=6` because that implies error tolerance of 0.

It should not imply error tolerance 0, but maybe I misunderstand. Can you clarify what you mean or where you read this?

> For example, for the following sequence input:
> ```
> aFIRSTmysequenceSECONDb
> aRSTmysequenceSECb
> ```
> 
> A command with `-g FIRST...SECOND` would generate the output
> ```
> FIRSTmysequenceSECOND (trimmed)
> RSTmysequenceSEC (trimmed)
> ```

I assume you use `--action=retain`, otherwise the adapters themselves would also be removed.

There might be a misunderstanding. Sorry if this is clear to you, but partial adapter occurrences are only found if they are at the beginning or end of the sequence. For example, assuming zero error tolerance for simplicity, if you have `somethingPTERmysequence` and search for `ADAPTER`, then `PTER` is not considered a match.

So in `aRSTmysequence`, the adapter `FIRST` would usually *not* be found because you have the `a` preceding the `RST`. That said, it depends on what the `a` actually is. I assume it is a placeholder that stands for any sequence, but if it were just a single nucleotide, then there *would* be a match, albeit with one error because `aRST` would be aligned to `IRST`.

> `cutadapt -e 0.3 --no-indels --revcomp -g file:test_adapters.fasta test_input.fasta`

This doesn’t have anything to do with your question, but note that recent Cutadapt versions allow you to set an absolute number of errors as in `-e 1`, which you may find more readable.

**Comment by racng** [comment]
Thanks for the clarification! I saw this description in the documentation regarding min_overlap

> The overlap length is the number of bases in the adapter that got aligned to the read, which means that if there are deletions in the adapter, the corresponding part in the read will be shorter. (This is only relevant when the maximum allowed error rate and/or the minimum overlap length are changed such that at least one error is allowed over the given length.)

I thought that mismatched bases might not be counted in the overlap length. 

For an alignment like of regular 5' adapters (top) to a sequence (bottom) with `-e 1`, does the overlap have length 3 or 4?
```
AAAT   
GAATGGGGCCCT
```
If the mismatched bases are counted in overlap length, then you are right that I can just set min_overlap to the length of the adapter.
Yes, I was using placeholder sequence because my actual flanking and adapter sequences are a bit long. 
Thanks for your help!

**Comment by marcelm** [comment]
Thanks, maybe I should rewrite that sentence a bit.

Another way to describe the overlap is that it is the length of the adapter minus the number of bases that "hang off" the end and are not aligned.

Another explanation, not sure how much this helps:

An adapter match is represented internally as four numbers:
- read_start: Start position of the match in the read
- read_end: End position of the match in the read
- adapter_start: Start position of the match in the adapter. This is usually 0, but becomes positive for partial matches of 5' adapters
- adapter_end: End position of the match in the adapter. This is usually the same as the adapter length, but is smaller for partial matches of 3' adapters

The overlap length is just adapter_end minus adapter_start.

So in your example:
```
AAAT   
GAATGGGGCCCT
```
The length of the overlap is four.
