### ISSUE TITLE
Connecting R with cutadapt

### ISSUE THREAD

**Issue by Th5P** [marcelm/cutadapt#689]
Hi Marcel!

**I'm trying to run cutadapt with DADA2 ITS Pipeline Workflow (1.8) in R, however, nothing happens when I run the code so I assume R is not finding cutadapt.
I'm using a laptop with Windows 10. I downloaded Miniconda3 and run it as administrator but I couldn't install cutadapt using conda, therefore I did it with the pip command. This is the code I used:**

**(base) PS C:\WINDOWS\system32> conda config --add channels defaults
>> conda config --add channels bioconda
>> conda config --add channels conda-forge
>> conda config --set channel_priority strict
Warning: 'defaults' already in 'channels' list, moving to the top
Warning: 'bioconda' already in 'channels' list, moving to the top
Warning: 'conda-forge' already in 'channels' list, moving to the top
(base) PS C:\WINDOWS\system32> conda create -n cutadaptenv cutadapt
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - cutadapt

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/bioconda/win-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

(base) PS C:\WINDOWS\system32> pip install cutadapt
Collecting cutadapt
  Using cached cutadapt-4.3-cp310-cp310-win_amd64.whl (388 kB)
Collecting dnaio>=0.10.0
  Using cached dnaio-0.10.0-cp310-cp310-win_amd64.whl (63 kB)
Collecting xopen>=1.6.0
  Using cached xopen-1.7.0-py3-none-any.whl (15 kB)
Collecting isal>=1.0.0
  Using cached isal-1.1.0-cp310-cp310-win_amd64.whl (190 kB)
Installing collected packages: isal, xopen, dnaio, cutadapt
Successfully installed cutadapt-4.3 dnaio-0.10.0 isal-1.1.0 xopen-1.7.0
(base) PS C:\WINDOWS\system32>
(base) PS C:\WINDOWS\system32> cutadapt
This is cutadapt 4.3 with Python 3.10.9**

I'm totally new using conda and the shell in general, but it seems cutadapt was installed. I assumed the path was: "C:/programdata/miniconda3/lib/site-packages/cutadapt" 

because of this output:

**(base) PS C:\WINDOWS\system32> pip install cutadapt
Requirement already satisfied: cutadapt in c:\programdata\miniconda3\lib\site-packages (4.3)
Requirement already satisfied: xopen>=1.6.0 in c:\programdata\miniconda3\lib\site-packages (from cutadapt) (1.7.0)
Requirement already satisfied: dnaio>=0.10.0 in c:\programdata\miniconda3\lib\site-packages (from cutadapt) (0.10.0)
Requirement already satisfied: isal>=1.0.0 in c:\programdata\miniconda3\lib\site-packages (from xopen>=1.6.0->cutadapt) (1.1.0)**

(I tried to check the path with "which cutadapt" but it doesn't recognize the command.)

This is the script in R:

**#Remove primers
cutadapt <- "C:/programdata/miniconda3/lib/site-packages/cutadapt" 
system2(cutadapt, args = "--version")

path.cut <- file.path("Data", "cutadapt")
if(!dir.exists(path.cut)) dir.create(path.cut)
fnFs.cut <- file.path(path.cut, basename(fnFs))
fnRs.cut <- file.path(path.cut, basename(fnRs))

FWD.RC <- dada2:::rc(FWD)
REV.RC <- dada2:::rc(REV)

# Trim FWD and the reverse-complement of REV off of R1 (forward reads)
R1.flags <- paste("-g", FWD, "-a", REV.RC) 
# Trim REV and the reverse-complement of FWD off of R2 (reverse reads)
R2.flags <- paste("-G", REV, "-A", FWD.RC) 

# Run Cutadapt
for(i in seq_along(fnFs)) {
  system2(cutadapt, args = c(R1.flags, R2.flags, "-n", 2, # -n 2 required to remove FWD and REV from reads
                             "-o", fnFs.cut[i], "-p", fnRs.cut[i], # output files
                             fnFs.filtN[i], fnRs.filtN[i])) # input files
}**

But when I run it nothing happens. Could you give me some guidance about what to do or what read to make it work? I have been reading all the issues I could find but I haven't found a solution.

Thank you very much in advance!

**Comment by marcelm** [comment]
Hi,

> I'm trying to run cutadapt with DADA2 ITS Pipeline Workflow (1.8) in R, however, nothing happens when I run the code so I assume R is not finding cutadapt. I'm using a laptop with Windows 10. I downloaded Miniconda3 and run it as administrator but I couldn't install cutadapt using conda, therefore I did it with the pip command. This is the code I used:

> (base) PS C:\WINDOWS\system32> conda create -n cutadaptenv cutadapt
[...]
> PackagesNotFoundError: The following packages are not available from current channels:

while Conda is available for Windows, Bioconda builds only Linux and macOS packages, which is why Cutadapt is not directly available through Conda on Windows.

Good you got it installed using `pip install`, but there is one slight issue. The way you did it now, when you ran `pip`, it used the version of `pip` that came with Conda. To be precise: You used the `pip` that is installed in the Conda "base" environment (that one gives you the `(base)` prompt), which means that Cutadapt was installed into this base environment. Usually, it is recommended to not install anything into the base environment apart from Conda itself. For everything else, one should use a separate environment (not sure if you know what an environment is – it’s essentially a directory with a bunch of programs and their dependencies). The idea is that if anything is messed up in an environment, you can always just throw it away (`conda env remove -n environmentname`) and start over, *except* if it is the base environment because that contains Conda. Using Conda+pip to install Cutadapt on Windows is actually not a bad idea (maybe I should add that to the installation instructions), but I would have done it this way:
```
conda create -n cutadapt python pip
conda activate cutadapt
pip install cutadapt
```
You can leave things as they are now, but just in case you get weird error messages in the future when trying to update Conda or so, you now know that it could come from things in the base environment that shouldn’t be there. (To fix it, you would need to reinstall miniconda.)

> I'm totally new using conda and the shell in general, but it seems cutadapt was installed. I assumed the path was: "C:/programdata/miniconda3/lib/site-packages/cutadapt"

It is correct that this is the installation location for the Cutadapt Python library, but it is not where the program itself would be. I think it would be at `C:/programdata/miniconda3/bin/cutadapt` in your case.

> (I tried to check the path with "which cutadapt" but it doesn't recognize the command.)

I think it is called `where` on Windows (but that may not be available), please try that to confirm the path I wrote.

> This is the script in R:
> 
> **#Remove primers cutadapt <- "C:/programdata/miniconda3/lib/site-packages/cutadapt" system2(cutadapt, args = "--version")

Yeah, try to replace that with the path I gave.

**Comment by Th5P** [comment]
Oh, thank you so much!! I was looking for the cutadapt.exe but I tried the path you proposed and it worked. Thank you very much, Marcel!!

**Comment by marcelm** [comment]
Glad I could help!
