### ISSUE TITLE
Install from source code issue

### ISSUE THREAD

**Issue by CalebWM** [marcelm/cutadapt#691]
Hello, 
I've downloaded the source code from https://github.com/marcelm/cutadapt/releases/tag/v4.0 in the tar.gz format.
Then I unpack using the tar -xzf function. However, I don't think it works correctly as I don't see an instance of the cutadapt function provided?
I'm sure this is a simple error as I am new to Linux and shared cluster computing.

**Comment by marcelm** [comment]
Hi, the GitHub releases are not the recommended installation method. Just unpacking the tar.gz file like that won’t work. On the page you linked, you can read this:
> GitHub releases are made irregularly and exist only to be able to provide a single-file Windows executable for Cutadapt, which is not as well tested as the other [installation methods](https://cutadapt.readthedocs.io/en/stable/installation.html).

If you are on a shared cluster, I would try to see whether Cutadapt is perhaps already available. On our cluster, I would just need to run `module load cutadapt` first to make it available.

If not, you can use the Conda installation method, but check whether that is ok on your cluster. Conda tends to produce lots of small files, which cluster file systems often do not like that much and therefore some cluster admins discourage usage of Conda. Otherwise, you should use the `pip install` method. `pip` is usually included in Python, so if Python is not available directly, you would need to maybe use something like `module load python` to get it.

To decide between Conda and pip: Conda allows you to install lots of other bioinformatics packages, so learning it once will give you access to many other tools. pip is only for Python packages, but for those, installation may be faster.
