### ISSUE TITLE
cutadapt installation issue - interpreter: No such file or directory

### ISSUE THREAD

**Issue by emankhalaf** [marcelm/cutadapt#707]
Hi,

I tried to install Cutadapt on Ubuntu 20.04 using different codes that all ended with the same error when running cutadapt command or checking the version:
For example:
installation using pipx

`    $`sudo apt install pipx python3-venv` 
`
`$`pipx install cutadapt` 
`
File exists at /home/xxxx/.local/bin/cutadapt and points to /home/xxxxx/.local/bin/cutadapt. Not modifying.
  installed package cutadapt 4.4, Python 3.8.10
    - cutadapt (symlink not installed)
done! ✨ 🌟 ✨

`    $`cutadapt –version`
`
bash: /home/xxxx/.local/bin/cutadapt: /home/xxxx/miniconda3/envs/cutadaptenv/bin/python: bad interpreter: No such file or directory

I used also 

``    $conda create -n cutadaptenv cutadapt
``
and get the same error 

also

`    $sudo apt-get install cutadapt
`
same issue when using cutadapt command or checking the version of installed cutadapt

bash: /home/xxxx/.local/bin/cutadapt: /home/xxxx/miniconda3/envs/cutadaptenv/bin/python: bad interpreter: No such file or directory

Your help is much appreciated!

**Comment by marcelm** [comment]
Hi, try to run `pipx install --force cutadapt`. This will overwrite the file `/home/xxxx/.local/bin/cutadapt`, which appears to be broken in your case.

You should then probably remove the Ubuntu version of cutadapt so that there’s no confusion: `sudo apt remove cutadapt`.

Just for completeness, in case you want to use Conda instead of pipx (it doesn’t matter) the conda command did not work because the environment needs to be activated first. This should work:
```
conda create -n cutadaptenv cutadapt
conda activate cutadapt
cutadapt --version
```

**Comment by marcelm** [comment]
(You forgot to replace your user name with `xxxxx` in one of the command outputs.)

It seems there are still some remnants of an old cutadapt installation somewhere. A couple of things to try:

1. What is the output of `which pipx`?
2. Run `pip uninstall cutadapt`.
3. Run `pipx install cutadapt` (add `--force` if it doesn’t work). Does `cutadapt --version` work now?
4. Try running the Ubuntu version of cutadapt by giving the explicit path: `/usr/bin/cutadapt --version`
5. Same thing, but with the conda-installed version: `~/miniconda3/envs/cutadaptenv/bin/cutadapt --version`

**Comment by emankhalaf** [comment]
Hi,

Thanks for the observation! 
`$which pipx
`/usr/bin/pipx

inside activated cutadaptenv conda environment 

`pip uninstall cutadapt
`Found existing installation: cutadapt 4.3
Uninstalling cutadapt-4.3:
  Would remove:
    /home/xxxx/.local/bin/cutadapt
    /home/xxxx/.local/lib/python3.7/site-packages/cutadapt-4.3.dist-info/*
    /home/xxxx/.local/lib/python3.7/site-packages/cutadapt/*
Proceed (Y/n)? y
  Successfully uninstalled cutadapt-4.3

Then

`pipx install --force cutadapt
`Installing to existing directory '/home/xxxxx/.local/pipx/venvs/cutadapt'
⚠️  Note: cutadapt was already on your PATH at /home/xxxxx/miniconda3/envs/cutadaptenv/bin/cutadapt
  installed package cutadapt 4.4, Python 3.8.10
  These binaries are now globally available
    - cutadapt
done! ✨ 🌟 ✨
`$ cutadapt --version
`1.18

Then I ran this code to trim 18 nucleotides from 5` and 8 nucleotides from 3` end
cutadapt -q 18,8 -Q 18,8 -o ~/Documents//out_T22_S274.1.fastq -p ~/Documents/T22_S274.2.fastq ~/Documents/T22_S274_R1.fastq.gz ~/Documents/T22_S274_R2.fastq.gz

I got an error regarding the option -Q
cutadapt: error: no such option: -Q

So, I followed the tutorial of version 1.18 and used the following code since I needed to remove poor-quality bases unconditionally:
cutadapt -u 18 -o ~/Documents/trimmed_T22_S274.2.fastq ~/Documents/T22_S274_R2_001.fastq.gz

cutadapt -u -8 -o ~/Documents/trimmed_complete8_T22_S274.2.fastq ~/Documents/Fungi/trimmed_T22_S274.2.fastq

It worked, but is there a way to trim both ends (use both positive and negative values) and trim both R1 and R2 reads in the same command?

Thanks so much for your help!

**Comment by marcelm** [comment]
I think it is easiest if you decide on which Cutadapt installation method you want to use and then get rid of the other installations because they interfere with each other. (For the Conda environment, deactivating it is sufficient, you don’t need to remove it entirely.)

Here is some background, sorry if I’m explaining this you already know.

* `apt-get install cutadapt` places the `cutadapt` binary at `/usr/bin/cutadapt`
* `pipx install cutadapt` places the binary at `~/.local/bin/cutadapt` (which in turn is a symlink to `~/.local/pipx/venvs/cutadapt/bin/cutadapt`)
* `conda create -n cutadaptenv cutadapt` puts the binary into `~/miniconda3/envs/cutadaptenv/bin/cutadapt` (in your case at least because you installed Conda into `~/miniconda3`).
* When you type just `cutadapt` on the command line, the shell searches through the directories in the `$PATH` environment variable one by one and then runs the first one it finds. You can see your path by typing `echo $PATH`. You can see which binary it would pick by running `which cutadapt`.

Cutadapt 1.18 is probably the one you got via `apt-get install cutadapt` at `/usr/bin/cutadapt`. It does not have the `-Q` option, so I suggest you just remove it with `sudo apt remove cutadapt`.

Then you need to decide between pipx and Conda. When you want to use pipx, *do not* run it within an activated Conda environment. So use `conda deactivate cutadaptenv` or open a new terminal window. Then running `cutadapt --version` should work.

If you want to use the Conda version, you should remove the pipx-installed version with `pipx uninstall cutadapt` just to avoid future confusion. (It is not strictly necessary because the Conda cutadapt binary is going to be earlier in the PATH when you are in the activated environment.)

That said, if you use just `-q 18,8`, *both* R1 and R2 will be quality trimmed, and I think that is the case even in 1.18. `-Q` is only needed if you want to use different thresholds for R1 vs R2.
