### ISSUE TITLE
ERROR: Error in sequence file at unknown line: Reads are improperly paired

### ISSUE THREAD

**Issue by starz77** [marcelm/cutadapt#755]
Hello,

I'm using cutadapt 4.6 with python 3.8.10

There's an mismatching error 

Here's my command 
cutadapt -q 20 -A XXX -o read1_adapterTrimmed.fastq.gz -p read2_adapterTrimmed.fastq.gz -m 30 /dir/sample_id_R1_001.fastq.gz /dir/sample_id_R2_001.fastq.gz 

cutadapt stdout:  This is cutadapt 4.6 with Python 3.8.10
Command line parameters: -q 20 -A XXX -o read1_adapterTrimmed.fastq.gz -p read2_adapterTrimmed.fastq.gz -m 30 /dir/sample_id_R1_001.fastq.gz /dir/sample_id_R2_001.fastq.gz 
Processing paired-end reads on 1 core ...
ERROR: Error in sequence file at unknown line: Reads are improperly paired. Read name 'A01487:102:HLVNWDSX5:1:2320:21305:26240:CCTGT+ATACT      RG:Z:sample_id' in file 1 does not match 'A01487:102:HLVNWDSX5:1:2273:22046:35164:CATCT+GTTGT    RG:Z:sample_id' in file 2.

This error occurred when trying all of my samples.

Please help.

**Comment by rhpvorderman** [comment]
> ERROR: Error in sequence file at unknown line: Reads are improperly paired. Read name 'A01487:102:HLVNWDSX5:1:2320:21305:26240:CCTGT+ATACT RG:Z:sample_id' in file 1 does not match 'A01487:102:HLVNWDSX5:1:2273:22046:35164:CATCT+GTTGT RG:Z:sample_id' in file 2.

This is exactly as it says on the tin. Your reads are improperly paired. In proper paired FASTQ files both files contain the same number of reads, and all reads are in the same order. This way, the first read of the first file corresponds with the first read of the second file all the way to the last read. The way to check this is to see if the name is the same. In your files this is not the case. Given the 'RG:Z:sample_id' in the header, I suspect these were files generated with `samtools fastq` from BAM files, rather than FASTQ files that you got directly from the sequencing provider.

**Comment by starz77** [comment]
Thank you for your advice.
I will get another .fastq file for analysis.
