### ISSUE TITLE
Reads not trimmed for PE with poly-G

### ISSUE THREAD

**Issue by joegeorgeson** [marcelm/cutadapt#771]
Hi cutadapt,

I get the below output fastq when running cutadapt command (v4.2, installed via LSF module/compilation with gcc 11.3.0)
`cutadapt -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT -m 20` 

read_1 contains 'CGGAAGAGCACACGTCTGAACTCCAGTCAC' which I would expect to be trimmed, or have this read-pair completely excluded. Approx ~5% of output reads are like this. It's clear the poly-G is interfering, is there a patch for this?

```
@read_1
CGGAAGAGCACACGTCTGAACTCCAGTCACCATAGCGAATCGCGGGTGGCGGGGGGGGGGT
+
FFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,,F,,:,,:,,,,,,,:,,,


@read_2
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
```

Header of output log;
```
=== Summary ===

Total read pairs processed:         18,195,120
  Read 1 with adapter:               5,113,890 (28.1%)
  Read 2 with adapter:               4,816,968 (26.5%)

== Read fate breakdown ==
Pairs that were too short:           1,274,559 (7.0%)
Pairs written (passing filters):    16,920,561 (93.0%)

Total basepairs processed: 2,219,804,640 bp
  Read 1: 1,109,902,320 bp
  Read 2: 1,109,902,320 bp
Total written (filtered):  1,946,639,781 bp (87.7%)
  Read 1:   971,602,837 bp
  Read 2:   975,036,944 bp
```

**Comment by marcelm** [comment]
What is AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC (the sequence you provided with `-a`)? It appears at the 5' end, but `-a` is used to specify 3' adapters. Is it indeed a 3' adapter that apears partially truncated at the 5' end?

**Comment by joegeorgeson** [comment]
Hi Marcel, thank you very much for the super fast reply! The library design here is non-standard, basically 'backwards' from what would normally be the assignment of R1/R2 (it's RNA-seq so the original RNA strand remains on the "+" R1, but practically trivial). I copied below a tab-delimited description, but I don't think this is the issue.

```
AATGATACGGCGACCACCGAGATCTACAC	TCATGCTC	ACACTCTTTCCCTACACGACGCTCTTCCGATCT	NNNNNNNNNNNNNNNNNNNNNNNNNNNNNN	AATTAGT	NNN	AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC	CTACCAGG	ATCTCGTATGCCGTCTTCTGCTTG
Illumina_P5	Index-1_(i5)	TruSeq_R1	RNA_of_interest	Internal_barcode	UMI	TruSeq_R2	Index-2_(i7)	Illumina_P7
```

I tried again adding `--nextseq-trim=11` but still get a handful of reads I would expect to be trimmed (or excluded on -m 20) that do not, for example in the below read_1 and read_2 have adapter content but these get kept in the output fastq.

```
@read_1
CGGAAGAGCACACGTCTGAACTCCAGTCACCATAGCGAATCTCGGTTTGGGTGGT
+
:FFFF:FF:FFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFF,:F,,,,,,:,,,:

@read_2
AGGCCAAACAGACGTGTGCTCTTCCGATCTAGACCAAAACAGCCCCGCCCACACAACCCAC
+
,F,,,,:,,,::FF,:F,F::F,,:::FF:F,:,FFF,FF::,,::F:,FFFF:::,:F,F
```

**Comment by marcelm** [comment]
Please correct me if I did not understand.

So the TruSeq R2 adapter occurs partially in read_1. This is how an alignment could look:
```
TruSeq R2 adapter: AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
                       ||||||||||||||||||||||||||||||
Read 1 sequence:       CGGAAGAGCACACGTCTGAACTCCAGTCACCATAGCGAATCTCGGTTTGGGTGGT
```
Something went wrong with this fragment because apparently TruSeq R1 and TruSeq R2 hybridized without any sequence of interest in between, and also somehow the first bases `AGAT` of the second adapter went missing. You want to recognize this case and get rid of those reads.

When you provide a 3' adapter using the `-a` option. An alignment as shown above is not allowed: A 3' adapter can either occur in its entirety within the read or partially at the 3' end. Here, it occurs partially at the 5' end. To allow this, and allow the adapter to be found anyway, you can use the `anywhere` adapter-trimming option as I described above. As it says in the documentation, you should also increase the minimum overlap to reduce the number of false positive chance matches. It would look like this:
```
cutadapt -a 'AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC;anywhere;o=24' -A ...
```
The adapter has 34 nt. This sets the minimum overlap to 24 nt, thus allowing 10 nt in the beginning to be missing.

**Comment by joegeorgeson** [comment]
Thank you for walking me through that, everything makes perfect sense now! (This was tRNA sequencing so I saw many things I hadn't before, mainly because the final size selection was permissive to small fragments.) Thank you very much!

**Comment by marcelm** [comment]
Great, glad I could help!
