### ISSUE TITLE
Nanopore adapter detection

### ISSUE THREAD

**Issue by Hedi65** [marcelm/cutadapt#782]
Hi 

as you already know CutAdapt can detect and trim adapter/barcodes in the middle of a read (anchored 3` or 5`). we are working with data from Oxford nanopre technology and we have lots of reads and their barcodes are in the middle of the reads. could please anyone explain to me why this is happening? as mentioned in the library prep documents, barcodes should only ligate to the end of the reads. 

Thanks for your help

**Comment by marcelm** [comment]
Hi, this is not quite the right place to ask this question because it is about the Oxford Nanopore technology and not really about Cutadapt itself. I can sometimes help with more general questions like this, but the issue tracker is really about bugs in Cutadapt and problems encountered when using it.

That said, it is normal to encounter some reads with *adapters* in the middle and there has been some discussion about adding functionality to Cutadapt to split such reads, see #747. The fraction of such reads shouldn’t be very large, however (AFAIK), and I don’t know about *barcodes* in the middle, though.

Closing this now as it is not a Cutadapt issue, but feel free to comment further.

**Comment by rhpvorderman** [comment]
@Hedi65 yes, these are chimeric reads. They are expected to occur about 2% (in R9 chemistry) and 10% (R10) in the sample. 

This is something I am actively thinking about how to solve. There is apparently a tool called alvis that can detect those in alignments https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-021-04056-0. 

I want to be able to detect it based on the sequence itself and add that to cutadapt. That is going to be a tough nut to crack. See the linked issue #747
