### ISSUE TITLE
Feature request: shorten paired-end reads with separate values for --length

### ISSUE THREAD

**Issue by MaWeffm** [marcelm/cutadapt#788]
Dear developer, dear community,

thank you for actively working on this fantastic tool!

I frequently work with paired-end files that I need to shorten to specific lengths that are not equal for both reads. Practically speaking, I would like to apply the --length parameter with two different values during paired-end trimming. Something like the following, which is currently not working:

```
cutadapt --pair-filter any --minimum-length 20:15 --length 20:15 --discard-untrimmed -e 0.1 -g ADAPTER1 -G ADAPTER2 -o R1.out -p R2 out R1.fastq.gz R2.fastq.gz
```
The resulting files should contain trimmed reads that are shortened to a fixed length, in this case 20 and 15 bases for read 1 and read 2, respectively.

My current approach is to ensure that both files are properly paired and then perform two separate rounds of trimming, one for each file. After that I further process both files to filter the valid pairs. This seems like a lot of redundant work that cutadapt is in principle able to do.

Would be great to have this feature in cutadapt! Is this something that you can foresee to implement in the near future?

Thanks!

**Comment by marcelm** [comment]
Hi, this makes sense. I would prefer to add an uppercase `-L` option for R2, however. This would be more consistent with the `-A`/`-B`/`-G`/`-U`/`-Q` options, where also the lowercase variant is for R1 and the uppercase variant for R2. (`-m` and `-M` don’t follow this schema because I added them when Cutadapt didn’t have paired-end support.)
