### ISSUE TITLE
Adapters in form of file and linked mode

### ISSUE THREAD

**Issue by luigallucci** [marcelm/cutadapt#790]
Hi!

I'm using (actually stable version) and python 3.10. 

I'm trying to do demultiplexing of ONT sequences.

As they are single reads, I would like to remove FWD+barcode and REV+BARCODE in one move. The REV+BARCODE is equal to all of them, while the FWD+BARCODE is different. 
I'm usually working with 

`file:`

but now if give it `file:${fwd}...file:${rev}` this is recognizing all the line as a single path and so not working. 

Do you have a solution or suggestions?  Probably my approach is not properly right. 

Thank you for your time.

**Comment by marcelm** [comment]
Currently, the only way to use the `file:` notation with linked adapters is to put all of them in a single FASTA file like so:
```
>seq1
ACGTACGT...AACCGGTT
>seq2
CGTACGTA...CCGGTTAA
>seq3
...
```
That is, include the dots in the sequence in the FASTA record.

So if I understand correctly, because REV+BARCODE is always the same, you would need to take your file with FWD+BARCODE sequences and add `...REV+BARCODE` to each entry.

**Comment by luigallucci** [comment]
Thank you...not thinked about that before. 

Do you know also when I have an unknow output what that means? I'm actually demultiplexing.

**Comment by marcelm** [comment]
The `unknown` file contains all the reads in which no adapter (i.e. barcode) could be found.

**Comment by luigallucci** [comment]
thank you for your help!
