### ISSUE TITLE
What's the difference between using linked adapters and -g -a ?

### ISSUE THREAD

**Issue by hjarnek** [marcelm/cutadapt#809]
Hi,

I can't seem to find a clear distinction between the expected behaviour of linking adapters with `^FWD_ADAPTER...RC_REV_ADAPTER` as opposed to using `-g ^FWD_ADAPTER -a RC_REV_ADAPTER -n 2` (and conversely for the reverse reads). Is there supposed to be one?

I am following the [Trimming (amplicon-) primers from paired-end reads](https://cutadapt.readthedocs.io/en/stable/recipes.html#trimming-amplicon-primers-from-paired-end-reads) recipe, where using linked adapters is suggested if you want to check for primer readthrough. I note a small difference in the output between the two methods though: Using the `-g -a` method retains about 2000 read pairs more, out of about 1.3 million passed read pairs. It's insignificant, but obviously they're not identical. Would love to understand the difference.

And speaking of which, is there any downside of checking for primer readthrough on amplicon data? Even if your expected amplicon length is guaranteed to be longer than the sequencer output length, would it hurt? You may still have primer dimers, which would be nice to filter out if possible. When you work with other people's data, it may often also be unclear which of the fastq files have been cutadapted already, and using which parameters and so on, so the safest bet (and definitely the easiest) would be to run everything through cutadapt again using your preferred parameters – unless you risk changing the outcome by running cutadapt twice somehow, unaware of the parameters of the first run?

**Comment by marcelm** [comment]
In short, the extra read pairs that you get with `-n 2` are exactly those that linked adapters are designed to filter out because they don’t follow the expected read structure.

Linked adapters were added because using `-g`, `-a` in combination with `-n 2` has a couple of downsides. Mainly, Cutadapt doesn’t understand that the two adapters belong together:

- With `-n 2`, it’s possible that two 5' or two 3' adapters are removed from a read. Linked adapters prevent this.
- If a read does not contain the 5' adapter, but the 3' adapter, it doesn’t have the structure you want, but Cutadapt will still consider it "trimmed" and therefore count it as such in the report and keep it when using `--discard-untrimmed`.
   
   In linked adapters with an anchored 5' adapter, on the other hand, the 5' adapter is required: If it cannot be found, the search stops and the read is considered untrimmed. (The 3' adapter won’t even be searched for.)
- If you have a primer mix (multiple primer pairs), there’s no way to specify which 5' adapter goes with which 3' adapter. With linked adapters, you can just use multiple `-a` options.

The difference between the methods should be small, and that is also in line with your observation.

> And speaking of which, is there any downside of checking for primer readthrough on amplicon data? Even if your expected amplicon length is guaranteed to be longer than the sequencer output length, would it hurt?
> You may still have primer dimers, which would be nice to filter out if possible.

If you specify a 3' adapter that doesn’t really exist in the data, the only minor problem is that you may get some chance matches. That is, if your read happens to end with the first three (or more) nucleotides of the primer, then those will be trimmed.

That said, for primer dimers, the reverse primer should occur at full length in the read, so you can set the minimum overlap length to the length of the primer. Then there won’t be any chance matches. (Use something like `-a ^FORWARD...REVERSE;o=99`.)

> When you work with other people's data, it may often also be unclear which of the fastq files 
> have been cutadapted already, and using which parameters and so on, so the safest bet (and definitely the easiest) would be to run everything through cutadapt again using your preferred parameters – unless you risk changing the outcome by running cutadapt twice somehow, unaware of the parameters of the first run?

Generally, it is of course best if you know what is in the reads and to run Cutadapt only if necessary and only trimming the adapters or primers that you know exist in the data. That said, if you don’t remove many different adapters at the same time, it should be relatively safe to run it a second time on data that has already been trimmed. You can get some random matches as explained above (for those adapter types that allow partial matches), but that should not hapen too often.

Also, you can always run Cutadapt once (discarding the output with `-o /dev/null -p /dev/null`), look at the report to see what you find and only then decide which options to use for the actual trimming run. That’s what I do quite often when I’m not so sure what the data actually contains.

> have been cutadapted already,

(BTW, awesome to see Cutadapt being used as a verb :smile:.)

**Comment by hjarnek** [comment]
Thank you for your quick and clear answer, @marcelm! Then linked adapters is what I'm looking for.

It seems important to adjust the minimum overlap for the readthrough adapter, using the `;o=` parameter. Otherwise you get a lot of spurious matches, as the default is just 3. However, regardless of whether I do that, I only get up to 300 reads that were discarded because they were too short (i.e. assumed primer dimers) out of a couple of million input reads. And that is with a very strict `--minimum-length` of `200`. Isn't that unexpectedly low? Primer dimers should be more prevalent than that, shouldn't they?

I may be biased by our local lab lingo, but I actually thought cutadapting was a valid synonym for adapter trimming, like you say Vespa when referring to a moped, or champagne when referring to sparkling white wine 😀 Will continue using it.

**Comment by marcelm** [comment]
> Isn't that unexpectedly low? Primer dimers should be more prevalent than that, shouldn't they?

I can unfortunately not answer that since I don’t do so much amplicon trimming myself. I have a small test dataset with 10000 reads here that I looked at just now, and it does not contain any primer dimers.

> Will continue using it.

Maybe it’ll spread :smile:!

**Comment by hjarnek** [comment]
Ok, fair enough. Thank you again for your helpful comments! Will close this now.

**Comment by marcelm** [comment]
I added a note to the documentation, see https://cutadapt.readthedocs.io/en/latest/guide.html#linked-adapters (highlighted box at the end of the section).
