### ISSUE TITLE
Reproducible full report

### ISSUE THREAD

**Issue by nr0cinu** [marcelm/cutadapt#819]
Hi,

would be nice if there would be a command line flag to enable reproducible full reports, i.e., the report is always the same if the input is the same. Right now, [with the processing time and speed being added](https://github.com/marcelm/cutadapt/blob/bddd1aa59d9b3be9692355223d8180e6b4a89f64/src/cutadapt/report.py#L621), the report always changes.

Thanks,
Bela

**Comment by marcelm** [comment]
Good idea. Note that I purposefully omitted runtime from the JSON output so that it would be reproducible. But the normal report is older, and I didn’t think about reproducible output at that time.

I’m trying to avoid adding more command-line options if I can, so I’m wondering whether writing the final runtime to stderr would be an option. Cutadapt currently sends the report to stdout (if you use `-o` to send trimmed reads to a file) and prints a progress report to stderr that already contains the runtime. This line:
```
[ 8<---------] 00:00:03     1,740,000 reads @   1.7 µs/read;  35.26 M reads/minute
```
So information about runtime is already available and doesn’t actually need to be in the part of the report that is sent to stdout.

@nr0cinu Do you use Cutadapt with `-o`?

**Comment by nr0cinu** [comment]
> Do you use Cutadapt with -o?

I do.

> So information about runtime is already available and doesn’t actually need to be in the part of the report that is sent to stdout.

that would work for me :)

**Comment by marcelm** [comment]
Note to self: `adapters.py` also outputs elapsed time, but only if an index is built.
