### ISSUE TITLE
Sequence and quality different lengths

### ISSUE THREAD

**Issue by marcelm** [marcelm/cutadapt#96]
_From [mrbelhoc...@gmail.com](https://code.google.com/u/102736045343753683488/) on November 05, 2014 08:53:22_

I run cutadapt 1.2.1 python 2.6 linux x86_64
with SOLID file (csfasta and qual) color space

and i have this error :

Sequence and quality different lengths !!!

_Original issue: http://code.google.com/p/cutadapt/issues/detail?id=86_

**Comment by marcelm** [comment]
_From [marcel.m...@tu-dortmund.de](https://code.google.com/u/115749445199231802729/) on November 05, 2014 04:25:56_

Which commandline are you using? You need to use the -c parameter for colorspace data. See the documentation here: http://cutadapt.readthedocs.org/en/latest/colorspace.html

**Comment by marcelm** [comment]
_From [marcel.m...@tu-dortmund.de](https://code.google.com/u/115749445199231802729/) on March 08, 2015 14:32:59_

No reply for a while, so closing. Feel free to re-open if you still have the problem.

**Status:** Invalid

**Comment by skiniry** [comment]
Hi I know this issue is closed but I have the same issue even when using the colorspace parameter.

The exact command I use is this:
_cutadapt -c -a CGCCTTGGCCGTACAGCAG SRR1964306.fastq_


Which results in the following error:
_Traceback (most recent call last):
  File "/usr/local/bin/cutadapt", line 10, in <module>
    cutadapt.main()
  File "/usr/local/lib/python2.7/dist-packages/cutadapt/scripts/cutadapt.py", line 806, in main
    (n, total_bp) = process_reads(reader, pe_reader, adapter_matcher, quality_trimmer, modifiers, readfilter, trimmed_outfile, untrimmed_outfile, pe_outfile, rest_writer)
  File "/usr/local/lib/python2.7/dist-packages/cutadapt/scripts/cutadapt.py", line 485, in process_reads
    for read in reader:
  File "_seqio.pyx", line 146, in __iter__ (cutadapt/_seqio.c:3520)
  File "/usr/local/lib/python2.7/dist-packages/cutadapt/seqio.py", line 86, in __init__
    super(ColorspaceSequence, self).__init__(name, sequence, qualities)
  File "_seqio.pyx", line 54, in cutadapt._seqio.Sequence.__init__ (cutadapt/_seqio.c:1679)
ValueError: In read named 'SRR1964306.1 1\_2...': length of quality sequence and length of read do not match (51!=50)_

The cutadapt version I'm using is 1.4.2 but I have tried a newer version as well with the same result. 
Here is an example of some lines of the fastq file:

_@SRR1964306.1 1_2_1269 length=50
T2112222333020103030311231230222231111.222132222.30
+SRR1964306.1 1_2_1269 length=50
!@/@.@8/@@-@@@;;@;@-@@@3@@?<:0@@/@=@A@!--0/.567*!**
@SRR1964306.2 1_2_3296 length=50
T2131201023301211101303022322232303311.130321330.00
+SRR1964306.2 1_2_3296 length=50
!@/@@@@8@@8@8>@@@@6@@@@6@@<??@@@@2@>??!@@2383<>=!.*
@SRR1964306.3 1_2_3523 length=50
T2022003030302010303131123123022203111.232131220.00
+SRR1964306.3 1_2_3523 length=50
!@/86@@>/68?<<>>>@??;@@2=?@?3.2@@;@=@@!6-6/--50*!_

**Comment by marcelm** [comment]
Colorspace FASTQ files that can be downloaded from the Sequence Read Archive unfortunately include an extra (dummy) quality value in the beginning. Note the exclamation mark at the beginning of each quality line. Regular colorspace FASTQ files do not have a quality associated with the primer base ('T').

Cutadapt can deal with those files if you add the option `--format=sra-fastq`. It will then remove the dummy quality.

**Comment by Yinglei1** [comment]
Hello, I meet the same problems, and I do not know how to figure it out. I do not understand what is the length of quality sequence, could you please help me check what is the matter, thanks in advance.
<img width="960" alt="sequence" src="https://user-images.githubusercontent.com/59709147/72103421-78b49e00-3329-11ea-8300-25a9c1df8be5.png">
<img width="958" alt="error" src="https://user-images.githubusercontent.com/59709147/72103466-92ee7c00-3329-11ea-91e2-4717f559328c.png">
<img width="810" alt="grep" src="https://user-images.githubusercontent.com/59709147/72103483-9aae2080-3329-11ea-9493-ee57ae2bede2.png">

**Comment by marcelm** [comment]
The part where gzip complains is the important one: Your gzip file is incomplete. Perhaps the download was interrupted or the disk got full while you copied the file. (I believe more recent Cutadapt versions will give you a better error message here.)

**Comment by Yinglei1** [comment]
Thanks for your answers!

**Comment by Yinglei1** [comment]
Hi， I re-download the new data, but the new problem arise. but the line 1 started with @. Thanks in advance!
9533e229d51ba96a9648850559f6844
87f01dde52382d820f07ce16ed7e78e

**Comment by Yinglei1** [comment]
Hi， I re-download the new data, but the new problem arise. but the line 1 started with @. Thanks in advance!
<img width="727" alt="9533e229d51ba96a9648850559f6844" src="https://user-images.githubusercontent.com/59709147/72155668-e1485d00-33b3-11ea-8965-d70ec5da4d66.png">
<img width="952" alt="87f01dde52382d820f07ce16ed7e78e" src="https://user-images.githubusercontent.com/59709147/72155675-e3aab700-33b3-11ea-8616-03a84ad09fe9.png">

**Comment by marcelm** [comment]
It is possible that the line number 1 that the error message mentions is incorrect. Does running `zcat 609sra.fastq.gz > /dev/null` give you any error messages?

**Comment by Yinglei1** [comment]
I tried, but it did not show anything, thank you very much!

**Comment by marcelm** [comment]
- How did you download the data? (Which command exactly.)
- Can you try running the most recent Cutadapt version?

**Comment by Yinglei1** [comment]
I download the data directly, not using command. somebody said maybe there is blank line and I used WC to test the line number, and the number is not multiples of four, so I used: ""zcat 611sra.fastq.gz |sed '/^[  ]*$/d' |gzip >new611sra.fastq.gz "" to delate the bank line. line number before:185782857. the new line number,:185782856. and size of the previous data is 6286737kb, and new one is 4163552. I do not know if the command I did is right and why the size become much smaller just because of deleting one blank line. and one more question: if I meet such problem like the line is expected to started with @, or  the length of quality and length of read does not math, if there any ways that I can use to test what is the exact problem, because you know the warning shown is not always like the true one.

**Comment by marcelm** [comment]
> I download the data directly, not using command.

Ok. I cannot entirely reproduce the contents of your `609.fastq.gz` file, but I get close with `fastq-dump --gzip --split-spot SRR6813609`.

Note that your `609.fastq.gz` file contains *interleaved* paired-end reads. if you want to process this data correctly, you should use Cutadapt’s `--interleaved` option. This does not explain the error message, however.

> somebody said maybe there is blank line and I used WC to test the line number, and the number is not multiples of four, so I used: ""zcat 611sra.fastq.gz |sed '/^[ ]*$/d' |gzip >new611sra.fastq.gz "" to delate the bank line

If the number of lines is not divisible by four, the file is corrupt. In my opinion, you should not trust the file even after you have removed the blank line because that may not be the only problem. I wold just re-download the data from SRA. You could for example use the `fastq-dump` command that I mentioned above (but then you need to use `--interleaved` with Cutadapt) or `fastq-dump --gzip --split-files SRR6813609` or download the files from https://www.ebi.ac.uk/ena/data/view/SRR6813609 that are listed in the "FASTQ files (FTP)" column. In the last two cases, you will get the paired-end data in two files (`SRR6813609_1.fastq.gz` and `SRR6813609_2.fastq.gz`) that you need to process appropriately.

> if I meet such problem like the line is expected to started with @, or the length of quality and length of read does not math, if there any ways that I can use to test what is the exact problem, because you know the warning shown is not always like the true one.

I just tested it: The current Cutadapt version will give you the correct line number when it encounters this type of problem. Can’t you upgrade? You could at least temporarily install the most recent version and run it on the input file, just to see the error message (use just `cutadapt -o /dev/null 609sra.fastq.gz`, it is not necessary to provide more options).

**Comment by Yinglei1** [comment]
You are so nice, yes, you are right, I am also not sure about the data after deleting the blank line, I will try to use the command to download the data, the data you tested is right, which is what i using, one more question: i am filtering the data, not only cut the adapter, also deleting some reads with low qulity, so I using trim_Galore to do it, I am a new leaner, so I do not know if  Cutadapt can do it like this. I will still use the command to re-download the data, Thanks so much.

**Comment by marcelm** [comment]
I cannot help with using Trim Galore, but Cutadapt can do quality trimming. Try `cutadapt -q 20 -a TGGAATTCTCGG -o trimmed.fastq.gz 609sra.fastq.gz`, for example. More info is in the documentation.

**Comment by Yinglei1** [comment]
I will learn Cutadapt, thank you so much, have a nice day!

**Comment by marcelm** [comment]
Thanks, the same and good luck! Please open a new issue for any further questions.
